BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "{JPN}トレーナーに ひつような もの……\pちしき…\nせんりゃく…\lうん…\lとうし…\lこころ…\lゆうき…\lそして さいのう か……\pぼく ぜんぶ バッチリ じゃん!\nどこの しせつでも らくしょー だね\pえっ? ポケモン? なんのことだい?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "{JPN}フロンティアブレーンって しってる?\pバトルフロンティアに ある\n7つの しせつを かんりする\lとくべつな トレーナーたちの ことを\lエニシダは そうよんでる らしいわ$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "{JPN}ぼく バトルタワーで おねえちゃんに\nたたかいの さいのうが あるねって\lすごく ほめられたのー!\pでも ぼく ポケモン コンテストの\nほーが すき なの!\pでも ポケモン コンテストは\nぜんぜん だめだよ!\pさいのうって すきとは ちがうの?$"

