#ifndef GUARD_CONSTANTS_FAME_CHECKER_H
#define GUARD_CONSTANTS_FAME_CHECKER_H

#define FAMECHECKER_OAK          0
#define FAMECHECKER_DAISY        1
#define FAMECHECKER_BROCK        2
#define FAMECHECKER_MISTY        3
#define FAMECHECKER_LTSURGE      4
#define FAMECHECKER_ERIKA        5
#define FAMECHECKER_KOGA         6
#define FAMECHECKER_SABRINA      7
#define FAMECHECKER_BLAINE       8
#define FAMECHECKER_LORELEI      9
#define FAMECHECKER_BRUNO       10
#define FAMECHECKER_AGATHA      11
#define FAMECHECKER_LANCE       12
#define FAMECHECKER_BILL        13
#define FAMECHECKER_MRFUJI      14
#define FAMECHECKER_GIOVANNI    15
#define NUM_FAMECHECKER_PERSONS 16

// Hoenn-facing aliases. The raw slot values are kept compatible with the
// restored FRLG Fame Checker save layout and script command arguments.
#define FAMECHECKER_BIRCH       FAMECHECKER_OAK
#define FAMECHECKER_RIVAL       FAMECHECKER_DAISY
#define FAMECHECKER_STEVEN      FAMECHECKER_BROCK
#define FAMECHECKER_MAXIE       FAMECHECKER_MISTY
#define FAMECHECKER_ARCHIE      FAMECHECKER_LTSURGE
#define FAMECHECKER_ROXANNE     FAMECHECKER_ERIKA
#define FAMECHECKER_BRAWLY      FAMECHECKER_KOGA
#define FAMECHECKER_WATTSON     FAMECHECKER_SABRINA
#define FAMECHECKER_FLANNERY    FAMECHECKER_BLAINE
#define FAMECHECKER_NORMAN      FAMECHECKER_LORELEI
#define FAMECHECKER_WINONA      FAMECHECKER_BRUNO
#define FAMECHECKER_TATE_LIZA   FAMECHECKER_AGATHA
#define FAMECHECKER_JUAN        FAMECHECKER_LANCE
#define FAMECHECKER_WALLACE     FAMECHECKER_BILL
#define FAMECHECKER_WALLY       FAMECHECKER_MRFUJI
#define FAMECHECKER_SCOTT       FAMECHECKER_GIOVANNI

#define FCPICKSTATE_NO_DRAW    0
#define FCPICKSTATE_SILHOUETTE 1
#define FCPICKSTATE_COLORED    2

#endif //GUARD_CONSTANTS_FAME_CHECKER_H
