PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "{JPN}ホウエンちほう には\nいわ…… こおり…… はがね……\pそれぞれの ちからを つかさどる\n3びきの ポケモンが\lそれぞれ どこかの どうくつに いる……\pおれ ちいさな ころに\nそんな はなしを きいたことが あるよ$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "{JPN}「むっつの てんが\n みっつの とびらを あける」\pおじいちゃんが よく いっていたけど\nいまだに なんのことだか わからないわ$"
