gText_ApprenticeChallenge0::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge1::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge2::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge3::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge4::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge5::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge6::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge7::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge8::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge9::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge10::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge11::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge12::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge13::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge14::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticeChallenge15::
	.string "{JPN}{STR_VAR_1}さんの\n{STR_VAR_2}ばんめの でしです"
	.string "よろしく おねがいします$"

gText_ApprenticePleaseTeach0::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching0::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode0::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks0::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach1::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching1::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode1::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks1::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach2::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching2::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode2::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks2::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach3::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching3::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode3::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks3::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach4::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}{KUN}\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching4::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode4::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks4::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach5::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}{KUN}\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching5::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode5::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks5::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach6::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching6::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode6::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks6::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach7::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching7::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode7::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks7::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach8::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching8::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode8::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks8::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach9::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}{KUN}\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching9::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode9::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks9::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach10::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}{KUN}\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching10::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode10::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks10::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach11::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching11::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode11::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks11::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach12::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}さん\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching12::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode12::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks12::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach13::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}{KUN}\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching13::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode13::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks13::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach14::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}{KUN}\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching14::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode14::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks14::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticePleaseTeach15::
	.string "{JPN}はじめまして\n{STR_VAR_1}と いいます"
	.string "{PLAYER}{KUN}\nバトルを おしえてください$"

gText_ApprenticeRejectTeaching15::
	.string "{JPN}もうすこしだけ\nおしえてください"
	.string "よろしく おねがいします$"

gText_ApprenticeWhichLevelMode15::
	.string "{JPN}バトルタワーには\nレベル50と オープンが あります"
	.string "どちらに ちょうせんすれば\nいいですか?$"

gText_ApprenticeLevelModeThanks15::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "ありがとうございます$"

gText_ApprenticeWhatHeldItem0::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing0::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem0::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem1::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing1::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem1::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem2::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing2::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem2::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem3::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing3::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem3::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem4::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing4::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem4::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem5::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing5::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem5::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem6::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing6::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem6::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem7::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing7::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem7::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem8::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing8::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem8::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem9::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing9::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem9::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem10::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing10::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem10::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem11::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing11::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem11::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem12::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing12::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem12::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem13::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing13::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem13::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem14::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing14::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem14::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhatHeldItem15::
	.string "{JPN}{STR_VAR_1}には\nなにを もたせれば"
	.string "いいですか?$"

gText_ApprenticeHoldNothing15::
	.string "{JPN}もちもの なしで\nよろしいですか?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "{JPN}わかりました"
	.string "もちもの なしで いきます$"

gText_ApprenticeThanksHeldItem15::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "たいせつに つかいます$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "{JPN}{STR_VAR_1}は もう\nすすめてもらいました"
	.string "{STR_VAR_2}は もちものなしで\nよろしいですか?$"

gText_ApprenticeWhichMonFirst0::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks0::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst1::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks1::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst2::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks2::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst3::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks3::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst4::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks4::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst5::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks5::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst6::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks6::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst7::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks7::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst8::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks8::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst9::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks9::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst10::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks10::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst11::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks11::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst12::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks12::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst13::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks13::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst14::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks14::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMonFirst15::
	.string "{JPN}さいしょに だす ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonFirstThanks15::
	.string "{JPN}{STR_VAR_1}を さいしょに\nだします$"

gText_ApprenticeWhichMon0::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks0::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon1::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks1::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon2::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks2::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon3::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks3::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon4::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks4::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon5::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks5::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon6::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks6::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon7::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks7::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon8::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks8::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon9::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks9::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon10::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks10::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon11::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks11::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon12::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks12::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon13::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks13::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon14::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks14::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMon15::
	.string "{JPN}つぎの ポケモンは"
	.string "{STR_VAR_1}と {STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMonThanks15::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "なかまに します$"

gText_ApprenticeWhichMove0::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks0::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove1::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks1::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove2::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks2::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove3::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks3::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove4::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks4::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove5::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks5::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove6::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks6::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove7::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks7::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove8::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks8::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove9::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks9::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove10::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks10::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove11::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks11::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove12::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks12::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove13::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks13::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove14::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks14::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticeWhichMove15::
	.string "{JPN}わざは {STR_VAR_1}と"
	.string "{STR_VAR_2}の\nどちらが いいですか?$"

gText_ApprenticeMoveThanks15::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "おぼえました$"

gText_ApprenticePickWinSpeech0::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech1::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech2::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech3::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech4::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech5::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks5::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech6::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech7::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech8::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks8::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech9::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech10::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech11::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech12::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks12::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech13::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech14::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"

gText_ApprenticePickWinSpeech15::
	.string "{JPN}バトルに かったとき"
	.string "なんて いえば いいですか?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{JPN}{STR_VAR_1}ですね"
	.string "しょうりの ことばに します$"
