gText_ApprenticeChallenge0::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばん でしです!\nグスン…… きんちょう するなあ$"

gText_ApprenticeChallenge1::
	.string "{JPN}ぼく {STR_VAR_1}さんの\n{STR_VAR_2}ばんの でし なんだ! いくぞー!$"

gText_ApprenticeChallenge2::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんの でしだ!\nいざ しょうぶ!$"

gText_ApprenticeChallenge3::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんでしです…\nあたし なんかが かてる かな……?$"

gText_ApprenticeChallenge4::
	.string "{JPN}{STR_VAR_1}の {STR_VAR_2}ばん でしなの!\nしょうぶ して あげるわ!$"

gText_ApprenticeChallenge5::
	.string "{JPN}いそがしい なか {STR_VAR_1}さんの\n{STR_VAR_2}ばんの でし やってる オレです!$"

gText_ApprenticeChallenge6::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんの\nでしトレーナーよ よっろしくぅ!$"

gText_ApprenticeChallenge7::
	.string "{JPN}わたくし {STR_VAR_1}さまの {STR_VAR_2}ばんの\nでしで ございますの…… いきますわよ$"

gText_ApprenticeChallenge8::
	.string "{JPN}キャー! {STR_VAR_1}せんせいの\n{STR_VAR_2}ばん でし ですっ! がんばります!$"

gText_ApprenticeChallenge9::
	.string "{JPN}いえーい! {STR_VAR_1}さんの\n{STR_VAR_2}ばん でしの おじさんと しょうぶ!$"

gText_ApprenticeChallenge10::
	.string "{JPN}{STR_VAR_1}の 1000ばんめの でしだ!\nうそ ほんとは {STR_VAR_2}ばん! いくぞ!$"

gText_ApprenticeChallenge11::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}ばんの\nでしだぜ! ノリノリで いってみようぜー!$"

gText_ApprenticeChallenge12::
	.string "{JPN}イヤハァ! {STR_VAR_1}さんの\n{STR_VAR_2}ばんの でしとは オレのことっ!$"

gText_ApprenticeChallenge13::
	.string "{JPN}……ゴホっ ゴホっ よろしく!\n{STR_VAR_1}さんの {STR_VAR_2}ばんでしだ!$"

gText_ApprenticeChallenge14::
	.string "{JPN}て てれますが {STR_VAR_1}さんの\n{STR_VAR_2}ばんの でし やってます……!$"

gText_ApprenticeChallenge15::
	.string "{JPN}うそじゃない! わたしは\n{STR_VAR_1}さんの {STR_VAR_2}ばんの でしだ$"

gText_ApprenticePleaseTeach0::
	.string "{JPN}も もしかして {PLAYER}さん……?\lああ! グスっ……\pあ…… ごめんなさい!\nきんちょう して なみだが でちゃった……\pぼくは {STR_VAR_1} って いって\n{PLAYER}さんに あこがれて います!\lい いつか {PLAYER}さんに あって\lポケモンのこと おしえて もらう って\lゆめ みて いたんです……! うう……\pあのう あのう {PLAYER}さん!\nできたら…… ポケモンのこと\lおしえて ください!$"

gText_ApprenticeRejectTeaching0::
	.string "{JPN}そ そんな……\nう うう うわーん!\pおねがいです…… おねがい ですから……!$"

gText_ApprenticeWhichLevelMode0::
	.string "{JPN}えー ほんとですか!\nやった! うれしいよう! うぉぉーん!\pあ…… ごめん なさい\nうれしくて なみだが……\pあのう じゃあ おしえて ください!\nバトルタワーの へや なんですけど\lレベル50と オープンレベルの へや\lぼく だったら どっちが いいのかな……?$"

gText_ApprenticeLevelModeThanks0::
	.string "{JPN}{STR_VAR_1} ですね! うぅ うわーん!\pあ! ごめんなさい\n{PLAYER}さんが ぼくに へやを\lきめてくれた うれしさで なみだが……\p……グスン\nありがとう ございました!\lまた おはなし してください!$"

gText_ApprenticePleaseTeach1::
	.string "{JPN}うわー! {PLAYER}さん だよね?\nすごく つよい ひと なんだよね?\pボク {STR_VAR_1}!\nトレーナーに なった ばかり なんだ\pねえ おねがい {PLAYER}さん!\nぼくの せんせいに なって\lトレーナーのこと いっぱい おしえてよ!$"

gText_ApprenticeRejectTeaching1::
	.string "{JPN}えー? どうして?\nねーっ いいでしょ いいでしょ\lせんせいに なってよ おねがい!$"

gText_ApprenticeWhichLevelMode1::
	.string "{JPN}わーい やった!\nじゃあねー はじめに ききたい ことはね\lバトルタワーの こと!\pレベル50と オープンレベルの へや\nどっちが ボクに ピッタリ かなあ?$"

gText_ApprenticeLevelModeThanks1::
	.string "{JPN}{STR_VAR_1}か! そーだよね!\nじゃあ ボク がんばるね!\pまた こんど ここで あったら\nなにか おしえてね せんせい!$"

gText_ApprenticePleaseTeach2::
	.string "{JPN}あの…… {PLAYER}さん ですか!?\nぼく {STR_VAR_1} って いいます!\pぼく ポケモントレーナーに なりたいんだけど\nどうすれば いいのか わからなくて……\pそれで ゆうめいな {PLAYER}さんに\nどうすれば いいのか きいてみようと\lおもったんです!\pそうだんに のって もらえますか?$"

gText_ApprenticeRejectTeaching2::
	.string "{JPN}そんなあ!\nぼく どうしても ポケモントレーナーに\lなりたいんです!\pしつもんに こたえて もらえますか?$"

gText_ApprenticeWhichLevelMode2::
	.string "{JPN}ありがとう ございます!\nじゃあ さっそく さいしょの しつもん!\pバトルタワーって レベル50と オープンと\nふたつの レベルが ありますよね!\pどっちの レベルが\nぼくに あってると おもいますか?$"

gText_ApprenticeLevelModeThanks2::
	.string "{JPN}{STR_VAR_1} ですね! わかりました!\nじゃあ また しつもんが あったら\lここに くるので おしえて ください!$"

gText_ApprenticePleaseTeach3::
	.string "{JPN}あれ? え? あなたは……!\nいえ そんなはず ないわ\lあたし なんかが {PLAYER}さんに\lあえるはず なんて ないもん\p……ほんとに {PLAYER}さん なの?\nしんじられない おはなし できるなんて!\lああ こんな いいことが あったら\lあとは わるいこと ばっかり おきるんだわ\p……あ ごめんなさい\nあたし…… {STR_VAR_1} です……\lなんの とりえも ありません\lって じこしょうかい なんて しても\lどうせ すぐ わすれちゃいます よね……\p{PLAYER}さんに あえたら\nトレーナーとして そうだんに のって って\lおねがい しようと おもっていたけど\lどうせ ムリですよね?\p……それとも もしかして\nそうだんに のって もらえたり しますか?$"

gText_ApprenticeRejectTeaching3::
	.string "{JPN}やっぱり…… そうですよね\nあたし なんて ほんとに\lつまらない おんなのこで……\pでも もしかしたら って おもって……\nかんがえなおして なんて くれませんよね?\pけど やっぱり あきらめられない\nうんが いい うちに おねがいしよう!\l……そうだんに のって もらえますか?$"

gText_ApprenticeWhichLevelMode3::
	.string "{JPN}ほんとう ですか? しんじられない!\nあたし なんかの そうだんに\lのってもらえる なんて!\lうれしい です……\pほんとうに くだらないです けど\nあたし には きめられないん です\pバトルタワーって レベルが\nレベル50と オープンレベルと\lふたつ えらべる けど……\pあたし なんか でも がんばれそうな\nレベルって どっちの へや でしょうか?$"

gText_ApprenticeLevelModeThanks3::
	.string "{JPN}{STR_VAR_1} ですか わかりました!\nほんとうに こんな あたしでも\lだいじょうぶ でしょうか\lがんばって みます ダメかも しれないけど\pきょうは あたしなんかの ために\nありがとう ございました……!$"

gText_ApprenticePleaseTeach4::
	.string "{JPN}あっ! {PLAYER}{KUN} でしょ!?\nポケモン つよいって きいてるよ!\pわたしは {STR_VAR_1}\nおともだちに なって あげる!\pあのね トレーナーズスクール で\nおそわった こと だけじゃ\lバトルフロンティア では かてないの!\pそうだんに のってくれても いいわよ\nもちろん オーケー でしょ?$"

gText_ApprenticeRejectTeaching4::
	.string "{JPN}え? なんで ことわるの?\nあたしの おねがい なんだけど!\lかんがえなおしてよぉ!$"

gText_ApprenticeWhichLevelMode4::
	.string "{JPN}うん じゃあ おねがいね\nさっそく きめて ほしいことが あるから\pレベル50と オープンレベルの へやが\nバトルタワーに あるじゃない?\l{PLAYER}{KUN}は わたしには\lどっちが いいと おもう?$"

gText_ApprenticeLevelModeThanks4::
	.string "{JPN}そう {STR_VAR_1}が\nわたしに ふさわしいのね ありがと!\l{PLAYER}{KUN}が きめた って おもえば\lまけても きが らくだわ!\pじゃあね\nまた そうだんに のってね!$"

gText_ApprenticePleaseTeach5::
	.string "{JPN}ああ きみ! {PLAYER}{KUN}!\nゆうめい だから しってるぜ\lオレは {STR_VAR_1} よろしく!\pオレは トライアスリート やってて\nからだを きたえる かたわら\lポケモンも そだてて ほかにも\lバイトに ひるねに しゃこうダンス……\pいそがしくて なっかなか\nいい トレーナーに なれないんだよね!\pそこで おねがい!\pここで あえたのも なにかの ごえん!\n{PLAYER}{KUN} たまに オレに\lアドバイスを おねがい できないかな?$"

gText_ApprenticeRejectTeaching5::
	.string "{JPN}えー! たのむよ!\n{PLAYER}{KUN} みたいな ひとが\lオレには ひつよう なんだよー!\pオレに アドバイス たのむよ!$"

gText_ApprenticeWhichLevelMode5::
	.string "{JPN}サンキュー そう こなくっちゃ!\nんじゃ てはじめに かるいのを 1つね!\pあのさ バトルタワー って\nレベルが 2しゅるい あるじゃん?\lレベル50と オープンレベル!\pいそがしい オレ だったら\nどっちで がんばれば いいかな?$"

gText_ApprenticeLevelModeThanks5::
	.string "{JPN}{STR_VAR_1} ね! オーケー!\nなんとか じかん つくって やってみるぜ!\p……っと いけね バイトのじかんだ!\nじゃあ サンキュー またな!$"

gText_ApprenticePleaseTeach6::
	.string "{JPN}うっそ もしかして\nほんものの {PLAYER}さん?\pあっは! すごーい!\nわたし {STR_VAR_1}よ よろしくぅ!\p{PLAYER}さん って なんか\nとっても つよいんでしょ\lみんな うわさ してるもんね!\pあ! いいこと かんがえちゃった\nわたし {PLAYER}さんに\lアドバイスを もらおうっと!\lきっと つよく なれそう!\pねっ いいでしょ?\nわたしに アドバイス おねがい!$"

gText_ApprenticeRejectTeaching6::
	.string "{JPN}あははは! そんな いじわる いっても\nあたし には つうじないわよん!\lほんとは オーケー なんでしょ?$"

gText_ApprenticeWhichLevelMode6::
	.string "{JPN}わーい さっすが {PLAYER}さん!\nココロひろーい!\lまずは なにから きこうかなー?\l……あっ おもいついた!\pジャーン しつもんです!\nわたしが バトルタワーに いどむなら!\lレベル50のへや! オープンレベルのへや!\lさて どっちが にあっている でしょう?$"

gText_ApprenticeLevelModeThanks6::
	.string "{JPN}ほほぉー!\n{STR_VAR_1} と きましたか!\lシブイ おこたえ ありがとう!\pん きょうは こんなところ かな\nこんど また ここで あおうね!\lありがと!$"

gText_ApprenticePleaseTeach7::
	.string "{JPN}もし {PLAYER}さんで\nいらっしゃいますか?\pおめに かかれて うれしゅうございます\nわたくし {STR_VAR_1}と もうしますの\l{PLAYER}さんに かねてより\lあこがれて おりました……\p…… …… ……\pあの…… こんな おねがい\nおこまりに なるかも しれませんが…\pわたくしを {PLAYER}さんに\nでしいり させて いただけません?$"

gText_ApprenticeRejectTeaching7::
	.string "{JPN}まあ……!\p…… …… ……\n…… …… ……\p……あ ショックで きを うしないましたわ\nいいえ! きっと ききまちがい ですわ\pおねがい! わたくしを\nでしに して くださると おっしゃって!$"

gText_ApprenticeWhichLevelMode7::
	.string "{JPN}うっ うれしい ですわ……!\pでは さっそくですけど わたくしの\nそうだんを きいて くださいませ!\pわたくし いちど バトルタワーに\nちょうせん しようと おもっていますの\lただ レベルが ふたつ ありまして……\pわたくしは レベル50と オープンレベル\nどちらに ふさわしいと おもわれますか?$"

gText_ApprenticeLevelModeThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\nわかりました がんばりますわ!\pそれでは {PLAYER}さん\nこれからも よろしく おねがいしますわ\lごきげんよう!$"

gText_ApprenticePleaseTeach8::
	.string "{JPN}キャー! キャー!!!\n{PLAYER}さんに はなしかけられた!\lかっ かんげきっ……!\pわたし! {STR_VAR_1}と いいますっ!\nトレーナーに なって すぐに\lポケモンかいの おおもの {PLAYER}さんと\lおはなし できて かんどう してますっ!\pそそそそ そうだ!\n{PLAYER}さん おねがいが!\lわたしを でしに して くださいっ!\lいろいろ おしえて ほしいのですっ!$"

gText_ApprenticeRejectTeaching8::
	.string "{JPN}うっわああ!!\n{PLAYER}さんに ことわられた……\lきっ きちょうな けいけん だわっ!\p{PLAYER}さんっ! こんどは\nよい おへんじも きかせて くださいっ!\lわたしに ごしどうを おねがいしますっ!$"

gText_ApprenticeWhichLevelMode8::
	.string "{JPN}ひええええぇ! {PLAYER}さんに\nはい って いわれたああぁ!!\lきょうは もう ねむれない……\lおありがとう ございますう!\pではっ うかがいます!\nわたしは バトルタワー\lレベル50のへやと オープンレベルのへや\lどちらに むいてると おもわれますかっ?$"

gText_ApprenticeLevelModeThanks8::
	.string "{JPN}{STR_VAR_1} りょうかいですっ\nりょうかいで ありますっ!\lわたし かんげき です!\pでは また こんど\nいろいろと おしえて くださいね!$"

gText_ApprenticePleaseTeach9::
	.string "{JPN}ワォ! きみは\nもしや もしや {PLAYER}{KUN}!\lストロングで フェイマスな トレーナー!\lいや おじさん ラッキーだなー!\pハロウ おじさんは {STR_VAR_1}ね!\nポケモン ティーチャー さがしてるんだ\lそんな ときに グッドタイミングで\l{PLAYER}{KUN}が あらわれた!\pと いうわけで {PLAYER}{KUN}!\nおじさんを でしいり させて くれ!$"

gText_ApprenticeRejectTeaching9::
	.string "{JPN}ぐわーっ!\nきみも なかなか クールで タフだね……\lそんなこと いわずに おねがいだよ!$"

gText_ApprenticeWhichLevelMode9::
	.string "{JPN}おぅー! グッと くるね!\nエクセレント!\pでは ファースト アドバイス たのむね!\nバトルタワー なんだけどさ\lおじさんが やるなら レベルは\l50と オープン どっちが ベターかな?$"

gText_ApprenticeLevelModeThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\nオーケイ オーケイ!\lおじさん バーっと がんばって くるよ!\pそれじゃあ これからも よろしくね\nアディオース!$"

gText_ApprenticePleaseTeach10::
	.string "{JPN}お おいっ {PLAYER}{KUN}だろ!\nさっき おまわりさんが さがしてたぞ!\p…… …… ……\nなんてね うっそ うそ!\pおいらは {STR_VAR_1} って いうんだ\nこうみえても ポケモンチャンピオンさ!\l……て いうのも ウソ!\pじつは おいら ポケモンしょうぶが\nあんまり とくいじゃ なくてさ!\lひとつ どうだろ\lおいらの ししょうに なってくれない かな?$"

gText_ApprenticeRejectTeaching10::
	.string "{JPN}そんな つめたい こと いうと\nこうだぞ!\pうえーん うえーん えーん えん えん\pなんてね うそなき!\pね! いいだろ\nおいらの ししょうに なって おくれよ!$"

gText_ApprenticeWhichLevelMode10::
	.string "{JPN}やったー!\nおれいに ふねを かって あげよう!\pなんて じょうだん だけど……\nししょう! よろしく たのむぜ!\pあのさ バトルタワーで\nレベル50と オープンレベルと あるだろ!\pどっちで がんばれば いいか\nまよってるんだよ……\lししょうが きめて くれないかな?$"

gText_ApprenticeLevelModeThanks10::
	.string "{JPN}そうか\n{STR_VAR_1}が いいのね!\lじゃあ ちがうほうに いこうっと!\p…… なんて じょうだん!\nちゃんと ししょうの いうこと きくよ\pありがとう ししょう!\nまた あったら よろしくなー$"

gText_ApprenticePleaseTeach11::
	.string "{JPN}は・じ・め・ま・し・て!\nはーい はじめまして!\lわし ノリノリ ふなのり {STR_VAR_1}!\lきみも じこしょうかい いってみようぜ!\pふん ふん なまえは {PLAYER}{KUN}!\nポケモン だいすきで\lびみょうな おとしごろね!\pじつは きみは わしが はなしかけた\nほんじつ 10にんめの トレーナーでーす!\pこの であいを きねんして\nぜひとも わしを でしに してください!$"

gText_ApprenticeRejectTeaching11::
	.string "{JPN}そんな!\nノリが わるいじゃ ないか!\pな いいじゃ ないか\nぜひとも わしを でしに してください!$"

gText_ApprenticeWhichLevelMode11::
	.string "{JPN}ようよう! ノリが いいね!\n{PLAYER}さん よろしく たのみますよ!\pそれじゃあ 1つめの しつもん\nいってみようぜ!\lバトルタワーに かんする しつもんだ!\pレベル50のへやと オープンレベルのへや\nわしが いくなら さあ どっち?$"

gText_ApprenticeLevelModeThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\nそんなら ノリノリで いってみるぜ!\pこれからも ヨロシク たのむぜ\n{PLAYER}さん!$"

gText_ApprenticePleaseTeach12::
	.string "{JPN}ヒャホー {PLAYER}さんじゃなーい!?\nどうする オレ? はなしかけてみる!?\lってもう はなし してるよ!!\pって {PLAYER}さん あきれてる!?\nしかたねー じこしょうかい してみる!?\pオスっ オレっ {STR_VAR_1}!\nポケモン ギタリストかいの 1ばんぼしさ!\pって きいてる!? きいてる!!\nついでに たのみごと してみる!?\pあの {PLAYER}さん!\nオレを {PLAYER}さんの でしに して!$"

gText_ApprenticeRejectTeaching12::
	.string "{JPN}って ことわられてる オレっ!?\nしかたねー もういちど たのんでみる!?\pおねがい だよ {PLAYER}さん!\nオレを でしに してエェ!!$"

gText_ApprenticeWhichLevelMode12::
	.string "{JPN}やったラッキー うれしーよ オレ!!\nさっそく なんか そうだんしてみる!?\lしかも ここは バトルタワー だから\lそのへん から きいてみる!?\pあのさっ! バトルタワーで オレ\nどっちの レベルが にあってる!?$"

gText_ApprenticeLevelModeThanks12::
	.string "{JPN}{STR_VAR_1}だって!\nじゃ そこ いってみるよ!!\pって {PLAYER}さん\nオレの こと わすれんなよ!\lまた あおうぜ!!$"

gText_ApprenticePleaseTeach13::
	.string "{JPN}あ…… きみきみ!\nちょっとさ かた もんでくれる?\p……ああ そうそう そこそこ\nはー きもちいい!\pおれ {STR_VAR_1} って いうんだ\nカラテ やってるんだけど\lいまいち からだが よわくてさ……\pポケモンしょうぶも やって\nきたえようと おもって いるんだよね\pきみ ポケモンリーグで かった\n{PLAYER}{KUN} だろう?\lどうかな たまに おれの\lそうだんに のって もらえない かい?$"

gText_ApprenticeRejectTeaching13::
	.string "{JPN}えー なんで!\pそんなに めんどうは かけないからさ\nおねがいだよ!$"

gText_ApprenticeWhichLevelMode13::
	.string "{JPN}ありがとう わるいね\n……ゴホ ゴホっ!\pうう はやく きたえなきゃ……\nすぐに バトルタワーに いくから\lレベル50のへや オープンレベルのへや\lどっちが いいか きめてくれるかい?$"

gText_ApprenticeLevelModeThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\nじゃあ さっそく いってくる!\pこれからも おれを よろしく たのむよ!\nもう でしいり したんだからな!$"

gText_ApprenticePleaseTeach14::
	.string "{JPN}あ…… あ……\n{PLAYER}{KUN} だよね?\lそ そんなに みないで くれよ!\lてれるだろ\pワシは {STR_VAR_1}と いって\nは はずかしい けど\lいせきを さがしたり して くらしてるんだ\pでも バトルフロンティア にも\nはずかしながら き きょうみが あるんだ\p{PLAYER}{KUN}は ポケモン つよいって\nひょうばん だから……\lその いいづらいん だけど\lひとつ おねがいを したいんだ\pワシの せんせいに なって\nアドバイスして もらえない かな……?$"

gText_ApprenticeRejectTeaching14::
	.string "{JPN}こ ことわらないでくれ!\nワシに はじを かかせないで くれ!\pおねがい だから\nワシの せんせいに なってくれ!$"

gText_ApprenticeWhichLevelMode14::
	.string "{JPN}あ ありがとう……\pいや だから そんなに みないで くれよ\nてれるだろ\pめを あわせずに こたえて くれ!\pば バトルタワ…… バトルタワー だが\nどの レベルに ちょうせん すれば いい?$"

gText_ApprenticeLevelModeThanks14::
	.string "{JPN}よ よし!\nそれで がんばって みるよ\pうう はずかし がらずに\nがんばれる かな……?\pありがとう {PLAYER}{KUN}\nまた こんど あえたら…… よろしくね$"

gText_ApprenticePleaseTeach15::
	.string "{JPN}ん?\n{PLAYER}{KUN}の ように みえるが……\lほんもの なのかね?\pわたしは {STR_VAR_1}だ\nいまね だれか つよい トレーナーに\lでしいり したいと おもって いたんだよ\pきみが いるなら よかった!\n……ほんとうに {PLAYER}{KUN} だよね?\pいや ほんもの なら いいんだ\nわたしの でしいりを みとめて ほしい$"

gText_ApprenticeRejectTeaching15::
	.string "{JPN}え? なぜ ことわるのかね?\pほんものか どうか うたがって わるかった\nあやまるから でしいり させてほしい$"

gText_ApprenticeWhichLevelMode15::
	.string "{JPN}ほんとうに みとめて くれるのかね?\nぬかよろこびは したく ないからな\pいや ほんとうなら いいんだ わるかった\nさっそく そうだんに のってほしい\pわたしが バトルタワーに でるなら\nレベル50…… オープンレベル……\lどちらの ほうが ふさわしいと おもうかね$"

gText_ApprenticeLevelModeThanks15::
	.string "{JPN}{STR_VAR_1}…… ほんとうかね?\pいや ほんとう なら いいんだ\nどうも ありがとう\pこんな わたし だが\nでし として みとめて くれて うれしい\lいずれまた あおう!$"

gText_ApprenticeWhatHeldItem0::
	.string "{JPN}はあ…… シクシク\nああっ {PLAYER}さん!\pぼくね きめられない ことが あって\nちょっと こまってたんです\pきめられない のは {STR_VAR_1}に\nなにを もたせるかって ことなんです\lおしえて ください {PLAYER}さん\lなにか もたせた ほうが いいですか?$"

gText_ApprenticeHoldNothing0::
	.string "{JPN}えっ…… {STR_VAR_1}は\nなにも もたないほうが いいんですか?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "{JPN}わっ わかりました!\nきまって うれしいです うぉぉーん!\pじゃあ ありがとう ございました!$"

gText_ApprenticeThanksHeldItem0::
	.string "{JPN}よ よかった\n{STR_VAR_1}なら もってるかも……\lきまって うれしいです うぉぉーん!\pじゃあ ありがとう ございました!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "{JPN}うわーん! ひどいです\n{STR_VAR_1}は もう\lおしえてもらった どうぐ です グスン\pそれとも {STR_VAR_2}は\nなにも もたないほうが いいんですか?$"

gText_ApprenticeWhatHeldItem1::
	.string "{JPN}わー {PLAYER}さん だ!\nよかった! ききたい ことが あったんだ!\pあのね {PLAYER}さんは\nポケモンに どうぐを もたせてる?\lボクも もたせたいんだけど……\pボクの {STR_VAR_1}には\nなにを もたせたら いいのかな\l{PLAYER}さんは どう おもう?$"

gText_ApprenticeHoldNothing1::
	.string "{JPN}えっ {STR_VAR_1}は\nなにも もたせなくて いいって こと?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "{JPN}わかったー じゃあ そうするー!\nせんせい ありがと!$"

gText_ApprenticeThanksHeldItem1::
	.string "{JPN}へええ! {STR_VAR_1}かー\nじゃあ そうするー!\pせんせい ありがと!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "{JPN}あ えっと そうじゃなくて\nまだ おしえて もらってない どうぐで\lなにが いいか しりたいんだ!\pそれとも こんどは\nなにも もたせなくって いいのかな?$"

gText_ApprenticeWhatHeldItem2::
	.string "{JPN}{PLAYER}さん こんにちは!\nぼくの {STR_VAR_1}の ことなんだけど\pなにか もちものを もたせたいんだ!\nなにか いい もちもの おしえてください!$"

gText_ApprenticeHoldNothing2::
	.string "{JPN}じゃあ {STR_VAR_1}には\nなにも もたせなくても いいんだね?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "{JPN}わかりました!\nじゃあ また!$"

gText_ApprenticeThanksHeldItem2::
	.string "{JPN}{STR_VAR_1} ですか!\nわかりました!\pがんばって さがしてきます!\nじゃあ また!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "{JPN}{STR_VAR_1}は\nまえに おしえて もらいましたよ\pそれとは ちがう もちものを\nもたせたいんです\pそれとも {STR_VAR_2}には\nなにも もたせなくて いいんだね?$"

gText_ApprenticeWhatHeldItem3::
	.string "{JPN}{PLAYER}さん こんにちは……\nごめんなさい きょうも あたし\lききたい ことが あるんです\pあたしの ちから だけでは\nしょうぶに かてないかも しれないから\lなにか どうぐを {STR_VAR_1}に\lもたせようかと おもって いるんです\lでも なにが いいのか……\p{PLAYER}さん おねがいします\nあたしの かわりに きめてください!$"

gText_ApprenticeHoldNothing3::
	.string "{JPN}あの あたしなんかの ポケモンには\nなにも もたせないほうが いいんですか?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "{JPN}わかりました……\nどうぐに たよるなって ことですね?\lがんばって みます!\pありがとう ございます!$"

gText_ApprenticeThanksHeldItem3::
	.string "{JPN}{STR_VAR_1} ですか!\nあたしに みつけられるか……\lいえ! がんばって みます\pありがとう ございます!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "{JPN}え…… それは\nまえに おしえて いただいたと おもいます\pあ もしかして\nあたしが {STR_VAR_1}を\lつかいこなせて いないから ですか?\pそれとも {STR_VAR_2}には なにも\nもたせるなと いう こと でしょうか?$"

gText_ApprenticeWhatHeldItem4::
	.string "{JPN}あら {PLAYER}{KUN}\nちょっと ききたい ことが あるのよ!\pわたし ポケモンは きめて もらったけど\nどの どうぐを もたせるか までは\lきめて もらってない じゃない?\pどうせ なら さいごまで\nあなたが きめて くれない?\lねえ なにが いいかしら?\l{STR_VAR_1}に もたせたいの!$"

gText_ApprenticeHoldNothing4::
	.string "{JPN}あら! {STR_VAR_1}は\nてぶらで がんばれ って ことかしら?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "{JPN}それが よければ そうするわ!\n{PLAYER}{KUN}が きめた って おもえば\lまけても きが らくだわ!\pじゃあね\nまた そうだんに のってね!$"

gText_ApprenticeThanksHeldItem4::
	.string "{JPN}{STR_VAR_1}か\nわるく ないわね そうするわ!\l{PLAYER}{KUN}が きめた って おもえば\lまけても きが らくだわ!\pじゃあね\nまた そうだんに のってね!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "{JPN}えっ なに いってるのよ\n{STR_VAR_1}は もう\lおしえて もらった じゃない!\pそれとも {STR_VAR_2}は\nてぶらで がんばれ って ことかしら?$"

gText_ApprenticeWhatHeldItem5::
	.string "{JPN}よっ {PLAYER}{KUN}\nいそがしい わりには よく あうよね!\lオレは きょうは\lウォーキング クリーニング それに\lブラッシングと たいへん そのものさ!\pおかげで だいじな {STR_VAR_1}にも\nどうぐ さえ かって やれなくてねー\pあのさ! じかんも ないから\nなにを {STR_VAR_1}に\lもたせて やったら いいか\lそれだけでも アドバイス してよ!$"

gText_ApprenticeHoldNothing5::
	.string "{JPN}おっ それじゃ\nいそがしい オレの {STR_VAR_1}は\lなにも もたなくて イイ ってこと?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "{JPN}オーケー わかった!\nそれ なら じかんも いらないぜ\pきょうは サンキュー! じゃ またな!$"

gText_ApprenticeThanksHeldItem5::
	.string "{JPN}オーケー わかった!\nじゃ なんとか じかん つくって\l{STR_VAR_1}を さがすぜ!\pオレは いい せんせいに であえたよな\nサンキュー! じゃ またな!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "{JPN}あれっ {STR_VAR_1}は\nもう しってるよ!\pん? それとも\nいそがしい オレの {STR_VAR_2}は\lなにも もたなくて イイ ってこと?$"

gText_ApprenticeWhatHeldItem6::
	.string "{JPN}よぅ {PLAYER}さん わたしだよ!\nきょうも ひとつ そうだんが あるの\lアドバイス おねがい ねっ!\pジャーン では そうだんです!\nわたしの {STR_VAR_1}に\lなにか どうぐを もたせるなら\lいったい なにに したら いいかな?$"

gText_ApprenticeHoldNothing6::
	.string "{JPN}ふーん? {STR_VAR_1}は\nもちものは いらないって ことかな?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "{JPN}じゃ そうするね!\pん きょうは こんなところ かな\nこんど また ここで あおうね!\lありがと!$"

gText_ApprenticeThanksHeldItem6::
	.string "{JPN}ははぁーん!\n{STR_VAR_1}とは シブイわぁ\lぜひ そうして みるね!\pん きょうは こんなところ かな\nこんど また ここで あおうね!\lありがと!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "{JPN}あっはは やだぁ\n{STR_VAR_1}は もう\lおしえて もらった じゃない!\l{PLAYER}さん だいじょぶ?\pあ! それとも {STR_VAR_2}は\nもちものは いらないって ことかな?$"

gText_ApprenticeWhatHeldItem7::
	.string "{JPN}ごきげん いかがですか {PLAYER}さん\nきいて くださる?\pこのまえ たたかった トレーナーさん\nポケモンに なにか どうぐを\lもたせていた らしいんですの\pおかげで まけて しまいましたわ……\pわたくしも まけずに なにか\n{STR_VAR_1}に もたせたいんですの!\lなにが よろしいの でしょう\lきめて いただければ うれしいのですが……$"

gText_ApprenticeHoldNothing7::
	.string "{JPN}それは つまり…… どうぐは\nもたせなくて よろしいんですのね?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "{JPN}わかりましたわ!\nこのまま がんばる ことに しますわ\pそれでは {PLAYER}さん\nこれからも よろしく おねがいしますわ\lごきげんよう!$"

gText_ApprenticeThanksHeldItem7::
	.string "{JPN}{STR_VAR_1} ですのね!\nさっそく とりよせますわ!\pそれでは {PLAYER}さん\nこれからも よろしく おねがいしますわ\lごきげんよう!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "{JPN}それは もう おしえて いただいて\nわたくし もっておりますわ!\pそれとも…… {STR_VAR_2}には\nなにも もたせないで よろしいと……?$"

gText_ApprenticeWhatHeldItem8::
	.string "{JPN}{PLAYER}さんっ!\nきょうも あえて かんげき ですっ……!\pそそそそそ そうだっ!\nあのっ {PLAYER}さんに\lきめて ほしいことが あるのですっ!\pわたしの {STR_VAR_1}には\nなにを もたせれば いいですかっ?$"

gText_ApprenticeHoldNothing8::
	.string "{JPN}うわあぁっ いがいな おこたえだあ!\nつまり なにも いらないの ですねっ?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "{JPN}りょうかいで ありますっ!\nどうぐ なしで がんばるで あります!\pでは また こんど\nいろいろと おしえて くださいね!$"

gText_ApprenticeThanksHeldItem8::
	.string "{JPN}{STR_VAR_1} ですねっ!\nこれって これって {PLAYER}さんと\lもしかして おそろい だったりしてっ!\pもー ぜったい もたせちゃいます!\nでは また こんど\lいろいろと おしえて くださいね!$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "{JPN}あれ まえにも {STR_VAR_1}を\nおすすめして くれました よね!\pやっぱり コレが いちばん ですかっ?\nあ それとも もしかして\l{STR_VAR_2}には なにも\lもたせなくて いいって ことですかっ?$"

gText_ApprenticeWhatHeldItem9::
	.string "{JPN}ハロウ ハローウ\nマイ ティーチャー {PLAYER}{KUN}!\pきょうは ポケモンの どうぐに ついて\nアドバイスを おねがい したいんだ!\pおじさんの {STR_VAR_1}には\nどんな どうぐを もたせれば いいかな?\lパーっと きめちゃって くれ!$"

gText_ApprenticeHoldNothing9::
	.string "{JPN}おっと それは\n{STR_VAR_1}は なにも もたせずとも\lかてる っていう こと なのかな?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "{JPN}オーケイ オーケイ!\nおじさん グーっと がんばるよ!\pそれじゃあ これからも よろしくね\nアディオース!$"

gText_ApprenticeThanksHeldItem9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\nオーケイ オーケイ!\lおじさん ゴーっと さがして くるよ!\pそれじゃあ これからも よろしくね\nアディオース!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "{JPN}ノンノン! {STR_VAR_1}は\nまえに おしえて もらったよ!\pお それとも もしや\n{STR_VAR_2}は なにも もたせずとも\lかてる っていう こと なのかな?$"

gText_ApprenticeWhatHeldItem10::
	.string "{JPN}{PLAYER}{KUN} ちょっと\nしんじられん ことが おきた!\pけさ おきたら ポケモンが\nきんのたまを 10コ もってたんだ!\l…… なーんて うっそさ! うわはは!\pじつは おいら ポケモンの どうぐを\nかんがえる こと なんて\lあんまり とくいじゃ なくてさ!\lひとつ どうだろ おいらの {STR_VAR_1}\lなにを もたせたら いいのか\lししょうが きめて くれない かな?$"

gText_ApprenticeHoldNothing10::
	.string "{JPN}どういう ことかな?\nなにも もたせなくて いいんだな?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "{JPN}そうか てぶらで いいのね!\nじゃあ なにか もたせようっと!\p…… なんて じょうだん!\nちゃんと ししょうの いうこと きくよ\pありがとう ししょう!\nまた あったら よろしくなー$"

gText_ApprenticeThanksHeldItem10::
	.string "{JPN}そうか\n{STR_VAR_1}が いいのね!\lじゃあ それだけは やめとこっと!\p…… なんて じょうだん!\nちゃんと ししょうの いうこと きくよ\pありがとう ししょう!\nまた あったら よろしくなー$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "{JPN}あー それは いちど\nおしえて もらったことが あるだろ?\lちがうので なにか ないかな?\pそれとも {STR_VAR_2}は\nなにも もたせなくて いいのかな?$"

gText_ApprenticeWhatHeldItem11::
	.string "{JPN}こ・ん・に・ち・は!\nはーい こんにちは!\lノリノリ ふなのりの わしが おくる\lそうだんタイム いってみよう!\lどうぐに かんする そうだんだよ!\pわしの {STR_VAR_1}に もたせるなら\nさあ どんな どうぐがいい?$"

gText_ApprenticeHoldNothing11::
	.string "{JPN}それは あれかな? {STR_VAR_1}は\nなんにも もたなくて いいのかな?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "{JPN}そうかーっ! ようよう!\nそんなら ノリノリで てぶらでいくぜ!\pこれからも ヨロシク たのむぜ\n{PLAYER}さん!$"

gText_ApprenticeThanksHeldItem11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\nそんなら ノリノリで もたせてみるぜ!\pこれからも ヨロシク たのむぜ\n{PLAYER}さん!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{JPN}{STR_VAR_1}かーっ! おいおい!\nそれなら きいたことが あるぜ!\lなんか ちがうやつを たのむぜ!\pそれとも あれかな?\nなにも もたせなくて いいのかな?$"

gText_ApprenticeWhatHeldItem12::
	.string "{JPN}オッケ {PLAYER}さん!\nきょうも みつけたぜェ!\lどうする オレ? そうだんしてみる!?\lって もう はなしかけてる!?\pって {PLAYER}さん オレのこと そろそろ\nきらいに なってる!? なってない!!\lそうだんが あるんだけど きいてェ!\pオレの {STR_VAR_1} なんだけど\nいい どうぐを もたせたいんだ!\lなにが いいか さあ きめて!$"

gText_ApprenticeHoldNothing12::
	.string "{JPN}エェ!? じゃあ {STR_VAR_1}には\nなにも もたせなくて いいって こと!?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "{JPN}もたせないってエェ!\nじゃ いうとおりに するよ!!\pって {PLAYER}さん\nオレの こと わすれんなよ!\lまた あおうぜ!!$"

gText_ApprenticeThanksHeldItem12::
	.string "{JPN}{STR_VAR_1}だってエェ!\nじゃ さっそく もたせてみるよ!!\pって {PLAYER}さん\nオレの こと わすれんなよ!\lまた あおうぜ!!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "{JPN}ちょっと まったァ!\nその {STR_VAR_1}って\lまえに きいたことが ある!? ある!!\pほかのを おしえて!\nそれとも {STR_VAR_2}には\lなにも もたせなくて いいって こと!?$"

gText_ApprenticeWhatHeldItem13::
	.string "{JPN}ギャッ いててっ! {PLAYER}{KUN}\nうでが おれてるから さわらないでよ!\pポケモンに なにを もたせるか\nじぶんで いろいろ ためしすぎちゃって\lうでが おれちゃったん だよね きっと!\pというわけ だからさ\nかわりに きめて くれよ!\p{PLAYER}{KUN}はさ おれの {STR_VAR_1}\nどんな どうぐ もたせたら いいとおもう?$"

gText_ApprenticeHoldNothing13::
	.string "{JPN}いてて…… えーっと それって\n{STR_VAR_1}には なにも もたせなくて\lいいって ことかな?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "{JPN}ん わかった\nおれも いまは そのほうが たすかるよ!\pこれからも おれを よろしく たのむよ!$"

gText_ApprenticeThanksHeldItem13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\nじゃあ ポケモンの うでは ぶじだから\lさっそく もたせてみるよ!\pこれからも おれを よろしく たのむよ!$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "{JPN}いやいや {STR_VAR_1}は\nこのあいだ おしえて くれただろ?\lもっと すごいの おしえてくれよ!\pあ それとも\n{STR_VAR_2}には なにも もたせなくて\lいいって ことかな?$"

gText_ApprenticeWhatHeldItem14::
	.string "{JPN}あ…… あ……\n{PLAYER}{KUN}……\pそ そんなに みないで くれよ\nワシの ポケモン なにも もってないからさ\pちょっと…… そうだん させて くれよ\nは はずかしいん だけどさ!\l{STR_VAR_1}が なにを\lもったら つよいか って なやんでてさ\l{PLAYER}{KUN} なにが いいと おもう?$"

gText_ApprenticeHoldNothing14::
	.string "{JPN}じゃ…… {STR_VAR_1}は なにも\nもたない ほうが いいの かな……?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "{JPN}よ よし!\nどうぐ なしで いくよ!\pうう てれるな\nかっこ よすぎない かな……?\pありがとう {PLAYER}{KUN}\nまた こんど あえたら…… よろしくね$"

gText_ApprenticeThanksHeldItem14::
	.string "{JPN}よ よし!\n{STR_VAR_1}に してみるよ\pうう てれるな\nかっこ よすぎない かな……?\pありがとう {PLAYER}{KUN}\nまた こんど あえたら…… よろしくね$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "{JPN}それは も もう きいた じゃないか\pて てを ぬかないでくれ!\nワシに はじを かかせないで くれ!\pあ…… それとも\n{STR_VAR_2}は なにも\lもたない ほうが いいの かな……?$"

gText_ApprenticeWhatHeldItem15::
	.string "{JPN}ん?\n{PLAYER}{KUN}の ように みえるが……\lほんもの なのかね?\lふたごの きょうだい って ことは?\pあっ いやいや いやいや!\nほんもの なら いいんだ わすれてくれ!\lさらに じょげんを おねがい したい!\pこの わたしの {STR_VAR_1}!\nなにか べんりな どうぐを もたせたい\lいったい どれが ふさわしい かな?$"

gText_ApprenticeHoldNothing15::
	.string "{JPN}なにも もたない ほうが いい……?\nほんとうかね?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "{JPN}いや そうか なら いいんだ\nどうも ありがとう\pでは いずれまた あおう!$"

gText_ApprenticeThanksHeldItem15::
	.string "{JPN}{STR_VAR_1}…… ほんとうかね?\pいや ほんとう なら いいんだ\nどうも ありがとう\lこんな わたしの ポケモンでも\lつかいこなせると いいな\pでは いずれまた あおう!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "{JPN}いやいや まってくれ\nそれは まえに おしえてくれた だろう\lそれとは ちがった ものを\lすすめられて みたいんだ\pそれとも {STR_VAR_2}は\nなにも もたない ほうが いい……?\lほんとうかね?$"

gText_ApprenticeWhichMonFirst0::
	.string "{JPN}えーん {PLAYER}さーん!\nぼく こまって いるんです グスン\pそろそろ しょうぶを して みたいけど\nポケモンを どんな じゅんばんで\lだしたら つよいのか わかんない……\p{PLAYER}さん だったら\nどの ポケモンを さいしょに だすか\l……おしえて ください!$"

gText_ApprenticeMonFirstThanks0::
	.string "{JPN}{STR_VAR_1} ですね! うぅ うわーん!\pあ! ごめんなさい\nじゅんばんが きまった うれしさで\lなみだが……\pじゃあ ありがとう ございました!$"

gText_ApprenticeWhichMonFirst1::
	.string "{JPN}わわっ! {PLAYER}さんだー!\nわーい あえて よかった\lそうだん したいことが あるんだ!\pあのね ぼくの もってる\nポケモン たちの なかで\lどれを さいしょに だせば\lいいと おもう?$"

gText_ApprenticeMonFirstThanks1::
	.string "{JPN}{STR_VAR_1}かあ そーだよね!\nじゃあ そうするー!\pせんせい ありがと!$"

gText_ApprenticeWhichMonFirst2::
	.string "{JPN}{PLAYER}さん こんにちは!\nしょうぶのときって さいしょに\pどの ポケモンを だすのかが\nとても だいじな きが するんです!\pぼくが もってる ポケモンの なかで\nどの ポケモンを\lさいしょに だすと いいでしょうか?$"

gText_ApprenticeMonFirstThanks2::
	.string "{JPN}{STR_VAR_1} ですね!\nわかりました!\pじゃあ また!$"

gText_ApprenticeWhichMonFirst3::
	.string "{JPN}{PLAYER}さん いつも\nそうだん ばかりで すみません……\lあたし じしんが なくって\l{PLAYER}さんが いないと……!\pあの ポケモンの じゅんばん って……\nどうすれば いいと おもいますか?\pあたし なんかが こだわっても\nしかたが ないかも しれません けど\lどうしても きめられなくて……\pどの ポケモンを 1ばん\nせんとうに すれば よいんでしょうか!$"

gText_ApprenticeMonFirstThanks3::
	.string "{JPN}{STR_VAR_1} ですか わかりました!\pこんな あたし なんかに\nなんども こたえて いただけるなんて\lしんじられない!\pきょうは あたしなんかの ために\nありがとう ございました……!$"

gText_ApprenticeWhichMonFirst4::
	.string "{JPN}{PLAYER}{KUN}! わたしよ\nよかったわ こまっていたの!\pちょっと ポケモンの じゅんばんを\nきめて もらえる かしら!\lと いっても そうねえ\lとりあえず 1ばんめの ポケモンで いいわ\lどの ポケモンに したら いいかしら?$"

gText_ApprenticeMonFirstThanks4::
	.string "{JPN}{STR_VAR_1}ね いいわ!\n{PLAYER}{KUN}が きめた って おもえば\lまけても きが らくだわ!\pじゃあね\nまた そうだんに のってね!$"

gText_ApprenticeWhichMonFirst5::
	.string "{JPN}ハイ! オレの せんせい\n{PLAYER}{KUN}!\pきょうも いそがしいんだ オレ\nサイクリングに ショッピングに ハミング!\pしょうぶに つかう ポケモンの\nじゅんばんさえ きめられなくてねー\pあのさ!\nちょっと オレの ポケモン みてよ!\lで どいつが はじめに でれば いいかな?$"

gText_ApprenticeMonFirstThanks5::
	.string "{JPN}オーケー わかった!\n{STR_VAR_1}を せんとうに する\nじかん くらいは あるぜ!\p……と いけね かのじょが まってる!\nサンキュー! じゃ またな!$"

gText_ApprenticeWhichMonFirst6::
	.string "{JPN}ヤッホー ハーイ {PLAYER}さーん\nいつも つよそうな かおで あるいてるわね\pねえねえ! きょうも\nあれ…… おねがい! いいでしょ!\pジャーン では ほんじつの そうだん!\nわたしが もっている ポケモン!\lさあ どのコを いちばん\lさいしょに だせば いいでしょう?$"

gText_ApprenticeMonFirstThanks6::
	.string "{JPN}ふむふむ!\n{STR_VAR_1} ですねぇ?\lシブイ おこたえ ありがとう!\pん きょうは こんなところ かな\nこんど また ここで あおうね!\lありがと!$"

gText_ApprenticeWhichMonFirst7::
	.string "{JPN}はなしかけて くださって\nありがとう ございます {PLAYER}さん\pその おやさしさに あまえて\nきょうも そうだんが ありますの……\pあの ポケモンの じゅんばんを\nきめて いただきたいん ですの\pさいしょに だす なら\nどの ポケモンが よろしいでしょうか?$"

gText_ApprenticeMonFirstThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\nすぐに ならびかえますわ!\pそれでは {PLAYER}さん\nこれからも よろしく おねがいしますわ\lごきげんよう!$"

gText_ApprenticeWhichMonFirst8::
	.string "{JPN}キャーキャー!\n{PLAYER} さーんっ!\lきょうも あえて かんげきっ……!\pわたしの ポケモンたち\nつよく なりましたよ!\lでも はじめに だす ポケモンで\lかったり まけたり しちゃうんです\p{PLAYER}さん おねがいが!\nどのコを はじめに だしたら いいのか\lぜひ きめて ほしいのですっ!$"

gText_ApprenticeMonFirstThanks8::
	.string "{JPN}はあああ…… しあわせすぎる\n{PLAYER}さんに きめて もらうなんて!\lりょうかいですっ! わたし\l{STR_VAR_1}から いくで ありますっ!\pでは また こんど\nいろいろと おしえて くださいね!$"

gText_ApprenticeWhichMonFirst9::
	.string "{JPN}ハローウ!\nマイ ティーチャー {PLAYER}{KUN}\lきょうも アドバイス バンバンたのむよ!\pおじさん スリー ポケモンズで\nティームを つくったのは いいんだが\lまだ じゅんばんが きまって ないんだよ\pそこで! {PLAYER}{KUN}が\nまず はじめに だす ポケモンを\lササーっと きめちゃって くれ!$"

gText_ApprenticeMonFirstThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\nオーケイ オーケイ!\lおじさん ガガーっと いれかえるよ!\pそれじゃあ これからも よろしくね\nアディオース!$"

gText_ApprenticeWhichMonFirst10::
	.string "{JPN}{PLAYER}{KUN} きいてくれ たいへんだ!\nおいらの ポケモンと きたら\l3びき いっしょに とびだすんだよ!\l……なんて わきゃ ないな わはは!\pじつは おいら ポケモンの\nじゅんばん なんて きめるの\lあんまり とくいじゃ なくてさ!\lひとつ どうだろ おいらの ポケモン\lどいつを さいしょに だしたら いいか\lししょうが きめて くれない かな?$"

gText_ApprenticeMonFirstThanks10::
	.string "{JPN}そうか\n{STR_VAR_1}が いいのね!\lじゃあ そいつだけは やめようっと!\p…… なんて じょうだん!\nちゃんと ししょうの いうこと きくよ\pありがとう ししょう!\nまた あったら よろしくなー$"

gText_ApprenticeWhichMonFirst11::
	.string "{JPN}こ・ん・に・ち・は!\nはーい こんにちは!\lノリノリ ふなのりの わしの\lきょうの そうだん いってみようよ!\lじゅんばんに かんする そうだんだよ!\pこたえて! この なかで\nせんとうに したい ポケモンは どれ?$"

gText_ApprenticeMonFirstThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\nそんなら ノリノリで いれかえるぜ!\pこれからも ヨロシク たのむぜ\n{PLAYER}さん!$"

gText_ApprenticeWhichMonFirst12::
	.string "{JPN}ヤァーフゥー {PLAYER}さんじゃーん?\nどうする オレ? アレきいてみる!?\lそうだんが あるんだけど きいてェ!\lって きいてる!? きいてる!!\pオレの ポケモンの うち どいつを\nさいしょに だしたら いいか きめてエェ!$"

gText_ApprenticeMonFirstThanks12::
	.string "{JPN}{STR_VAR_1}だって! イエス!\nじゃ そうしてみる!!\pって {PLAYER}さん\nオレの こと わすれんなよ!\lまた あおうぜ!!$"

gText_ApprenticeWhichMonFirst13::
	.string "{JPN}うう {PLAYER}{KUN} ……\nおなか いたくってさ ちょっとまって……\p……ああ なおってきた……\pどの ポケモンを しょうぶのとき\nさいしょに だすか なやんで いて\lなやみ すぎちゃったん だよね きっと!\pというわけ だからさ\nかわりに きめて くれよ!\p{PLAYER}{KUN}はさ おれの ポケモン\nどれを さいしょに だせば\lかてると おもうかい?$"

gText_ApprenticeMonFirstThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\nじゃあ ごはんを たべたら\lそういうふうに してみるよ!\pこれからも おれを よろしく たのむよ!$"

gText_ApprenticeWhichMonFirst14::
	.string "{JPN}あ…… あ……\n{PLAYER}{KUN} だよね?\lそ そんなに みないで くれよ!\lてれるだろ\lひとつ…… そうだん させてよ\pは はずかし ながら\nポケモン 3びき きまった けどさ\lじゅんばんが きまらないんだよ\pどの ポケモンを 1ばんめに\nだせば かっこが つくの かな……?$"

gText_ApprenticeMonFirstThanks14::
	.string "{JPN}よ よし!\n{STR_VAR_1}から だして みるよ\pうう はずかし がらずに\nがんばれる かな……?\pありがとう {PLAYER}{KUN}\nまた こんど あえたら…… よろしくね$"

gText_ApprenticeWhichMonFirst15::
	.string "{JPN}ん?\n{PLAYER}{KUN}の ように みえるが……\lかげむしゃ って ことは ないだろうね\pいやいやいや! ほんものなら いいんだ\nおこらないで くれ!\lそして じょげんを おねがい したい!\pわたしの てもちの なかから\nどのポケモンを しょうぶの はじめに\lだせば いいのか おしえて ほしい$"

gText_ApprenticeMonFirstThanks15::
	.string "{JPN}{STR_VAR_1}……\nうそでは ないだろうね?\pいや ほんとう なら いいんだ\nどうも ありがとう\lこんな わたしだが がんばって みよう\pでは いずれまた あおう!$"

gText_ApprenticeWhichMon0::
	.string "{JPN}グスン……\nあっ {PLAYER}さん!\lちょうど よかったよう\lぼく きめられない ことが あって……\pあのね ポケモンをね\nどっちを つかうか きめられないんです\p{STR_VAR_1} と {STR_VAR_2}で\nまよって いるんだけど……\l{PLAYER}さんは どっち だったら\lぼくでも かてそう って おもいますか?$"

gText_ApprenticeMonThanks0::
	.string "{JPN}グスっ わ わかりました!\nあ ごめんなさい うれしくて なみだが……\pぼく がんばって {STR_VAR_1}を\nつかまえてみます!\pじゃあ ありがとう ございました!$"

gText_ApprenticeWhichMon1::
	.string "{JPN}あっ! {PLAYER}さんだー!\nわーい ちょうど よかった\lきょうも ボクの そうだんに のってね!\pあのね ボクね\n{STR_VAR_1}と {STR_VAR_2}の どっちを\lつかうか まよっちゃったの\pどっちを そだてようかなあ\n{PLAYER}さんは どう おもう?$"

gText_ApprenticeMonThanks1::
	.string "{JPN}へえ\n{STR_VAR_1}が いいのか!\lじゃあ そうするー!\pせんせい ありがと!$"

gText_ApprenticeWhichMon2::
	.string "{JPN}{PLAYER}さん こんにちは!\nちょっと しつもん させて ください!\p{STR_VAR_1} と {STR_VAR_2} で\nどっちを つかうか なやんでるんです!\pどっちの ポケモンが\nつよいと おもいますか?$"

gText_ApprenticeMonThanks2::
	.string "{JPN}{STR_VAR_1} ですね!\nわかりました!\pよし さっそく\nつよい {STR_VAR_1}を つかまえるぞ!\pじゃあ また!$"

gText_ApprenticeWhichMon3::
	.string "{JPN}{PLAYER}さん……!\nあの あたしの ことなんて\lどうせ わすれて しまいました よね\p……それでも いいです から\nそうだんに のって ください……\pあたし そだてたい ポケモン ひとつ\nじぶんで きめられなくって……\l{STR_VAR_1} か {STR_VAR_2}\lどちらかに する までは きまったけど\lそこで まよってしまって……\p{PLAYER}さん いやかも しれませんが\nあたしの かわりに きめてください!$"

gText_ApprenticeMonThanks3::
	.string "{JPN}あたし なんかの いうこと\n{STR_VAR_1}が きいて くれるか……\pでも やって みます!\pそのまえに つかまえられるか……\nいえ! がんばって みます\pありがとう ございます!$"

gText_ApprenticeWhichMon4::
	.string "{JPN}{PLAYER}{KUN} よかった\nさがしに いこうと おもってたのよ!\pねえ わたしが つかう ポケモン\nあなたが きめて くれない?\pそうね……\n{STR_VAR_1}と {STR_VAR_2}だったら\lどっちが いいと おもう?$"

gText_ApprenticeMonThanks4::
	.string "{JPN}{STR_VAR_1}ね ありがと!\n{PLAYER}{KUN}が きめた って おもえば\lまけても きが らくだわ!\pじゃあね\nまた そうだんに のってね!$"

gText_ApprenticeWhichMon5::
	.string "{JPN}あっれー\n{PLAYER}{KUN} じゃない げんき?\lオレは あいかわらず いそがしくてさ!\pポケモンも がんばりたいんだ けど\nどいつを つかうかも きまんなくてねー\pあのさ!\n{STR_VAR_1}って つよそう じゃん?\lでも {STR_VAR_2}も すてがたいよねー\p{PLAYER}{KUN} アドバイス してよ!\nどっちの ポケモンが イイかな?$"

gText_ApprenticeMonThanks5::
	.string "{JPN}オーケー わかった!\nじゃ なんとか じかん つくって\l{STR_VAR_1}を つかまえて みるぜ!\pオレは いい せんせいに であえたよな\nサンキュー! じゃ またな!$"

gText_ApprenticeWhichMon6::
	.string "{JPN}あっ わーい\n{PLAYER}さん じゃない!\lわたし さっそく ともだちに\lしりあいだって じまん しちゃったよ!\pねえねえ きょうも アドバイス おねがい!\nかんたんな こと だから ねっ!\pジャーン では しつもんです!\nわたしが そだてる なら!\l{STR_VAR_1}と {STR_VAR_2} さあどっち?$"

gText_ApprenticeMonThanks6::
	.string "{JPN}へっえー!\n{STR_VAR_1} と きますかぁ!\lシブイ おこたえ ありがとう!\pん きょうは こんなところ かな\nこんど また ここで あおうね!\lありがと!$"

gText_ApprenticeWhichMon7::
	.string "{JPN}まあ {PLAYER}さんでは?\nごきげんよう……!\pあなたに でしいり して わたくし\nすこし じしんが ついて まいりました!\lポケモンを さっそく そだてたいと\lおもって おりますの!\pそれでね {PLAYER}さんに\nわたしの ポケモンを\lきめていただく わけには まいりませんか?\p{STR_VAR_1}と {STR_VAR_2}……\nどちらの ポケモンが よろしいでしょう?$"

gText_ApprenticeMonThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\nさっそく さがして きますわ!\pそれでは {PLAYER}さん\nこれからも よろしく おねがいしますわ\lごきげんよう!$"

gText_ApprenticeWhichMon8::
	.string "{JPN}キャー {PLAYER}さんに また あえた!\nかっ かんげきっ……!\pそそそ そうだわっ!\nせっかく あえたん ですもの\lこの チャンスを のがす ては ないわっ!\p{PLAYER}さん おねがいが!\nわたしの ポケモンを きめて くださいっ!\p{STR_VAR_1}と {STR_VAR_2}と\nどちらが いいか きめて ほしいのですっ!$"

gText_ApprenticeMonThanks8::
	.string "{JPN}うわぁぁ きめて もらっちゃったあ!\n{STR_VAR_1} ですねっ!\lがんばって そだてるで あります!\pでは また こんど\nいろいろと おしえて くださいね!$"

gText_ApprenticeWhichMon9::
	.string "{JPN}ヘイ ヘイ {PLAYER}{KUN}!\nおじさんの ポケモン ティーチャー!\pハロウ きみを さがしてたんだよ\nアドバイスを おねがいするよ!\pおじさんが つかう ポケモン\nどっちが いいかな?\l{STR_VAR_1}か {STR_VAR_2}か\lパーっと きめちゃって くれ!$"

gText_ApprenticeMonThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ね\nオーケイ オーケイ!\lおじさん ガーっと つかまえて くるよ!\pそれじゃあ これからも よろしくね\nアディオース!$"

gText_ApprenticeWhichMon10::
	.string "{JPN}{PLAYER}{KUN} たいへんだ たいへんだ!\nまぼろしの ポケモン つかまえちゃった!\l……なんて うそさ! わっはっは\pじつは おいら ポケモン つかまえるの\nあんまり とくいじゃ なくてさ!\lひとつ どうだろ おいらの ポケモン\lどいつを つかまえたら いいか\lししょうが きめて くれない かな?\pどっちが いいかな?\n{STR_VAR_1}と {STR_VAR_2}だと……$"

gText_ApprenticeMonThanks10::
	.string "{JPN}そうか\n{STR_VAR_1}が いいのね!\lじゃあ ちがうほうに しようっと!\p…… なんて じょうだん!\nちゃんと ししょうの いうこと きくよ\pありがとう ししょう!\nまた あったら よろしくなー$"

gText_ApprenticeWhichMon11::
	.string "{JPN}こ・ん・に・ち・は!\nはーい こんにちは!\lノリノリ ふなのりの わし\lきみは とうぜん おぼえてるだろ?\pきょうも わしの しつもん いってみよう!\nポケモンに かんする そうだんだよ!\p{STR_VAR_1} と {STR_VAR_2}\nわしが つかまえるなら さあ どっち?$"

gText_ApprenticeMonThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\nそんなら ノリノリで さがしてくるぜ!\pこれからも ヨロシク たのむぜ\n{PLAYER}さん!$"

gText_ApprenticeWhichMon12::
	.string "{JPN}ゥワォ {PLAYER}さんじゃなーい!?\nどうする オレ? そうだんしてみる!?\lって もう はなしかけてる!?\pオスっ ひさしぶり ですっ!\nそうだんが あるんだけど きいてェ!\lって きいてる!? きいてる!!\lオレの ポケモン なにに したらいいかな!\p{STR_VAR_1}と {STR_VAR_2}\nどっちが いいか さあ きめて!$"

gText_ApprenticeMonThanks12::
	.string "{JPN}{STR_VAR_1}だってエェ!\nじゃ さっそく さがしてみるよ!!\pって {PLAYER}さん\nオレの こと わすれんなよ!\lまた あおうぜ!!$"

gText_ApprenticeWhichMon13::
	.string "{JPN}{PLAYER}{KUN}かぁ\nおれ あたま いたくてさ……\pどの ポケモンに するか\nなやみ すぎちゃったん だよね きっと\lというわけ だからさ\lかわりに きめて くれよ!\p{PLAYER}{KUN}はさ おれの ポケモン\n{STR_VAR_1}と {STR_VAR_2} だったら\lどっちが あってると おもうかい?$"

gText_ApprenticeMonThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\nじゃあ たいちょうの いいときに\lさがしてみるよ!\pこれからも おれを よろしく たのむよ!$"

gText_ApprenticeWhichMon14::
	.string "{JPN}あ…… あ……\n{PLAYER}{KUN} だよね?\lそ そんなに みないで くれよ!\lてれるだろ\lちょっと…… そうだん させて くれよ\pは はずかしいん だけどさ!\nつかいたい ポケモンで なやんでててさ\l{STR_VAR_1}と {STR_VAR_2}だったら\lどっちを つかったら いい かな……?$"

gText_ApprenticeMonThanks14::
	.string "{JPN}よ よし!\n{STR_VAR_1}で がんばって みるよ\pうう はずかし がらずに\nがんばれる かな……?\pありがとう {PLAYER}{KUN}\nまた こんど あえたら…… よろしくね$"

gText_ApprenticeWhichMon15::
	.string "{JPN}ん?\n{PLAYER}{KUN}の ように みえるが……\lほんもの なのかね?\pいや ほんもの なら いいんだ\nついでに でしの わたしに\lじょげんを おねがい したい!\pわたしが つかう ポケモンの ことだが\n{STR_VAR_1}と {STR_VAR_2}であれば\lどちらが わたしに ふさわしい かな?$"

gText_ApprenticeMonThanks15::
	.string "{JPN}{STR_VAR_1}…… ほんとうかね?\pいや ほんとう なら いいんだ\nどうも ありがとう\lこんな わたし でも\lなんとか つかい こなせると いいな\pでは いずれまた あおう!$"

gText_ApprenticeWhichMove0::
	.string "{JPN}うわーん {PLAYER}さんだ!\nぐすん ひっく\lぼく なやんで いるんですよう!\lぼくの {STR_VAR_1}のね わざが\lなかなか きまらないん です……\pあのう あのう!\n{PLAYER}さん きめて もらえませんか?\p{STR_VAR_1}の わざ\n{STR_VAR_2}と {STR_VAR_3}なら\lどっちが いいんでしょう……?$"

gText_ApprenticeMoveThanks0::
	.string "{JPN}{STR_VAR_1} ですね!\nうぅ うわああぁん!\pあ! ごめんなさい\n{PLAYER}さんが わざを\lきめてくれた うれしさで なみだが……\p……グスン\nありがとう ございました!\lまた おはなし してください!$"

gText_ApprenticeWhichMove1::
	.string "{JPN}{PLAYER}せんせい こんにちは!\nまた おしえて ほしいことが あるの!\pぼくの {STR_VAR_1}に\nかっこいい わざを おしえたいの!\lおすすめは どっちかな?\p{STR_VAR_2}か {STR_VAR_3}が\nいいんだけど……$"

gText_ApprenticeMoveThanks1::
	.string "{JPN}{STR_VAR_1}か! そーだよね!\nじゃあ ボク それで いくね!\pまた こんど ここで あったら\nなにか おしえてね せんせい!$"

gText_ApprenticeWhichMove2::
	.string "{JPN}{PLAYER}さん こんにちは!\nぼくの {STR_VAR_1}の こと なんだけど\lわざの ことで なやんでるんです\p{STR_VAR_2} と {STR_VAR_3}\nどっちの わざが つよいのか……\p{STR_VAR_1}には どっちの わざが\nあってると おもいますか?$"

gText_ApprenticeMoveThanks2::
	.string "{JPN}{STR_VAR_1} ですね!\nわかりました!\pよし さっそく\n{STR_VAR_1}を おぼえさせるぞ!\pじゃあ また!$"

gText_ApprenticeWhichMove3::
	.string "{JPN}ああ {PLAYER}さん!\nあたし あたし ほんと ダメなんです!\pポケモンを いざ そだてようと しても\n……わざ ひとつ まともに きめられなくて\lどうしようも ありません……\p{PLAYER}さんには そんな こと\nどうでも いいのは わかってます……\lでも あたし……\pおねがいです {PLAYER}さん\nあたしの {STR_VAR_1}の わざ\lきめて いただけませんか?\p{STR_VAR_2}と {STR_VAR_3}か\nどちらかを えらんで くださるだけでも!$"

gText_ApprenticeMoveThanks3::
	.string "{JPN}わかりました!\pあたし なんかの ために\n{STR_VAR_1}を おぼえて くれるか……\lいえ! がんばって みます\pありがとう ございます!$"

gText_ApprenticeWhichMove4::
	.string "{JPN}あら! {PLAYER}{KUN}\nあいたいと おもって いたの!\lわたしの {STR_VAR_1}に ふさわしい わざは\lなにかなー って まよってて……\lあなたが きめて くれない?\pそうね……\n{STR_VAR_2}と {STR_VAR_3}だったら\lどっちが いいと おもう?$"

gText_ApprenticeMoveThanks4::
	.string "{JPN}{STR_VAR_1}ね ありがと!\n{PLAYER}{KUN}が きめた って おもえば\lまけても きが らくだわ!\pじゃあね\nまた そうだんに のってね!$"

gText_ApprenticeWhichMove5::
	.string "{JPN}あー いそがしい いそがしい!\nおっと きみは {PLAYER}{KUN}!\lちょうしは どう?\pこっちはさ! けさ おきてから\nジョギング スイミング クッキング\lいそがしいの なんのって……!\pオレの {STR_VAR_1}に\nおしえさせる わざも きまんなくてねー\pあのさ!\n{STR_VAR_2} って よさそうじゃん?\lでも {STR_VAR_3} も イイよね!\p{PLAYER}{KUN}の アドバイス たのむよ!\nどっちの わざが イイかな?$"

gText_ApprenticeMoveThanks5::
	.string "{JPN}オーケー わかった!\nじゃ スケジュール あけて\lおぼえさせて みるぜ!\pほんと きみって いい せんせい だぜ\nサンキュー! じゃ またな!$"

gText_ApprenticeWhichMove6::
	.string "{JPN}おおっ ラッキー!\n{PLAYER}さんに あえましたー!\lさっそく ききたいことが あるのー!\pジャーン では\nほんじつの そうだんでーす!\pわたしの {STR_VAR_1}には\n{STR_VAR_2}と {STR_VAR_3}\lおにあいの わざは さあどっち?$"

gText_ApprenticeMoveThanks6::
	.string "{JPN}ははぁーん\n{STR_VAR_1} が イイですか!\lシブイ おこたえ ありがとう!\pん きょうは こんなところ かな\nこんど また ここで あおうね!\lありがと!$"

gText_ApprenticeWhichMove7::
	.string "{JPN}ごきげんよう {PLAYER}さん……!\nあのね きょうも\lわたくし そうだんが あるのです\lわたくしの かわいい\l{STR_VAR_1}ちゃんの ことですの\p{STR_VAR_1}ちゃんに ピッタリの わざ……\n{STR_VAR_2}と {STR_VAR_3}の\lどちらを おしえたら よろしいでしょう?$"

gText_ApprenticeMoveThanks7::
	.string "{JPN}{STR_VAR_1} ですのね!\nさっそく そのように しますわ!\pそれでは {PLAYER}さん\nこれからも よろしく おねがいしますわ\lごきげんよう!$"

gText_ApprenticeWhichMove8::
	.string "{JPN}キャァァ {PLAYER}さんが いるーっ!\nかっ かんげきっ……!\lこまった ときは {PLAYER}さんですっ!\pほんじつは わざの オススメを\nおしえて ほしいのですっ!\lわたしの {STR_VAR_1}の わざを\lきめて くださいっ!\pどっちが いいですかっ?\n{STR_VAR_2}と {STR_VAR_3}!$"

gText_ApprenticeMoveThanks8::
	.string "{JPN}ああぁ ありがとう ございますっ!\n{STR_VAR_1} ですねっ\lりょうかいで ありますっ!\pでは また こんど\nいろいろと おしえて くださいね!$"

gText_ApprenticeWhichMove9::
	.string "{JPN}ハロウ {PLAYER}{KUN} ハロウ!\nおじさん きょうも きみに\lアドバイスを もらいたいんだ プリーズ!\pマイ ポケモン {STR_VAR_1}の\nベストな わざは なんだろう?\lババーっと かてちゃいそうな わざ!\p{STR_VAR_2} かな?\nオア {STR_VAR_3} かな?$"

gText_ApprenticeMoveThanks9::
	.string "{JPN}あはぁ {STR_VAR_1}ねー\nオーケイ オーケイ!\lおじさん ザザーっと おぼえさせるよ!\pそれじゃあ これからも よろしくね\nアディオース!$"

gText_ApprenticeWhichMove10::
	.string "{JPN}{PLAYER}{KUN} たいへんだぞ!\nおいらの ポケモンが なんと\lわざを 6つ おぼえたんだ!\p……なんてね ウソだよ! ははは!\pじつは おいら ポケモンの わざ きめるの\nあんまり とくいじゃ なくてさ!\lひとつ どうだろ ししょうが\lオススメのわざ きめて くれない かな?\p{STR_VAR_2} と {STR_VAR_3}\n{STR_VAR_1}なら どっちが あうかい?$"

gText_ApprenticeMoveThanks10::
	.string "{JPN}そうか\n{STR_VAR_1}が いいのね!\lじゃあ ちがうわざに しようっと!\p…… なんて じょうだん!\nちゃんと ししょうの いうこと きくよ\pありがとう ししょう!\nまた あったら よろしくなー$"

gText_ApprenticeWhichMove11::
	.string "{JPN}こ・ん・に・ち・は!\nはーい こんにちは!\lノリノリ ふなのりの わしだぜー!\pよーし きょうの わしの そうだん\nいってみようぜー!\lわざに かんする そうだんだよ!\p{STR_VAR_2}と {STR_VAR_3}\n{STR_VAR_1}が おぼえるなら どっちだ?$"

gText_ApprenticeMoveThanks11::
	.string "{JPN}{STR_VAR_1}かーっ! ようよう!\nそんなら ノリノリで おぼえさせるぜ!\pこれからも ヨロシク たのむぜ\n{PLAYER}さん!$"

gText_ApprenticeWhichMove12::
	.string "{JPN}イエァ {PLAYER}さんじゃないのー?\nどうする オレ? また はなしかける!?\lってもう はなしかけてる!?\lって {PLAYER}さん あきれてる!?\lしかたねー そうだん してみる!?\pきょうも そうだんに のってェ!\nって きいてる!? きいてる!!\pおれの {STR_VAR_1}の わざ\nどうしたら いいかな? きめてエェ!\l{STR_VAR_2}!? {STR_VAR_3}!?$"

gText_ApprenticeMoveThanks12::
	.string "{JPN}{STR_VAR_1}で オーライ!\nじゃ さっそく おぼえさせるぜェ!!\pって {PLAYER}さん\nオレの こと わすれんなよ!\lまた あおうぜ!!$"

gText_ApprenticeWhichMove13::
	.string "{JPN}ガハゴホ あ {PLAYER}{KUN}\nカゼ ひいちゃったよ おれ……\pポケモンに おしえる わざを\nきめたいんだけど ムリっぽいん だよね\lというわけ だからさ かわりに たのむよ!\p{PLAYER}{KUN}はさ おれの {STR_VAR_1}\n{STR_VAR_2}と {STR_VAR_3}なら\lどっちが あってると おもうかい?$"

gText_ApprenticeMoveThanks13::
	.string "{JPN}ん わかった {STR_VAR_1}な!\nじゃあ カゼが なおったら\lゴホ おしえて みるよ!\pこれからも おれを よろしく たのむよ!$"

gText_ApprenticeWhichMove14::
	.string "{JPN}あ…… あ……\n{PLAYER}{KUN} だよね?\lそ そんなに みないで くれよ!\lてれるだろ\lまた…… そうだん させて くれよ\pは はずかしながらさ\nポケモンに おしえる わざがさ\lきまんないんだ アドバイス くれよ!\pポケモンは {STR_VAR_1}なんだ\nだったら どっちが いい かな……?\n{STR_VAR_2}…… {STR_VAR_3}……$"

gText_ApprenticeMoveThanks14::
	.string "{JPN}よ よし {STR_VAR_1}\nいって みるよ!\pそんな わざを おしえるなんて\nて てれるな……\pありがとう {PLAYER}{KUN}\nまた こんど あえたら…… よろしくね$"

gText_ApprenticeWhichMove15::
	.string "{JPN}ん?\n{PLAYER}{KUN}の ように みえるが……\lほんものかな?\lさいきん はやりの モノマネ では?\pいやいや! ほんもの ならいいんだ!\nきを わるく しないでくれ!\lそして ついでに でしの わたしに\lじょげんを おねがい したい\lわたしの {STR_VAR_1}の ことだ!\p{STR_VAR_2} と {STR_VAR_3}\nどっちの わざが つかえたら いいかね?$"

gText_ApprenticeMoveThanks15::
	.string "{JPN}{STR_VAR_1}……\nまちがいなく そうなの かね?\pいや ほんとう なら いいんだ\nどうも ありがとう\lこんな わたしの ポケモンでも\lおぼえて くれると いいな\pでは いずれまた あおう!$"

gText_ApprenticePickWinSpeech0::
	.string "{JPN}ああっ {PLAYER}さん\n{PLAYER}さんだ! わわーん!\lぐすん ひっく きいて ください\pぼくっ ぼく しょうぶ するとき\nものすごく きんちょう して\lかっても ないちゃうん です……\pなにか かっこいい こと いえたら\nいいなと おもうんです けど……\pあのう あのう {PLAYER}さん\nもし よかったら……\lぼく なかなくて いいように\lなにか かったときに いう ことばを\lかんがえて もらえませんか?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{JPN}{STR_VAR_1}\p…… うぉぉーん!\nすごく かっこいいよう!\pあ ごめんなさい\nうれしすぎて なみだが……\p……グスン {PLAYER}さん!\nいつも いつも ありがとう ございました!\lぼく {PLAYER}さんの ためにも\lがんばって たたかい つづけます!\pでは {PLAYER}さん!\nこんどは…… どこかで たたかいましょう!$"

gText_ApprenticePickWinSpeech1::
	.string "{JPN}{PLAYER}せんせい こんにちは!\nぼく きめたい ことが あるの!\pあのね!\nぼく しょうぶに かった とき\lなにか かっこいい セリフを いいたいの!\pせんせい おすすめの\nかっこいい セリフって あるかな?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{JPN}{STR_VAR_1}\pうわあー いーね!\nじゃあ ボク それで いくね!\pせんせい いままで ありがとう!\nボク これから いろんな ところで\lがんばる ことに する!\pこんど あうときは しょうぶ だよ!$"

gText_ApprenticePickWinSpeech2::
	.string "{JPN}{PLAYER}さん こんにちは!\nポケモンの じゅんびは\pばんぜん なんですけど\nひとつ きに なってるんです\pポケモントレーナーって\nしょうぶに かった ときに かけごえ が\pあると いいかなーって おもうんです\nなにか いいの かんがえて ください!$"

gText_ApprenticeWinSpeechThanks2::
	.string "{JPN}{STR_VAR_1}\p……かっこいいですね!\nそれ つかわせて いただきます!\pじゃあ ぼくは これから\nいろんな ところで しょうぶ してきます!\pいつか {PLAYER}さんと\nしょうぶ する ひが\lくるかも しれませんね!\pでは こんどは しょうぶの ば で\nおあい しましょう!$"

gText_ApprenticePickWinSpeech3::
	.string "{JPN}あっ {PLAYER}さん……!\nあたし ほんと ダメな おんなのこです!\pせっかく……\nせっかく しょうぶに かっても\lことば ひとつ でてこなくって……\p{PLAYER}さんには そんな こと\nどうでも いいのは わかってます!\lでも あたし どうしても……\pおねがい! です {PLAYER}さん\nかったとき って\lなんて いうべき なんでしょうか……?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{JPN}{STR_VAR_1}\pすごいわ……\pあ あたしなんかが\nそんな こと いって いいのか……\lいえ! がんばって みます\p{PLAYER}さん!\pいままで あたしなんかの ために\nありがとう…… ございました……!\lあたし いまから がんばってきます!\pあたしの こと なんて\nすぐに わすれて しまうと おもうけど\lでも どこかで おあい しましょう!$"

gText_ApprenticePickWinSpeech4::
	.string "{JPN}あら {PLAYER}{KUN}?\nちょっと きいて ほしいんだけど!\pじぶんでも わかって いるけど\nわたし すこし くちが わるくて……\lしょうぶに かったときに\lなんか えらそうに しちゃうのよね!\pだけど きらわれたく ないから\nわたしに まけた あいてに\lやさしい ことばを かけて あげたいのよ!\pでも ぜんぜん おもいつかなくて!\nあなたが かんがえて くれない?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{JPN}{STR_VAR_1}\pわるく ないわね!\nうん それで いくことに するわ!\pじゃあ…… いままで\n{PLAYER}さんに おそわった\lいろいろな ことを むねに\lわたし がんばって くる!\lいろいろと なまいき いって\lごめんなさい!\pつぎに あう ときは しょうぶよ!\nじゃあね!$"

gText_ApprenticePickWinSpeech5::
	.string "{JPN}あー いそがしい いそがしい!\nおっと さがしてたよ {PLAYER}{KUN}\lきょうも げんきかい?\pこっちはさー! あいかわらず\nランニング ファイティング マッピングと\lなんで こんなに いそがしいんだ?\pでもさ! いそがしい からって\nしょうぶに かった ときに\lなにも いわないで\lたちさっちゃ しつれいだろ?\pでさ!\nかっこよく たちさる オレを\lえんしゅつする いい ことば ないかな?\l{PLAYER}{KUN} なんか たのむよ!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{JPN}{STR_VAR_1}\pオーケー わかった!\nそのぐらい いう じかんは つくれるぜ!\lほんと きみ みたいな\lいい せんせいに であえて よかったぜ!\pオレは これから じかんを つくって\nポケモンしょうぶを してくるよ!\lいままで サンキュー {PLAYER}{KUN}!\pいつか オレと しょうぶ しようぜ!$"

gText_ApprenticePickWinSpeech6::
	.string "{JPN}やったねーっ\n{PLAYER}さんに あえちゃった!\lさっそく そうだんが あるのよ!\pジャーン\nでは さいごの そうだん でーす!\pわたしが しょうぶで かった とき\nかっこよく キメたいと したら\lさあ なんて いえばいい?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{JPN}{STR_VAR_1}\pいっ イイ!\nシブイ! それいただき!\p……ねえ わたし\nそろそろ いちにんまえに なったよね!\pあのね これから いろんなひとと\nたたかって みようと おもうの!\p{PLAYER}さんの アドバイス\nすっごく たすかったよー!\lいつか しょうぶする ときが くるかもね\lいままで ほんと ありがとー!$"

gText_ApprenticePickWinSpeech7::
	.string "{JPN}まあ {PLAYER}さん\nあえて よかった ですわ……!\pわたくし ポケモンの ほうは\nもう しんぱい ないのです けれど\lわたくし じしんの ほうが……\pその あの ポケモントレーナーさんは\nいつも しょうぶに かったとき\lことばを かけて くださいますね?\pぜひ! わたくしも あれを\nやってみたいのです!\lおねがいです! なにか\lかったときの ことば きめて ください!$"

gText_ApprenticeWinSpeechThanks7::
	.string "{JPN}{STR_VAR_1}\pですのね……!\pああ! なんだか わたくし\nうまれかわれる きが しますわ……!\lさっそく そのことば つかってみますわ!\pそれでは ここで おわかれです……\n{PLAYER}さんの ごしどう\lわたくし けっして わすれずに\lみなさまと たたかって まいります!\pまた いずれ……\nごきげんよう!$"

gText_ApprenticePickWinSpeech8::
	.string "{JPN}キャァー!\n{PLAYER}さんを はっけんーっ!\lかっ かんげきっ……!\pあのっ そうだんが あります!\pこのあいだ ポケモンしょうぶに\nかったは いいんですけど!\lわたし かんげき しすぎちゃって\lなんにも いえなく なっちゃって……!\pそこで {PLAYER}さん!\nわたしが かった ときの きめぜりふ!\lかんがえて ほしいのですっ!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{JPN}{STR_VAR_1}\pう うわああぁぁあ!\nこの ことばを わたしが!\lかっ かんげき………っ!!\pあああ ありがとう ございますっ!\nもう おもいのこす ことは ありませんっ!\lわたし これから たびだって\lいろいろな ひとと しょうぶ してみます!\pなにもかも {PLAYER}さんの\nおかげで あります!\lほんとうに ありがとう ございますっ!\pそれでは それでは\nいつか しょうぶの ばで あいましょう!$"

gText_ApprenticePickWinSpeech9::
	.string "{JPN}ハッローウ\nハロウ {PLAYER}{KUN}!\pおじさん そろそろ あちこちで\nしょうぶが したく なって きたよ!\lそこで そのまえに きみに\lアドバイスを もらいたいんだ プリーズ!\pおじさんが もし しょうぶに かったら\nあいての トレーナーに むかって\lじまん するような ことばって ないかな?$"


gText_ApprenticeWinSpeechThanks9::
	.string "{JPN}{STR_VAR_1}\pあはぁ それいいね\nオーケイ オーケイ!\lおじさん ババーっと いってみるよ!\pそれじゃあ おわかれだ!\nいままで いろいろ ありがとうね\lいつか しょうぶも してくれよ!\pアディオース!$"

gText_ApprenticePickWinSpeech10::
	.string "{JPN}{PLAYER}{KUN} たいへんだーっ!\pおいら しょうぶに かつと\n1じかんも えばっちゃうんだ!\p……なんてね ウソなんだよ! うっはは\pじつは おいら ひとと はなし するの\nあんまり とくいじゃ なくてさ!\lひとつ どうだろ\lおいらが しょうぶに かったときに\lいう ことばを\lししょうが きめて くれない かな?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{JPN}{STR_VAR_1}\pこう いえば いいのね!\nじゃあ それだけは やめておこうっと!\p…… なんて じょうだん!\nちゃんと ししょうの いうこと きくよ\pずっとずっと ありがとう ししょう!\nおいら やっと トレーナーって もんが\lわかった きがするよ!\pいまから いろんな やつと\nしょうぶして かって くるぞ!\lししょう とも しょうぶ するかもな!\pそれじゃな!\nさらばだ ししょう!$"

gText_ApprenticePickWinSpeech11::
	.string "{JPN}こ・ん・に・ち・は!\nはーい こんにちは!\lノリノリ ふなのりの わしだぜー!\pよーし さいごの わしの そうだん\nいってみようぜー!\lことばに かんする そうだんだよ!\pわしが もし しょうぶで かったら\nどういう ことばで キメたら いいかな?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{JPN}{STR_VAR_1}\pなるほどーっ! ようよう!\nそんなら ノリノリで それ つかうぜ!\pそろそろ わしも すだつと するか\nノリノリで たたかい まくるぜ!\lいろいろと ありがとうな!\pお・つ・か・れ・さ・ま!\nはーい おつかれさま ごきげんよう!$"

gText_ApprenticePickWinSpeech12::
	.string "{JPN}オーイェッ {PLAYER}さあん!\nどうする オレ? きょうも きいてみる?\lってもう きこうとしてる!?\pそもそも {PLAYER}さんって\nいつも きいてる!? きいてる!!\lじゃ そうだんに のってェ!\pおれが かった ときに さけぶ\nカッコイイ キメキメの\lすんごい セリフ……\lなんか かんがえてエエェ!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{JPN}{STR_VAR_1}\pオーラーイ オーライ!\nじゃ さっそく それでいくぜェ!\pってオレ もう\nきくことが なくなったぜ!\lしかたねー これで おわかれする!?\lとかいって どこかで ちゃっかり\lまた あえちゃったり するかも!?\pまー とりあえずは おわかれだぜ!\pって {PLAYER}さん\nオレの こと わすれんなよ!\lじゃあな {PLAYER}さん! スキだぜェ!$"

gText_ApprenticePickWinSpeech13::
	.string "{JPN}{PLAYER}{KUN} おれは\nもう ダメだよ……\lはなみずが とまらなくってさ……\pしょうぶに かった ときに\nなにか かっこいいこと いおうとして\lあたまで かんがえてたら……\pわれながら ジーンと なけちゃって\nはなみずが でたんだよね きっと!\lというわけ だからさ\l{PLAYER}{KUN} かんがえてよ!\pしょうぶに かったら\nおれ なんて いえば いいかな?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{JPN}{STR_VAR_1}\p…… …… ……いいよ\nそれ いいよ!\lダメだ なみだが また とまらないよ\pでも なみだと はなみずを こらえて\nそのセリフ つかわせて もらうよ!\pおれは もう {PLAYER}{KUN}に\nききたい ことは なくなった!\lこれからは ライバルだよ!\pん いままで ありがとうな!$"

gText_ApprenticePickWinSpeech14::
	.string "{JPN}あ…… あ……\n{PLAYER}{KUN} だよね?\lそ そんなに みないで くれよ!\lてれるだろ\pまた…… そうだん させて くれよ\nこ これで さいごに するからさ\pあのさ はずかしいん だけどさ\nもし もし しょうぶに かったら!\lワシは なんて いったら いいんだろう……?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{JPN}{STR_VAR_1}\pよ よし それ\nいって みるよ!\lは はずかしいな いえるかな……\pありがとう {PLAYER}{KUN}\nさようならだ!\l{PLAYER}{KUN}に いわれた こと\lぜんぶ まもって ワシ がんばるよ!$"

gText_ApprenticePickWinSpeech15::
	.string "{JPN}ん?\n{PLAYER}{KUN}の ように みえるが……\lほんものかな?\l{PLAYER}{KUN} ぬいぐるみ では?\pいや! いやいやいやいや!\nすまない ほんものなら いいんだ\lまあ そう おこらないで くれ!\lそれでもって じょげんを おねがいする\lことばに かんする ことだ!\pもし わたしが しょうぶに かったら\nぜんたい なんと いえば いいかね?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{JPN}{STR_VAR_1}\p…… …… ……\nしょうぶに かったら\p{STR_VAR_1}\p…… ほんき なのかね?\pいや ほんき なら いいんだ!\nどうも ありがとう\lこんな わたしでも いつか\lつかえる ときが くれば いいな\pでは そろそろ\nほしい じょげんも なくなってきた\l{PLAYER}{KUN}とは おわかれして\lひとりで がんばって みようかと おもう\pでは ありがとう!\nうたがって すまなかった!$"
