gText_Birch_Welcome::
	.string "にほんご がつかえるか テストするよ\p"
	.string   "あいうえお かきくけこ\n"
	.string   "さしすせそ たちつてと\p"
	.string   "なにぬねの はひふへほ\n"
	.string   "まみむめも やゆよ\p"
	.string   "らりるれろ わをん\n"
	.string   "ぁぃぅぇぉ ゃゅょっ\p"
	.string   "がぎぐげご ざじずぜぞ\n"
	.string   "だぢづでど ばびぶべぼ\p"
        .string   "ぱぴぷぺぽ\n"
	.string   "アイウエオ カキクケコ\p"
	.string   "サシスセソ タチツテト\n"
	.string   "ナニヌネノ ハヒフヘホ\p"
	.string   "マミムメモ ヤユヨ\n"
	.string   "ラリルレロ ワヲン\p"
	.string   "ァィゥェォ ャュョッ\n"
	.string   "ガギグゲゴ ザジズゼゾ\p"
	.string   "ダヂヅデド バビブベボ\n"
	.string   "パピプペポ \p"
	.string   "ー!?.,-/ 0123456789$"

gText_Birch_Pokemon::
	.string "ハスボー だすよ\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "ハスボー Lv.50 HP 123/456\p"
	.string "ABC xyz 0123456789$"

gText_Birch_AndYouAre::
	.string "せんたくしの テストだよ?$"

gText_Birch_BoyOrGirl::
	.string "きみはおとこ?\n"
	.string "おんな?　ってやつだね$"

gText_Birch_WhatsYourName::
	.string "おっけー。\n"
	.string "なまえ にゅうりょく テストするね?$"

gText_Birch_SoItsPlayer::
	.string "きみは {PLAYER}くんだね?$"

gText_Birch_YourePlayer::
	.string "おっけー!\p"
	.string "きみは {PLAYER}くん という\n"
	.string "なまえになったよ\p"
	.string "これでよし$"

gText_Birch_AreYouReady::
	.string "じゃあ ゲームスタートだ\p"
	.string "$"
