Text_PictureBookShelf:
	.string "There's a set of POKEMON picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
	.string "POKEMON magazines!\n"
	.string "POKEMON PAL...\p"
	.string "POKEMON HANDBOOK...\n"
	.string "ADORABLE POKEMON...$"

Text_Vase:
	.string "This vase looks expensive...\n"
	.string "Peered inside...\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "POKEMON merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
