EventTicket_Text_ShowOldSeaMap:
	.string "{JPN}カイナいき れんらくせん……\p"
	.string "{JPN}え? この ちずの とおりに\n"
	.string "{JPN}いってくれって?\p"
	.string "{JPN}わたしでは よく わからないので\n"
	.string "{JPN}おまちください$"

EventTicket_Text_ThatPass:
	.string "{JPN}カイナいき れんらくせん……\p"
	.string "{JPN}あら?\n"
	.string "{JPN}その チケットは……!$"

EventTicket_Text_ShowEonTicket:
	.string "{JPN}ヘンテコな チケットを\n"
	.string "{JPN}もってきたのは おまえさんか?\p"
	.string "{JPN}おまえが いこうと しているのは\n"
	.string "{JPN}みなみの はての ちっぽけな しま……\p"
	.string "{JPN}そこでは なにが おこるのか\n"
	.string "{JPN}だれも わからねえ……\l"
	.string "{JPN}ううむ ふなのりの ちが さわぐぜ!\p"
	.string "{JPN}さあ のりな!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "{JPN}なにもねえ ちんけな しま だな……\n"
	.string "{JPN}ミナモへ かえるか?$"

EventTicket_Text_SailHome:
	.string "{JPN}よし! かえると するか!$"

EventTicket_Text_AsYouLike:
	.string "{JPN}そうかい\n"
	.string "{JPN}まあ すきにするが いいさ$"

SouthernIsland_Interior_Text_Sign:
	.string "{JPN}すべての ゆめは もうひとつの げんじつ\n"
	.string "{JPN}それを わすれるべからず……$"

SouthernIsland_Exterior_Text_Sign:
	.string "{JPN}きおく かすみし ものは\n"
	.string "{JPN}こころに きざみつける ことを のぞむ……$"
