MatchCall_WildBattleText1::
	.string "{JPN}あ! {PLAYER}{KUN} こんにちは!\n{STR_VAR_1} です\pこのまえ {STR_VAR_2}を みつけたんだけど\nつかまえられなかったよ\pおしかったなー\nじゃあ またね!$"

MatchCall_WildBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n{STR_VAR_1} です\pこのまえ {STR_VAR_2} を\nつかまえようと したんだけど\pにげられちゃったの\nざんねん だったなあ\pじゃあ またね!$"

MatchCall_WildBattleText3::
	.string "{JPN}おーっす {PLAYER}!\n{STR_VAR_1} だ!\pこのまえ {STR_VAR_2} を\nつかまえようと したんだけど\lあとすこしの ところで にげられたんだ!\pくやしかった なあ・・・\nじゃあ またなー$"

MatchCall_WildBattleText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\p{STR_VAR_2}って ポケモン しってるかい?\nこのまえ あとすこしで\pつかまえられそう だったんだけど\nにげられて しまったよ\pこんど みつけたら ぜったい\nつかまえて みせるよ\pじゃあ またな$"

MatchCall_WildBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だけど\lポケモン つかまえてる?\pおれも このまえ もうすこしで\nつかまえられそう だったけど\pにげられちゃったよ\nじゃあ またな$"

MatchCall_WildBattleText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だけど\lポケモン つかまえてる?\pおれも このまえ もうすこしで\nつかまえられそう だったけど\pにげられちゃったよ\nじゃあ またな$"

MatchCall_WildBattleText7::
	.string "{JPN}・・・あ {PLAYER}{KUN}?\n{STR_VAR_1} だけど・・・\pあ ちょっと まって!\nいま {STR_VAR_2}を つかまえ・・・\pああああ にげられたー!\nもうすこし だったのに!$"

MatchCall_WildBattleText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\pあれから ポケモン つかまえた?\nわたし このまえ もうすこしで\pつかまえられそう だったのに\nにげられちゃった\pもっと がんばらなきゃ!\nじゃあ またね$"

MatchCall_WildBattleText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n{STR_VAR_1} です!\pどう? ポケモン あつまってる?\nわたしは にげられて ばっかりで\pぜんぜん うまく いかないの\nじゃあ またね!$"

MatchCall_WildBattleText10::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pもうすこしで {STR_VAR_2} を\nつかまえられそう だったのに\lにげられちゃった\pもっと がんばらなきゃ!\nじゃあ またね$"

MatchCall_WildBattleText11::
	.string "{JPN}ああ {PLAYER}{KUN}\n{STR_VAR_1}だけど\lちょうしは どうだい?\pおれは このまえ {STR_VAR_2} を\nつかまえようと したんだけど\pにげられちゃったよ\nがっくり$"

MatchCall_WildBattleText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが\lポケモン つかまえとるかな?\pわしも つかまえようと おもったが\nなかなか うまくいかん\pポケモンの みちは\nおくが ふかいのう$"

MatchCall_WildBattleText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが\lポケモン つかまえとるかな?\pわしも つかまえようと おもったが\nなかなか うまくいかん\pポケモンの みちは\nおくが ふかいのう$"

MatchCall_WildBattleText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pさっき {STR_VAR_2}ちゃんを\nつかまえようと したんだけど\pにげられちゃったのよ ざんねん!\nじゃあ またね$"

MatchCall_WildBattleText15::
	.string "{JPN}おーっす {PLAYER}!\n{STR_VAR_1} だ!\pポケモンを つかまえようと\nおもってるんだが\lみつからなくてさー\lおじさん こまってる とこなのよ\pまいったなー\nじゃあ またなー$"

MatchCall_NegativeBattleText1::
	.string "{JPN}{PLAYER}{KUN} こんにちは!\n{STR_VAR_1} です!\pほかのひとと しょうぶ したんだけど\nまけちゃったよ がっくし\pじゃあ またね$"

MatchCall_NegativeBattleText2::
	.string "{JPN}{PLAYER}{KUN} こんにちは!\n{STR_VAR_1}よ!\pわたし ね\nあれから また しょうぶ してみたの\pでも あとちょっとの ところで\nまけちゃった あーあ$"

MatchCall_NegativeBattleText3::
	.string "{JPN}おーっす {PLAYER}!\n{STR_VAR_1} だ!\pしょうぶ に まけたよー\nもっと そだてないと だめだなー$"

MatchCall_NegativeBattleText4::
	.string "{JPN}やあ {PLAYER}\n{STR_VAR_1} だ\pきのう また しょうぶ してみたんだ\nでも かてなかったよ\pもっと そだてが ひつようだな\nじゃあ またな$"

MatchCall_NegativeBattleText5::
	.string "{JPN}やあ {PLAYER}\n{STR_VAR_1} だよ\pちょうしは どうだい?\nおれは しょうぶ しても\lあまり かてないんだよ\pちょうし わるいなあ\nじゃあ またな$"

MatchCall_NegativeBattleText6::
	.string "{JPN}やあ {PLAYER}\n{STR_VAR_1} だよ\pちょうしは どうだい?\nおれは しょうぶ しても\lあまり かてないんだよ\pちょうし わるいなあ\nじゃあ またな$"

MatchCall_NegativeBattleText7::
	.string "{JPN}{STR_VAR_1} だけどー\nさいきん どう?\pきのう しょうぶに まけてさ\nそのことで あたまが いっぱいなんだ\pたいさく かんがえないと・・・\nじゃあ また$"

MatchCall_NegativeBattleText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\pポケモンの ちょうしは どう?\nわたしは このまえの しょうぶで\lまけちゃった\pもっと がんばらなきゃ!\nじゃあ またね$"

MatchCall_NegativeBattleText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n{STR_VAR_1} でーす\pねー きいて きいて!\nこのまえ ポケモン しょうぶ したんだけど\pあとちょっとの ところで\nまけちゃったのよー! くやしい!$"

MatchCall_NegativeBattleText10::
	.string "{JPN}あら {PLAYER}{KUN}\n{STR_VAR_1} です\pさっき しょうぶ したんだけど\nまけちゃった\pもっと ポケモン そだてないと だめね\nじゃあ またね$"

MatchCall_NegativeBattleText11::
	.string "{JPN}やあ {PLAYER}{KUN} げんきかい?\n{STR_VAR_1} だよ\lポケモンの ちょうしは どう?\pこっちは また しょうぶに\nまけちゃったよ\pじゃあ また$"

MatchCall_NegativeBattleText12::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが\lしょうぶ しておるのかな?\pわしのほうは このまえ まけてしまって\nまた ポケモンを\lそだてておる ところじゃよ\pでは またな$"

MatchCall_NegativeBattleText13::
	.string "{JPN}おお {PLAYER}{KUN}\n{STR_VAR_1} じゃ\pげんき かのう?\nさっきまで ポケモン しょうぶを\lしておったよ\p{PLAYER}{KUN}も がんばるんじゃぞ\nでは またの$"

MatchCall_NegativeBattleText14::
	.string "{JPN}あら {PLAYER}{KUN}\n{STR_VAR_1} よ\pちょうしは どうなの?\nたまには いえに かえらないと だめよ\lじゃあ またね$"

MatchCall_PositiveBattleText1::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n{STR_VAR_1} です!\pさっき しょうぶ したんだけど\nかったよ! かったよ!\pぼくの {STR_VAR_2} が\nすごく がんばったんだ! うれしいなー$"

MatchCall_PositiveBattleText2::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n{STR_VAR_1} です!\pきのう しょうぶ したんだけど\nかったのよ! うれしいー!$"

MatchCall_PositiveBattleText3::
	.string "{JPN}おーっす {PLAYER}!\n{STR_VAR_1} だぞ\pちょうしは どうだ?\nおれも このまえ しょうぶ したんだけど\lおれの {STR_VAR_2}が だいかつやく さ!\pつぎ {PLAYER}と しょうぶ するときは\nぜったい まけない からなー!$"

MatchCall_PositiveBattleText4::
	.string "{JPN}やあ {PLAYER}\n{STR_VAR_1} だ\pさっき しょうぶ したんだけど\nなんとか かつ ことが できたよ\pぼくの {STR_VAR_2}が\nすごく がんばったんだ$"

MatchCall_PositiveBattleText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\pちょうしは どうだい?\nしょうぶ してる?\pおれ このまえ かったよ!\n{STR_VAR_2}が だいかつやく さ!\pつぎこそ きみに かつからね!\nじゃあ またね$"

MatchCall_PositiveBattleText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\pげんき かい?\nおれは さいきん ちょうしが よくて\lさっきも しょうぶに かったところだ\pつぎに きみと しょうぶ するときは\nぜったいに まけないからな$"

MatchCall_PositiveBattleText7::
	.string "{JPN}{PLAYER}{KUN}?\n{STR_VAR_1} だけど\pぼくの {STR_VAR_2} つよいわけよ!\nさっきも しょうぶで かったわけよ!\pつぎに きみと しょうぶ するのが\nたのしみだなあ$"

MatchCall_PositiveBattleText8::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pげんき かしら?\nわたしね さっき しょうぶ して かったの\p{STR_VAR_2} が とっても がんばったのよ\nじゃあ またね$"

MatchCall_PositiveBattleText9::
	.string "{JPN}こんにちは {PLAYER}{KUN}!\n{STR_VAR_1} でーす!\pポケモンの ちょうしは どう?\nわたしのほうは さっき しょうぶして\lかった ところよ!\pわたしの {STR_VAR_2} が\nすごい かつやく だったのよ\pみせたかったなー\nじゃあ またね!$"

MatchCall_PositiveBattleText10::
	.string "{JPN}あら こんにちは {PLAYER}{KUN}\n{STR_VAR_1} よ\pちょうしは どうかしら?\nわたしの ポケモン ちょうし いいみたい\pさっきも しょうぶで かてたのよ\nじゃあ またね$"

MatchCall_PositiveBattleText11::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だよ\pポケモン しょうぶ してるかい?\nおじさん きょうも しょうぶに かってねー\pちょうし いいんだよ がははは\nじゃあ またね$"

MatchCall_PositiveBattleText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃよ\pげんきに してるかのう?\nわしは げんき じゃぞ\pさっきも しょうぶに かった ところじゃ\nわかいもんには まだまだ まけんぞ$"

MatchCall_PositiveBattleText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃよ\pげんきに してるかのう?\nわしは げんき じゃぞ\pさっきも しょうぶに かった ところじゃ\nわかいもんには まだまだ まけんぞ\pじゃあ またのう$"

MatchCall_PositiveBattleText14::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pこのまえ しょうぶ したんだけど\nわたしの {STR_VAR_2}が だいかつやく!\p{PLAYER}{KUN}にも みせたかったな\nじゃあ また$"

MatchCall_SameRouteBattleRequestText1::
	.string "{JPN}{PLAYER}さん こんにちは!\n{STR_VAR_1} だよ\pえ! いま {STR_VAR_2} に いるの?\nじゃあ いまから しょうぶ しようよ!\lまってるよ! じゃあね!$"

MatchCall_SameRouteBattleRequestText2::
	.string "{JPN}{PLAYER}さん こんにちは!\n{STR_VAR_1} でーす\pえ! いま {STR_VAR_2} に いるの?\nじゃあ いまから しょうぶ しない?\lまってるわよ! じゃあね!$"

MatchCall_SameRouteBattleRequestText3::
	.string "{JPN}おーっす {PLAYER}!\n{STR_VAR_1} だ!\pお いま {STR_VAR_2}にいるのか?\nじゃあ これから しょうぶ しないか?\pこんどこそ まけない からな!\nまってるぞー じゃあな$"

MatchCall_SameRouteBattleRequestText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\pいま どこに いるんだい?\nえ {STR_VAR_2}?\pじゃあ これから しょうぶ しないか?\nまってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だよ\pちょうしは どうだい?\nえ? いま {STR_VAR_2}に いるの?\pそれなら これから おれと\nしょうぶ してみないかい?\pまってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\pポケモンの ちょうしは どうだい?\nへえ いま {STR_VAR_2}に いるのか\pじゃあ これから おれと\nしょうぶ しよう\pまってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText7::
	.string "{JPN}・・・あ {PLAYER}{KUN}?\n{STR_VAR_1} だけど・・・\pへー いま {STR_VAR_2}に いるの?\nじゃあ しょうぶ しよう これから\pおれの ポケモンを みせてあげるよ\nじゃあ まってるよ$"

MatchCall_SameRouteBattleRequestText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\pげんき ですか?\nあら いま {STR_VAR_2}に いるのね\pじゃあ これから\nわたしと しょうぶ しない?\pまってるわよ じゃあね!$"

MatchCall_SameRouteBattleRequestText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n{STR_VAR_1} です!\pげんきに してる?\nあら いま {STR_VAR_2}に いるの?\pそっかー じゃあ これから\nわたしと しょうぶ してみない?\pじゃあね まってるわよ$"

MatchCall_SameRouteBattleRequestText10::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\pげんき ですか?\nあら いま {STR_VAR_2}に いるのね\pじゃあ これから\nわたしと しょうぶ しない?\pまってるわよ じゃあね!$"

MatchCall_SameRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}\n{STR_VAR_1}だけど\pほほう\nいま {STR_VAR_2}に いるんだって?\pじゃあ これから おじさんと\nポケモン しょうぶ しないかい?\pまってるよ じゃあね$"

MatchCall_SameRouteBattleRequestText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが\lいま どこに いるのかな?\p{STR_VAR_2} か! すぐ ちかく じゃな\nこれから わしと しょうぶ せんか?\pまっておるぞ じゃあの$"

MatchCall_SameRouteBattleRequestText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが げんきかのう?\pほうほう いまは {STR_VAR_2}に おるのか\nちかいから こっちへ よって\pいちど しょうぶ して いかんかの?\nまっておるぞ じゃあの$"

MatchCall_SameRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pあら いま {STR_VAR_2}に いるの?\nすぐちかくに いるのね\pじゃあ これから おばさんと\nポケモンしょうぶ してみない?\pまってるわよ じゃあね$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "{JPN}あ! {PLAYER}{KUN}!\n{STR_VAR_1} です\pこれから ぼくと しょうぶ しない?\n{STR_VAR_2} で まってるよ!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "{JPN}あ! {PLAYER}{KUN}!\n{STR_VAR_1} です\pこれから わたしと しょうぶ してみない?\n{STR_VAR_2} で まってるよ!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "{JPN}おーっす {PLAYER}!\n{STR_VAR_1} だ!\pあれから おれの ポケモンも\nたくましく なったぞ!\p{PLAYER}の ポケモンで\nうでだめし したいから\pしょうぶ してみないか?\n{STR_VAR_2} で まってるぞ$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\pちょうしは どうだい?\nおれの ポケモンも\lずいぶん つよく なったよ\pそうだ また おれと\nしょうぶ しないかい?\pじゃあ {STR_VAR_2}で あおう$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だけど\pおれの ポケモン\nけっこう いいかんじに そだってきたよ\pきみと もういちど\nしょうぶ してみたいなあ\p{STR_VAR_2} で まってるよ\nじゃあね$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だけど\lげんきで やってるかい?\pまた きみと ポケモンしょうぶを\nしてみたいんだけど どうだい?\pしょうぶ したくなったら\n{STR_VAR_2}に きてくれよ\pじゃあ また$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "{JPN}あ {PLAYER}{KUN}?\n{STR_VAR_1} だけど・・・\pどう? ポケモン そだってる?\nぼくの ポケモンも つよくなったから\lきみに みせたいなあ\p{STR_VAR_2}で まってるから\nしょうぶ しに きてくれよ\pじゃあ また$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\pちょうしは どうですか?\nわたしの ポケモンは とても げんきですよ\pこんど こちらに いらしたら\nまた わたしと\lしょうぶ してくださいね\p{STR_VAR_2}で まってます\nでは また$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "{JPN}あ {PLAYER}{KUN} こんにちはー!\n{STR_VAR_1} です!\pポケモンの ちょうしは どうかな?\nわたしの ポケモンも\pどんどん つよく なってるのよ\n{PLAYER}{KUN}にも みせてあげたいなあ\p{STR_VAR_2}に いるから\nちかくに きたら しょうぶでも しようよ\pじゃあ またね$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pどう? げんきで やってるかしら?\nあれから わたしの ポケモンも\lずいぶん つよく なったのよ\pまた {PLAYER}{KUN}と\nしょうぶ したいなあ\p{STR_VAR_2}に いるから\nちかくに きたら あいに きてね$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{JPN}ああ {PLAYER}{KUN}\n{STR_VAR_1}だけど\lいま どこに いるのかな?\pわしの ポケモンは とても げんき だぞ\n{PLAYER}{KUN}の ポケモンと あうのを\lたのしみに しているみたいだ\p{STR_VAR_2}に いるから\nぜひ あいに きてくれよ$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃ\pわしの ポケモンも あれから\nずいぶんと たくましく なったぞ\p{PLAYER}{KUN}の ポケモンと\nもういちど てあわせ したいのう\p{STR_VAR_2}に おるから\nいつでも きてくれたまえ$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃ\pポケモンは げんきに しとるかね?\nわしの ポケモンも\lまけない ぐらい げんきに しておるよ\pまた しょうぶ してみたいので\n{STR_VAR_2}の ちかくに きたら\pあいに きてくれんかのう\nでは またの$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pげんきに してる?\nあ そうそう\pわたしの ポケモン\nあれから けっこう つよく なったのよ\p{PLAYER}{KUN}と もういちど\nしょうぶ してみたいわねえ\p{STR_VAR_2}で まってるから\nいつでも あいに きてね$"

MatchCall_PersonalizedText1::
	.string "{JPN}やまを あいする {STR_VAR_1}だが\pどうだね あれから\nすこしは やまが すきに なったか?\lあまり やまで きみを みかけないが……\pよし つぎは {STR_VAR_2}で\nあおう じゃないか またな!$"

MatchCall_PersonalizedText2::
	.string "{JPN}{STR_VAR_1}です\nこんにちは\pいまね トレーナーに なりたてのコに\nあなたの ことを きかせて いたのよ!\lポケモンを たいせつに そだてている\lつよい トレーナーが いるのよって……\pみんなの あこがれに なるような\nすばらしい トレーナーに なってね!\lじゃあ また あいましょう!$"

MatchCall_PersonalizedText3::
	.string "{JPN}こんにちは! {STR_VAR_1}よ\nこの あたりは ほんとうに\lいいかおりが して きもちがいいわ\pだれかが きのみを うめて\nはなを さかせて くれたのかしら? うふふ\pそれじゃ またね!$"

MatchCall_PersonalizedText4::
	.string "{JPN}はいはい! いせきを さがして 30ねん\nわたし {STR_VAR_1}で ございます\pきみは せっきょくてきに あちこちを\nまわって いるよう だけど\lなにか いせきを みつけたかい?\lみつけたら おしえて くれよ!\pでは わたしは\nいせきを さがすので これで$"

MatchCall_PersonalizedText5::
	.string "{JPN}{STR_VAR_1} でーす\nきょうはね すなはま から\lうみを ながめて いるんだ!\pはー…… キラキラ なみが ひかって\nここから みる うみが いちばん きれい!\lあー おなかすいた じゃあまたね!$"

MatchCall_PersonalizedText6::
	.string "{JPN}もぐもぐ……\nあ {STR_VAR_1}です\lすなはまで たべる おにぎりは うまいなー\pうーん ぼくも ポケモンも\nげんきに なったぞ!\lじゃ およいで くるね!$"

MatchCall_PersonalizedText7::
	.string "{JPN}やあ {STR_VAR_1} だけど……\pエリートトレーナー の せいかつに\nちょっと つかれちゃってね……\pみんな ぼくのことを\nかんぺきな トレーナーだと おもうから\lぼくも それらしく しないと いけない\pでも それも エリートトレーナーの\nしゅくめいだと おもって\lがんばる ことに するよ!\pこんな ことが いえるのは キミだけだ\nでも こんど あった ときは\lよわねは はかないから あんしんして!\lじゃ!$"

MatchCall_PersonalizedText8::
	.string "{JPN}ヤッホー {STR_VAR_1}よ\nこんにちは!\pいま あなたを めざして\nポケモンを そだてて いるの!\lこんど たたかう ときは\lぜったい まけない つもり! ふふっ\pトレーナー なかまが いるって いいよね\nまた あいましょう!$"

MatchCall_PersonalizedText9::
	.string "{JPN}{STR_VAR_1} ですけど……\nいま あなたの うしろ……\lなにかが いない……?\pここ おくりびやまで ねむっている\nポケモンたちの ちからが\lわたしに おしえて くれるの……\lふりかえらないで そのまま\lまっすぐ あるいたほうが いいわよ……\pフフ……\nそれじゃあ さよなら……$"

MatchCall_PersonalizedText10::
	.string "{JPN}わたくし {STR_VAR_1}ですわ\nごきげんよう\pはなれていても こうして\nおはなし できるなんて べんりね\pいままでは あいたい ひとが いたら\nパパに おくってもらって いたもの……\pそれではまた……\nおはなし できて うれしかった ですわ$"

MatchCall_PersonalizedText11::
	.string "{JPN}{STR_VAR_1}よ\nちょっと はなし ききなさいよ!\pわたし サファリゾーンが すきなんだけど\nあそこに いくと かならず まようのよ!\lくさ ばっかり はえてて\lちょっと ひろすぎるのよねー! ぷんぷん!\pあー おこったら きが すんだわ\nちょっと サファリゾーンでも いこっと!\lまたね!$"

MatchCall_PersonalizedText12::
	.string "{JPN}やあ\nおかねもちの {STR_VAR_1} だけど\pボク あれから ますます\nおかねもちに なっちゃったし\lポケモンも ますます つよく なったよ\pこの せかいって\nボクの ために あるんじゃない かな?\pああ へんじは しなくて いいよ\nわかっている ことだからね!\lおっと そろそろ ディナーのじかんだ\lしつれい するよ!$"

MatchCall_PersonalizedText13::
	.string "{JPN}うふふふふふふ……\nボ ボク {STR_VAR_1}です\pいま めのまえで\n{STR_VAR_2} どうしが たたかってるんだ\lかった ほうを つかまえよう かな?\lうふふふふ……\pじ じゃ いそがしいから\nボクは これで$"

MatchCall_PersonalizedText14::
	.string "{JPN}あ {STR_VAR_1}です!\nそろそろ すてられぶね にも\lあきて きちゃった のよね\pでも せっかく だから\nいちどは キミに かって みたいし\lとうぶんは ここで さんぽ してるわ\lきが むいたら あいに きてよね!\pよし きょうは ついに\nとなりの へやの おじさんに\lしょうぶを いどんで みようかな?\pではね!$"

MatchCall_PersonalizedText15::
	.string "{JPN}うみの おとこ\n{STR_VAR_1}だぜ!\pやっぱさ!\nでっかい うみに いる トレーナーは\lつよいやつ ばっかりだぜ!\pおまえも オレらを みならって\nうみで しゅぎょうすりゃ いいのによ……\l……と おおなみが きそうだ!\pしゅぎょうの チャンスだぜ!\nわるいけど またなっ!$"

MatchCall_PersonalizedText16::
	.string "{JPN}{STR_VAR_1}だ!\nポケモンに カラテを おしえてたら\lほんとに おれより つよくなっちまって\lおれ まけまくりだ!\pだが おれは ポケモンに まけても\nトレーナー には まけん!\lいつか また おれと しょうぶだ!\lうがー!$"

MatchCall_PersonalizedText17::
	.string "{JPN}{STR_VAR_1}だけど\nそっちの たびは どんなカンジ?\p……へえー なるほど なるほど\nたのしそうじゃん!\lきみの エピソードで\l1きょく つくれそうだな!\p……おッ うかんできた\nいい フレーズ うかんできたよ!\pじゃ オレ いまから\nきょくづくりに はいるから またな!$"

MatchCall_PersonalizedText18::
	.string "{JPN}{STR_VAR_1}だけど……\nボクの しんきょく きいてくれ\pルル {STR_VAR_2} {STR_VAR_2}\nどうして おまえは {STR_VAR_2}なんだ\lどうして ボクは {STR_VAR_2}では ないんだ\lあー ルルル {STR_VAR_2}と{STR_VAR_1}\l{STR_VAR_1}と{STR_VAR_2} ルル……\pフェードアウト……$"

MatchCall_PersonalizedText19::
	.string "{JPN}キャンプの たつじん\n{STR_VAR_1} だ!\pま こないだ ぼくが まけちゃったのは\nぼくの せんもんが キャンプだからね\lしかたが なかったのさ!\pかっても まけても\nキャンプで ポケモンしょうぶ するの\lぼく だいすき なんだ!\pまたこんど あいてを たのむよ\nあ キャンプも いっしょに しようぜ!$"

MatchCall_PersonalizedText20::
	.string "{JPN}おれ おれ {STR_VAR_1}!\pいやあ おれも ほかの やまにも\nのぼって みても いいんだけどさー\lえんとつやま みたいに\lきれいな おねいさん たちが\lいるか どうか わからんもんなー\pきれいな おねいさんが いっぱいの\nやまが あったら おしえて くれよ!\lえへへへ またなあ!$"

MatchCall_PersonalizedText21::
	.string "{JPN}…… …… ……\n…… …… ……\l{STR_VAR_1} です……\p…… …… ……\n…… …… ……\lきょうは それだけ……$"

MatchCall_PersonalizedText22::
	.string "{JPN}{STR_VAR_1}だよ… きょうは\nきみと はなす きが してたんだ\pきみに かちたい きもちは\nひましに つよくなる ばかりだよ\lきみ にも そんな あいてが いるだろ?\lそれが ぼくなら いいのにな\pきいて くれて ありがと またな!$"

MatchCall_PersonalizedText23::
	.string "{JPN}{STR_VAR_1}です\pつよい トレーナーが ちかくに いると\nなんとなく その そんざいを\lかんじる ことが あるの\pもしかしたら {PLAYER}{KUN}が\nわたしの そばを とおったの かもね?\pあいに きて くれるのを\nまっているわ! バーイ!$"

MatchCall_PersonalizedText24::
	.string "{JPN}{STR_VAR_1}です\n{PLAYER}{KUN}は げんきそう ですな\pせかい かっこくを まわった わたしですが\nこの ちほうを たいへん きにいりました\lとうぶん いる つもりですよ\pそういう わけ ですから\nまた あえるかも しれませんね\pあなたの みごとな わざ\nわすれては おりませんよ\lまた おあいてを おねがいしますね$"

MatchCall_PersonalizedText25::
	.string "{JPN}グスン {STR_VAR_1}……です\n……グスン\pきょう ツツジさんに\nおこられ ちゃった\pでも ツツジさんは\nなんで ボクが わるいのか\lちゃんと おしえて くれるから\lうらんだり しないよ!\pあしたも また いくんだ\nトレーナーズ スクール! えへ……\lじゃ またね!$"

MatchCall_PersonalizedText26::
	.string "{JPN}{STR_VAR_1} です!\pきのう ツツジさまに\nしょうぶ してもらったの!\pけっかは さんざん だったけど……\nツツジさまが あたしの あいてを\lしてくれた って いうことが\lすごく うれしいの!\lますます あこがれちゃうわ!\pいまから また もうべんきょうよ!\nだから さよなら!$"

MatchCall_PersonalizedText27::
	.string "{JPN}ミホでーす!\nきょうも こうはいの リコと いっしょだよ\pもうね! リコも ポケモンも\nかわいくて しかたないの\lおとうとや いもうと みたいに\lずーっと めんどう みて あげたいな!\pあ リコ!\nパン かってきて くれた?\pえ? な なによ\nつかいっぱしり なんて させてないわよ!\lポケモン しょうぶで まけたから\lこれは ばつゲームなの!\pかわいい リコを\nこきつかうわけ ないでしょ!\lじゃ これから おやつだから バイバイ!$"

MatchCall_PersonalizedText28::
	.string "{JPN}ポケモン だいすき!\nだいすきクラブの {STR_VAR_1}です!\pきっ きいて くださいよ!\nわたしの ポケモンちゃんが なんと……!\lぐふ ぐふふふ\lこれいじょうは ひみつ!\lもー かわいすぎて くちに できない!\pああっ {STR_VAR_2}ちゃんが\nポロックを おねだりしてるー!\lかわいいぞーーーっ!\pわるいけど きみと\nはなしている ばあいじゃ ないぞ!\lまた こんど つづきを きいてくれ$"

MatchCall_PersonalizedText29::
	.string "{JPN}おほほ!\pポケモンを じまん したくて しかたない\n{STR_VAR_1} ですわ!\pあなた おききに なって\nあたくしの {STR_VAR_2}ちゃん……\lほかの ひとに だっこされると\lピョンと にげだして\lあたくしの むねに とびこんでくるの!\pもう…… もう!\nこんな しあわせって ほかに あるかしら!\pああ しあわせだわ\nあなたにも しあわせを わけて あげられて\lよかったわ!\lでは しつれい するわね$"

MatchCall_PersonalizedText30::
	.string "{JPN}わたしは…… {STR_VAR_1}だ\pひとは わたしを たつじんと よぶ\nだが わたしは わかっている\lわたしだけの ちから では\lたつじん には なれない ことを\pポケモンの ちからが あってこそ\nトレーナーは たつじんに なれる!\pうむ……! わたしは いま\nすごく いいことを いった きがする!\lきもちがよい ままに わかれよう!$"

MatchCall_PersonalizedText31::
	.string "{JPN}{STR_VAR_1} じゃよ\nおんせんに つかって ごきげんだからねぇ\lこうして おはなし できて うれしいよ!\pあれから なんにんか\nわかい トレーナーさんと たたかったが\lおまえさんが いちばん つよかったよ!\pきっと としを とったら\nたつじんに なるじゃろうな!\lおっほっほっほ……$"

MatchCall_PersonalizedText32::
	.string "{JPN}わーい! {STR_VAR_1}でーす!\nげんきー?\pボクが ポケモン かてる ときって\nきのせいかも しれないけど\lたんパンの ちょうしが いいんだ!\pえ どういうこと かって?\nうーん うまく せつめい できないけど\lなんていう のかな……\lはき ごこちが サラっと してるんだ!\pで {PLAYER}{KUN}と しょうぶの ときは\nだいたい ベタっと してるんだよね……\p…… …… ……\nボクの はなし しんじた?\lえへへへ じゃあね バイバーイ!$"

MatchCall_PersonalizedText33::
	.string "{JPN}うおーい!\n{STR_VAR_1}だぞーっ!\lきょうも ごうかいに\lつりを たのしんで いるぞーっ!\pうみ か かわ いがいに\nつりが できる ばしょって ないかーっ?\lどこでも つりが したくって\lうずうずするんだーっ!\pおっと つりいとが からまった!\nじゃ つりが できるところ\lさがしといてくれーっ! またなーっ!$"

MatchCall_PersonalizedText34::
	.string "{JPN}やあ! {STR_VAR_1} だけど\nどう のんびり やっている かい?\pボクはさ むかしから\nあせったり いそいだり するのが\lにがて なんだよね\lそれでも なぜか いまは\lトライアスリートを やっている……\pじんせい なにが おこるか\nわからないって ヤツだな! はは\pキミも いまは トレーナーだけど\nしょうらいは せんせい とか えかき とか\lよそうも つかない ことを\lやって いるの かもな!\pまー のんびり やれよ!\nじゃあなー$"

MatchCall_PersonalizedText35::
	.string "{JPN}{STR_VAR_1}よ!\nいま じてんしゃに のっているわ!\pわたし すいえいも はしるのも すきだけど\nじてんしゃが いちばん すきなの!\lだって からだに かぜを\lたくさん かんじる ことが できるでしょ?\lそらをとぶ みたいで きもちいいのよ!\pよーし きょうこそ サイクリングロードで\nしんきろくを だすわっ!\lあなたも ちょうせん しに きなさいよ!\lじゃあねーっ$"

MatchCall_PersonalizedText36::
	.string "{JPN}よお! トライアスロンの まっさいちゅうの\n{STR_VAR_1}だけど\lさくっと せけんばなし でも どうだい!\pポケモンと いっしょに あせを ながすと\nすごく きもちいいぜ!\lことばに ださなくったって\lふたりの こころが つうじあうんだ\lあれは ちょっと かんどう するなあ!\pはあはあ… はしりながら はなしてたら\nたいりょくが なくなった!\lはあはあ わるいけど こんどな!$"

MatchCall_PersonalizedText37::
	.string "{JPN}こんにちは {STR_VAR_1}よ\nじきゅうりょく を つけるには\lやっぱり たかい ところが いいわね!\pやまの てっぺん とかで\nはしり まわると\lすぐに いきが きれるのよ!\pああ わたしも いきが きれそう\nじゃあ またね!$"

MatchCall_PersonalizedText38::
	.string "{JPN}ああ {STR_VAR_1} です\nあれから だいぶ およいだけど\lサイユウシティには まだ つかないのかなあ\pもしかして おなじ ところを\nぐるぐる まわってるだけ だったりして\pいや まさか そんなこと ないよな\nわはははは\lじゃあ また!$"

MatchCall_PersonalizedText39::
	.string "{JPN}ああ {STR_VAR_1} ですけ……\pボチャン\pブクブクブク………\pザバー\pブンブン\p……ごッ ごめん!\nいま オイルを ぬった てで\lポケナビを もってたら\lうみに おとして しまったんだ!\pうみに おとしても こわれないなんて\nデボンの ポケナビって すげーな!\lじゃ にっこうよくの つづきを するんで\lまたこんど はなそうぜ!$"

MatchCall_PersonalizedText40::
	.string "{JPN}トライアスロンの なかでも\nすいえいが だいすきな {STR_VAR_1} です\pでも あんまり ながいこと\nうみに いると\lからだが ふやけちゃわないかなあ\pやっぱり トライアスロンは\nかこくな レースよね!\lじゃ またね!$"

MatchCall_PersonalizedText41::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1}だ\pきみの ポケモンの\nちょうしは どうだい?\pぼくの ドラゴンポケモンたちも\nちょうし よさそうだよ\lじゃあ また$"

MatchCall_PersonalizedText42::
	.string "{JPN}{STR_VAR_1}だ\nおれの {STR_VAR_2}\lあれから いちだんと つよくなったぜ!\pつぎ キミと しょうぶ するときは\nまけない からな!\pじゃあ またな!$"

MatchCall_PersonalizedText43::
	.string "{JPN}{STR_VAR_1}で ござる\nかくれかたの けんきゅうを\lつづけて いるんだけど\pうまく かくれすぎると\nだれにも みつけて もらえないで ござる\lそれは ちょっと さびしいで ござるなあ\pそれでは これにて どろん!$"

MatchCall_PersonalizedText44::
	.string "{JPN}{STR_VAR_1}よ\nあれから しゅぎょうを かさねて\pわたしの {STR_VAR_2}も\nけっこう つよく なってきたわよ\pやっぱり すなはまでの しゅぎょうは\nこうかてき だわ!\lじゃあ また!$"

MatchCall_PersonalizedText45::
	.string "{JPN}こんにちは {STR_VAR_1}です\nかざんばい いつになったら\lおさまるの かしら\pあんまり つもっちゃうと\nパラソルの がらが\lみえなく なっちゃうのに……\pそれでは また\nおあい しましょう$"

MatchCall_PersonalizedText46::
	.string "{JPN}{STR_VAR_1} でーす\pねえねえ!\nうみって プールと くらべて\lうかびやすいって しってた?\pこうやって からだを よこに すれば\lかってに うくのよ\pでも あんまり ながく うかんでると\nおきに ながされるから\lきを つけないと だめよ\p……あれ? ここ どこかしら……\nじゃ じゃあ またね!$"

MatchCall_PersonalizedText47::
	.string "{JPN}あ {PLAYER}{KUN} こんにちは!\n{STR_VAR_1} です\pここって じめんが でこぼこ してるから\nテント はれないのよね……\lせっかく やまに きたのに……\pあ! いいこと おもいついた!\nポケモンで ここを たいらに\lできないかしら?\pよーし がんばっちゃおう!\nじゃあ またね!$"

MatchCall_PersonalizedText48::
	.string "{JPN}あ こんにちは\n{STR_VAR_1} でーす\pルミと いっしょに がんばって\nポケモン そだててるの!\pもっと がんばったら\nいちばんに なれるかなあ?\lじゃあ またねー!$"

MatchCall_PersonalizedText49::
	.string "{JPN}{STR_VAR_1}だ!\pオレさまは ふなのり だが\nいまは ふねに のっていない\pふねに のっていない ふなのりは\nなんと よべば いいだろうか!\pうみを みながら\nそんな ことを かんがえて いるのだ!\lじゃあ またな!!$"

MatchCall_PersonalizedText50::
	.string "{JPN}{STR_VAR_1} だよ\nどう? ポケモン ふえた?\pあたらしい ポケモン つかまえたら\nまた みせに きてくれよ\pちょうだいって いわないからさ\nまってるよ じゃあね$"

MatchCall_PersonalizedText51::
	.string "{JPN}{STR_VAR_1}だ\nポケモン ちゃんと そだててるか?\pここは くうきも きれいだし\nポケモンを そだてるには\lぜっこうの かんきょう なんだよな\pきみも ポケモンを そだてる ことに\nせんねん する ときは\l{STR_VAR_2}に くると いいぞ\lじゃあ またな$"

MatchCall_PersonalizedText52::
	.string "{JPN}{STR_VAR_1}です\nわたしの {STR_VAR_2}に\pポロック あげたんですよ\nとても よろこんでた みたい\pポケモンに よって\nポロックの すききらいが あるみたいなの\pおもしろい ですよね\nでは ごきげんよう$"

MatchCall_PersonalizedText53::
	.string "{JPN}{STR_VAR_1}だ\nポケモンと きょうりょく すれば\lしぜんの なかでも\lかいてきに くらせる ものだよ\pみんな それに きが ついて\nもっと ポケモンと\lきょうりょく できるように なれば\lいいのにな!\pきみは けっこう いいセン\nいってると おもうよ!\lじゃ またな!$"

MatchCall_PersonalizedText54::
	.string "{JPN}いつも ぼうけんの じゅんびを\nおこたらない {STR_VAR_1}よ!\p{PLAYER}{KUN} どうぐは たりてる?\nポケモンの たいちょうは バッチリ?\pじぶんの みの まわりを\nつねに かんぺきに しておくことが\lたびを ながく つづける ひけつ よ!\pわたしも じぶんの どうぐを\nかくにん するわ! またね!$"

MatchCall_PersonalizedText55::
	.string "{JPN}{STR_VAR_1}だよ {STR_VAR_1}だよー!\p{STR_VAR_2} って\nひとどおりが はげしいから\lまいにち いろんな ひとに\lしょうぶを もうしこまれるの!\pきょうはねえ 5にんに かって\n3にんに まけたわ!\lあなたのほうは どうだった?\lこんど きかせてねっ! じゃあね$"

MatchCall_PersonalizedText56::
	.string "{JPN}むしポケモンを いっぱい もってて\nにんきものの {STR_VAR_1} だけど!\p……きょう がっこうに\nおきにいりの むしポケモンを\lいっぱい つれて いったら\lすきな おんなのこに なかれ ちゃった……\lうう わらいたければ わらって くれよ\pぼくは むしポケモンの よさを\nあのコに わかって もらえるまで\lがんばるんだ からね!\pグッスン じゃーな!$"

MatchCall_PersonalizedText57::
	.string "{JPN}はっ ほっ はっ ほっ\pやあ! {STR_VAR_1}です! はっ ほっ\pやま……のぼり しながらの おしゃべりも\nなかなか どうして…… はっ ほっ\lトレーニングに なるなあ\pふっ くっ……\nおっと のぼりが きつく なってきた\lま また こんど…… ゆっくり はなそう!\lはっ ほっ はっ……$"

MatchCall_PersonalizedText58::
	.string "{JPN}や や どうも!\nいま ナツと おたから さがしててさ!\pおたから なんて もしかしたら\nほんとうは ないのかも しれないけど……\pナツと おたからを ふたりで さがす\nって ことが だいじ なんだよね\p……て あれ ナツ?\nな なんで おこってるの?\lほっといて ゴメンね\lもちろん キミが いちばん だいじだよぉ\lわかっている だろう?\pじ じゃ…… {PLAYER}さんさようなら$"

MatchCall_PersonalizedText59::
	.string "{JPN}じぶんは {STR_VAR_1}だ!\nしゅぎょうの ために また\lムロの ポケモンジムに いってきた!\pジムリーダーの トウキは\nあらなみに もまれ つよくなった!\lなのに ちっとも あせくさく ないし\lもてもてで しょうじき くやしい!\pなかまの シバ という おとこも\nきっと あせくさく なくて\lビッグウェーブ だとか ボク だとか\lさわやかに いったり するのだろう!\p……やきもちは みぐるしいな!\nすまん わすれて くれ! オスっ!$"

MatchCall_PersonalizedText60::
	.string "{JPN}わかい トレーナーさんと\nおはなし できて うれしい のう\pきみも もちろん\nなんさいに なっても ポケモンを\lがんばる つもり じゃろう?\lその ときには わしらのように\lだれか あいてが いると いいのう!\pまあ {PLAYER}{KUN}は いまだって\nポケモンに しんらい されて\lずっと がんばって おるからのう\pりっぱな きんこんしきに なれる\nそしつは バッチリじゃ!\lはっはっはっ がんばるのじゃよ!$"

MatchCall_PersonalizedText61::
	.string "{JPN}{STR_VAR_1}です!\nさっき ボクたち めずらしく\lかいパンの おにいさんに かったんだ!\lでも かっこいい ひとだった から……\pせっかく かよわい ところを\nみせようと したのに!\pって ねえちゃんに おこられた……\pどーせ かっても まけても\nおこられるんだ ボクは!\l{PLAYER}{KUN}も こんど\lなんとか いって やって!\pじゃ またねー!$"

MatchCall_PersonalizedText62::
	.string "{JPN}{STR_VAR_1}だよ うん……\nきのうは いせきを もとめて\lちがう うみに でようと したら\lみちに まよってしまったよ\pうみを めぐり めぐって\nきがついたら また もとの ばしょさ\pあいかわらず しょうぶも よわいし\nもう わらって くれよ……\pまあ わしは あきらめんぞ\nいつのひか いせきを みつけたら\lわしの じだいが くるだろう からな!\pそういった わけで\nきょうは これで さらばだ!$"

MatchCall_PersonalizedText63::
	.string "{JPN}やあー きみーっ!\n{STR_VAR_1}だー!\lわたしは いまー\l108ばんすいどうに きているーっ!\pつまり いつもと おなじ ところだー!\pきょうは めの まえを\nビキニのおねえさんが とおったからーっ\lおおごえで おどかして みたーっ!\pそしたら いやな かおを されたー!\pいじょう 108ばんすいどう から\n{STR_VAR_1}が おつたえ したー!$"

MatchCall_PersonalizedText64::
	.string "{JPN}{STR_VAR_1}よ!\nいま いそがしいんだけど\lきょうは もう\l5にんの トレーナーを たおしたから\lあなたにも いちおう ほうこく するわ!\pこの ちょうし だと\nつぎは たぶん あなたに かてるわね!\lわたしたち いい ライバルとして\lやって いけそうね……\lじゃあね バイ!$"

MatchCall_BattleFrontierStreakText1::
	.string "{JPN}こんにちは {STR_VAR_1} です!\nきいたよ!\p{STR_VAR_2} で\nすごい かつやく したんだって?\p{STR_VAR_3}れんしょう って すごいなあ\nじゃあ またね!$"

MatchCall_BattleFrontierStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす\n{STR_VAR_2} で\l{STR_VAR_3}れんしょう したって きいたわよ!\pすっごーい! わたしも がんばろうっと!\nじゃあ またね!$"

MatchCall_BattleFrontierStreakText3::
	.string "{JPN}おう! {PLAYER}!\n{STR_VAR_1}だぞ!\p{STR_VAR_2} で\nおおあばれ したらしいな!\p{STR_VAR_3}れんしょう って\nすごい きろく なんだろ?\pおれも まけられねーな!\nじゃ またな!$"

MatchCall_BattleFrontierStreakText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だけど げんき かい?\pうわさで きいたんだけど\nきみ {STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんだって?\pぼくも がんばらなきゃな\nじゃあ また$"

MatchCall_BattleFrontierStreakText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} だよ\p{STR_VAR_2}で\n{STR_VAR_3}れんしょうも したんだってね!\lすごいなあ\pぼくも ポケモン そだてなきゃ\nじゃあ また$"

MatchCall_BattleFrontierStreakText6::
	.string "{JPN}{PLAYER}{KUN} かい?\nこんにちは {STR_VAR_1} だ\pそういえば きみ\n{STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんだってね\pおれも がんばって\nポケモンを そだてるよ$"

MatchCall_BattleFrontierStreakText7::
	.string "{JPN}えーと あ {PLAYER}{KUN}?\n{STR_VAR_1} だ・・・\pそういえば {STR_VAR_2} で\n{STR_VAR_3}れんしょう したんだってね\pあ! いま めずらしい ポケモンを\nみつけたから じゃあ また!$"

MatchCall_BattleFrontierStreakText8::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\pちょうしは どうですか?\nそういえば {STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんですって?\pすごいですね!\nつぎも がんばってね$"

MatchCall_BattleFrontierStreakText9::
	.string "{JPN}あら {PLAYER}{KUN}!\nこんにちは {STR_VAR_1}です!\pきいたわよ! {STR_VAR_2}で\n{STR_VAR_3}れんしょうも したって!\pすっごいねー\nわたしも がんばらなくちゃ$"

MatchCall_BattleFrontierStreakText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\p{STR_VAR_2}で\n{STR_VAR_3}れんしょうも したんですって?\pすごいわねえ\nわたしも がんばらなくちゃ$"

MatchCall_BattleFrontierStreakText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n{STR_VAR_1}だ\p{STR_VAR_2}で だいかつやく らしいなあ\n{STR_VAR_3}れんしょう したんだって?\pすげえなあ おれだったら\nなんれんしょう できるのかな$"

MatchCall_BattleFrontierStreakText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが げんきかの?\pひとづてに きいたのじゃが\n{STR_VAR_2} とかいう ところで\l{STR_VAR_3}れんしょうも したらしいのう?\pすごい はなし だのう\nでは またの$"

MatchCall_BattleFrontierStreakText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2}で\n{STR_VAR_3}れんしょうも したそうじゃのう\pげんきで いいことじゃ\nでは またのう$"

MatchCall_BattleFrontierStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pきいたわよ!\n{STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんですって?\pすごいわねえ かんしん しちゃうわ!\nじゃあ またね$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "{JPN}こんにちは {STR_VAR_1} です!\nきいたよ!\p{STR_VAR_2} で\nすごい かつやく したんだって?\p{STR_VAR_3}れんしょう って すごいなあ\nじゃあ またね!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす\n{STR_VAR_2} で\l{STR_VAR_3}れんしょう したって きいたわよ!\pすっごーい! わたしも がんばろうっと!\nじゃあ またね!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "{JPN}おう! {PLAYER}!\n{STR_VAR_1}だぞ!\p{STR_VAR_2} で\nおおあばれ したらしいな!\p{STR_VAR_3}れんしょう って\nすごい きろく なんだろ?\pおれも まけられねーな!\nじゃ またな!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だけど げんき かい?\pうわさで きいたんだけど\nきみ {STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんだって?\pぼくも がんばらなきゃな\nじゃあ また$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} だよ\p{STR_VAR_2}で\n{STR_VAR_3}れんしょうも したんだってね!\lすごいなあ\pおれ? おれは まあ ぼちぼちかなー\nじゃあ またね$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "{JPN}{PLAYER}{KUN} かい?\nこんにちは {STR_VAR_1} だ\pそういえば きみ\n{STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんだってね\pおれも がんばらなきゃ!\nじゃあ またね$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "{JPN}えーと あ {PLAYER}{KUN}?\n{STR_VAR_1} だ・・・\pそういえば {STR_VAR_2} で\n{STR_VAR_3}れんしょう したんだってね\pあ! いま めずらしい ポケモンを\nみつけたから じゃあ また!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\pちょうしは どうですか?\nそういえば {STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんですって?\pすごいですね! わたしも がんばって\nポケモンを そだてなきゃ$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "{JPN}あら {PLAYER}{KUN}!\nこんにちは {STR_VAR_1}です!\pきいたわよ! {STR_VAR_2}で\n{STR_VAR_3}れんしょうも したって!\pすっごいねー\nわたしも がんばらなくちゃ$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\p{STR_VAR_2}で\n{STR_VAR_3}れんしょうも したんですって?\pすごいわねえ\nわたしも がんばらなくちゃ$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n{STR_VAR_1}だ\p{STR_VAR_2}で だいかつやく らしいなあ\n{STR_VAR_3}れんしょう したんだって?\pすげえなあ おれだったら\nなんれんしょう できるのかな$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが げんきかの?\pひとづてに きいたのじゃが\n{STR_VAR_2} とかいう ところで\l{STR_VAR_3}れんしょうも したらしいのう?\pすごい はなし だのう\nでは またの$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2}で\n{STR_VAR_3}れんしょうも したそうじゃのう\pげんきで いいことじゃ\nでは またのう$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pきいたわよ!\n{STR_VAR_2}で\l{STR_VAR_3}れんしょうも したんですって?\pすごいわねえ かんしん しちゃうわ!\nじゃあ またね$"

MatchCall_BattleDomeText1::
	.string "{JPN}あ! {PLAYER}?\nこんにちは {STR_VAR_1} です!\pきいたよ!\n{STR_VAR_2} で\p{STR_VAR_3}かい も\nゆうしょう したんだって?\pすごいね! ぼくも がんばらなきゃ!\nじゃあ またね$"

MatchCall_BattleDomeText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす!\nきいたわよ!\p{STR_VAR_2} で\n{STR_VAR_3}かい も\lゆうしょう したんですって?\pすごいわねー\nわたしも ゆうしょう できるのかな?$"

MatchCall_BattleDomeText3::
	.string "{JPN}よう {PLAYER}!\n{STR_VAR_1}だぞ げんきかー?\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう したって きいたぞ\pつぎも がんばれよなー\nじゃあ またな$"

MatchCall_BattleDomeText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\p{STR_VAR_2}で {STR_VAR_3}かいも\nゆうしょう した らしいね\pがんばってる みたいだね\nぼくも まけないように しなきゃ$"

MatchCall_BattleDomeText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} だよ\pきいたよ {STR_VAR_2}で\n{STR_VAR_3}かいも ゆうしょう したんだって?\pぼくも がんばらなきゃ\nじゃあ またね$"

MatchCall_BattleDomeText6::
	.string "{JPN}{PLAYER}{KUN} かい?\nこんにちは {STR_VAR_1} だ\pそういえば きみ\n{STR_VAR_2}で {STR_VAR_3}かいも\lゆうしょう したんだってね\pおれも まけないように\nポケモンを そだてなきゃな$"

MatchCall_BattleDomeText7::
	.string "{JPN}{PLAYER}{KUN}?\nああ {STR_VAR_1} だけど\p{STR_VAR_2}で ゆうしょうを\n{STR_VAR_3}かいも したんだって?\pへー ところで さいきん\nめずらしい ポケモン つかまえた?\pあ そう\nじゃあ またね$"

MatchCall_BattleDomeText8::
	.string "{JPN}こんにちは {PLAYER}{KUN}\n{STR_VAR_1} です\pげんき ですか?\n{STR_VAR_2}で {STR_VAR_3}かいも\lゆうしょう したんですって?\pすごいですね!\nわたしも がんばって\pポケモン そだてないと!\nじゃあ またね$"

MatchCall_BattleDomeText9::
	.string "{JPN}あら {PLAYER}{KUN}!\nこんにちは {STR_VAR_1}です!\p{STR_VAR_2}で\n{STR_VAR_3}かいも ゆうしょう したんだって?\pすっごいねー\nわたしも がんばらなくちゃ$"

MatchCall_BattleDomeText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\p{STR_VAR_2}で\n{STR_VAR_3}れんしょうも したんですって?\pすごいわねえ\nわたしも がんばらなくちゃ$"

MatchCall_BattleDomeText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n{STR_VAR_1}だ\p{STR_VAR_2}で\nだいかつやく らしいなあ\l{STR_VAR_3}れんしょう したんだって?\pすげえなあ おれでも\nゆうしょう できるのかな\p・・・ むりかな?\nじゃあ またな$"

MatchCall_BattleDomeText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2} とかいう ところで\n{STR_VAR_3}かい ゆうしょう したとな?\pすごい はなし だのう\nでは またの$"

MatchCall_BattleDomeText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2} で\n{STR_VAR_3}かいも ゆうしょう とな?\pげんきで いいことじゃ\nでは またのう$"

MatchCall_BattleDomeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pきいたわよ!\n{STR_VAR_2} で\p{STR_VAR_3}かいも\nゆうしょう したんですって?\pすごいわねえ かんしん しちゃうわ!\nじゃあ またね$"

MatchCall_BattlePikeText1::
	.string "{JPN}あ! {PLAYER}?\nこんにちは {STR_VAR_1} です!\pきいたよ!\n{STR_VAR_2} で\p{STR_VAR_3}も へやを\nとっぱ したんだって?\pすごいなあ\nじゃあ またね$"

MatchCall_BattlePikeText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす!\nきいたわよ!\p{STR_VAR_2} で{STR_VAR_3}へやも\nかちぬいたんですって?\pわたしも がんばらなきゃ!\nじゃあ またね$"

MatchCall_BattlePikeText3::
	.string "{JPN}よう {PLAYER}!\n{STR_VAR_1}だぞ げんきかー?\p{STR_VAR_2}で {STR_VAR_3}へやも\nとっぱ したって きいたぞ\pつぎも がんばれよなー\nじゃあ またな$"

MatchCall_BattlePikeText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\p{STR_VAR_2}で {STR_VAR_3}へやも\nとっぱ した らしいね\pおれも まけないように\nポケモン そだてなきゃな$"

MatchCall_BattlePikeText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} だよ\pきいたよ {STR_VAR_2}で\n{STR_VAR_3}へやも とっぱ したんだって?\pぼくも がんばらなきゃ\nじゃあ またね$"

MatchCall_BattlePikeText6::
	.string "{JPN}{PLAYER}{KUN} かい?\nこんにちは {STR_VAR_1} だ\pそういえば きみ\n{STR_VAR_2}で {STR_VAR_3}へやも\lとっぱ したんだってね\pおれも まけないように\nポケモンを そだてなきゃな$"

MatchCall_BattlePikeText7::
	.string "{JPN}{PLAYER}{KUN}?\nああ {STR_VAR_1} だけど\p{STR_VAR_2}で {STR_VAR_3}へやも\nとっぱ したんだって?\pすごいねえ\nあ めずらしいポケモンを みつけたから\pじゃあ また$"

MatchCall_BattlePikeText8::
	.string "{JPN}こんにちは {PLAYER}{KUN}\n{STR_VAR_1} です\pげんき ですか?\n{STR_VAR_2}で {STR_VAR_3}へやも\lとっぱ したんですって?\pすごいですね!\nわたしも がんばって\pポケモン そだてないと!\nじゃあ またね$"

MatchCall_BattlePikeText9::
	.string "{JPN}あら {PLAYER}{KUN}!\nこんにちは {STR_VAR_1}です!\p{STR_VAR_2}で {STR_VAR_3}へやも\nとっぱ したんだって?\pすっごいねー\nわたしも がんばらなくちゃ$"

MatchCall_BattlePikeText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\p{STR_VAR_2}で\n{STR_VAR_3}へやも とっぱ したんですって?\pすごいわねえ\nわたしも がんばらなくちゃ$"

MatchCall_BattlePikeText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n{STR_VAR_1}だ\p{STR_VAR_2}で\nだいかつやく らしいなあ\l{STR_VAR_3}へやも とっぱ したんだって?\pすげえなあ おれでも\nゆうしょう できるのかな\p・・・ むりかなあ?\nじゃあ またな$"

MatchCall_BattlePikeText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2} とかいう ところで\n{STR_VAR_3}へや とっぱ したとな?\pすごい はなし だのう\nでは またの$"

MatchCall_BattlePikeText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2}で\n{STR_VAR_3}へやも とっぱした とな?\pげんきで いいことじゃ\nでは またのう$"

MatchCall_BattlePikeText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pきいたわよ!\n{STR_VAR_2}で\p{STR_VAR_3}へやも\nとっぱ したんですって?\pすごいわねえ かんしん しちゃうわ!\nじゃあ またね$"

MatchCall_BattlePyramidText1::
	.string "{JPN}あ! {PLAYER}?\nこんにちは {STR_VAR_1} です!\pきいたよ!\n{STR_VAR_2} で\p{STR_VAR_3}だん も\nのぼったんだって?\pすごいねー ぼくも こんど\nちょうせん してみようかなー$"

MatchCall_BattlePyramidText2::
	.string "{JPN}こんにちは {STR_VAR_1} でーす!\nきいたわよ!\p{STR_VAR_2} で\n{STR_VAR_3}だん も\lかちぬいたんですって?\pすごーい! わたしの ポケモンも\nがんばって そだてなくちゃ$"

MatchCall_BattlePyramidText3::
	.string "{JPN}よう {PLAYER}!\n{STR_VAR_1}だぞ げんきかー?\p{STR_VAR_2}で {STR_VAR_3}だんも\nのぼったって きいたぞ\pつぎも がんばれよなー\nじゃあ またな$"

MatchCall_BattlePyramidText4::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} だ\p{STR_VAR_2}で {STR_VAR_3}だんも\nのぼった らしいね\pぼくも きみに まけないように\nがんばらなきゃな$"

MatchCall_BattlePyramidText5::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} だよ\pきいたよ {STR_VAR_2} で\n{STR_VAR_3}だんも のぼったんだって?\pぼくも がんばらなきゃ\nじゃあ またね$"

MatchCall_BattlePyramidText6::
	.string "{JPN}{PLAYER}{KUN} かい?\nこんにちは {STR_VAR_1} だ\pそういえば きみ\n{STR_VAR_2}で {STR_VAR_3}だんも\lかちぬいたんだってね\pおれも まけないように\nポケモンを そだてなきゃな$"

MatchCall_BattlePyramidText7::
	.string "{JPN}{PLAYER}{KUN}?\nああ {STR_VAR_1} だけど\p{STR_VAR_2}で {STR_VAR_3}だんも\nのぼったんだって?\pへー…… そこに\nめずらしい ポケモン いなかった?\pそうかー いないかー\nじゃあ また$"

MatchCall_BattlePyramidText8::
	.string "{JPN}こんにちは {PLAYER}{KUN}\n{STR_VAR_1} です\pげんき ですか?\n{STR_VAR_2}で {STR_VAR_3}だんも\lかちぬいたんですって?\pすごいですね!\nわたしも がんばって\pポケモン そだてないと!\nじゃあ またね$"

MatchCall_BattlePyramidText9::
	.string "{JPN}あら {PLAYER}{KUN}!\nこんにちは {STR_VAR_1}です!\p{STR_VAR_2}で {STR_VAR_3}だんも\nかちぬいたんだって?\pすっごいねー\nわたしも がんばらなくちゃ$"

MatchCall_BattlePyramidText10::
	.string "{JPN}{PLAYER}{KUN} こんにちは\n{STR_VAR_1} です\p{STR_VAR_2}で\n{STR_VAR_3}だんも のぼったんですって?\pすごいわねえ\nわたしも がんばらなくちゃ$"

MatchCall_BattlePyramidText11::
	.string "{JPN}やあやあ {PLAYER}{KUN}\n{STR_VAR_1}だ\p{STR_VAR_2}で\nだいかつやく らしいなあ\l{STR_VAR_3}だんも のぼったんだって?\pすげえなあ おれでも\nゆうしょう できるのかな\p・・・ できない?\nじゃあ またな$"

MatchCall_BattlePyramidText12::
	.string "{JPN}やあ {PLAYER}{KUN}\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2} とかいう ところで\n{STR_VAR_3}だんも かちぬいたとな?\pすごい はなし だのう\nでは またの$"

MatchCall_BattlePyramidText13::
	.string "{JPN}{PLAYER}{KUN} かい?\n{STR_VAR_1} じゃが げんきかの?\p{STR_VAR_2}で\n{STR_VAR_3}だんも のぼったとな?\pげんきで いいことじゃ\nでは またのう$"

MatchCall_BattlePyramidText14::
	.string "{JPN}あら {PLAYER}{KUN} こんにちは\n{STR_VAR_1} よ\pきいたわよ!\n{STR_VAR_2}で\p{STR_VAR_3}だんも\nかちぬいたんですって?\pすごいわねえ かんしん しちゃうわ!\nじゃあ またね$"

MatchCall_Text_Mom1::
	.string "{JPN}ママ『パパも あなたも\nみんな ポケモンに むちゅう なのね\pポケモンの みりょく って\nなんなの かしら……\pわたし?\nわたしは いえの ようじを おてつだい\lしてくれる ポケモンが すきだわ$"

MatchCall_Text_Mom2::
	.string "{JPN}ママ『あら {PLAYER}\nパパなら まいにち トウカシティの\lジムに こもってるわよ!\pときどき うちに かえってきては\nたくさん ごはんを たべて\lまた でかけて いくの!\pあなたに まけたのが\nよっぽど くやしかった みたいね!$"

MatchCall_Text_Mom3::
	.string "{JPN}ママ『{PLAYER}……\pおうちの ことなら きにしなくて いいから\nママが あげた ランニングシューズ\lボロボロに なるまで はいてちょうだいね!$"

MatchCall_Text_Roxanne_Preparing::
	.string "{JPN}ツツジ『あら {PLAYER}さん!\pあれから また トレーニングを\nやりなおして いるところ なんですよ!\pまた ジムを さいかい するためには\nもうすこし じかんが かかりますが\pもし ジムを さいかい できたら\nぜひまた ちょうせん してくださいね……$"

MatchCall_Text_Roxanne_PreparingPostGame::
	.string "{JPN}ツツジ『{PLAYER}さん おめでとう!\nうわさは ききましたよ!\pこちらは ジムを さいかい するためには\nもうすこし じかんが かかりますが\pもし ジムを さいかい できたら\nぜひまた ちょうせん してくださいね……$"

MatchCall_Text_Roxanne_RematchReady::
	.string "{JPN}ツツジ『{PLAYER}さん!\nジムの じゅんびが できました!\pいつでも カナズミ シティまで\nきてくださいな!$"

MatchCall_Text_Roxanne_PostRematch::
	.string "{JPN}ツツジ『{PLAYER}さんと\nしょうぶ できたことは\lカナズミ ジムの ほこりですよ!$"

MatchCall_Text_Brawly_Preparing::
	.string "{JPN}トウキ『やあ {PLAYER}{KUN}!\pキミとの しょうぶでは いろんなことを\nまなばせて もらったよ!\pまた しゅぎょう しなおして\nジムを さいかいする つもりさ!\pジムの じゅんびが できるまでは\nまだ じかんが かかりそう だけど\pもし ジムを さいかい できたら\nぜひまた ちょうせん してくれよ……$"

MatchCall_Text_Brawly_PreparingPostGame::
	.string "{JPN}トウキ『{PLAYER}{KUN} おめでとう!\pキミの うわさは しおかぜに のって\nこのまちにも とどいて いるよ!\pボクのほうは まだまだ しゅぎょうを\nやりなおす ひつようが ありそうだ\pジムの じゅんびが できるまでは\nまだ じかんが かかりそう だけど\pもし ジムを さいかい できたら\nぜひまた ちょうせん してくれよ……$"

MatchCall_Text_Brawly_RematchReady::
	.string "{JPN}トウキ『{PLAYER}{KUN}!\nジムの じゅんびが できたよ!\pいつでも ムロ タウンまで\nちょうせんしに きてくれよな!$"

MatchCall_Text_Brawly_PostRematch::
	.string "{JPN}トウキ『{PLAYER}{KUN} とは\nなんど しょうぶ しても あきないよ!$"

MatchCall_Text_Wattson_Preparing::
	.string "{JPN}テッセン『おう おまえさんか!\pわしは あれから また トレーニングを\nやりなおして いるところ じゃよ!\pわしの ジムを さいかいするには\nまだ ちーと じかんが かかりそうじゃな!\pそれまで まっていて おくれ!\nわっはははは!$"

MatchCall_Text_Wattson_PreparingPostGame::
	.string "{JPN}テッセン『わっははは!\pおまえさん とうとう やったな!\nうわさは わしの みみにも とどいとる!\pこちらは まだまだ しゅぎょうを\nやりなおす ひつようが ありそうじゃ\pわしの ジムを さいかいするには\nまだ ちーと じかんが かかりそうじゃな!\pそれまで まっていて おくれ!\nわっはははは!$"

MatchCall_Text_Wattson_RematchReady::
	.string "{JPN}テッセン『おう おまえさんか!\nジムの じゅんびが できたぞい!\pいつでも キンセツ シティまで\nくるがいいぞ! わっははは!$"

MatchCall_Text_Wattson_PostRematch::
	.string "{JPN}テッセン『わっははは!\pおまえさんとの ポケモン しょうぶは\nビリビリと しげきてきじゃな!$"

MatchCall_Text_Flannery_Preparing::
	.string "{JPN}アスナ『{PLAYER}さん……\pあなたとの しょうぶで じぶんの\nみじゅくさを おもいしらされた けど\lわたしは これで おわったり しないよ!\pもういちど しゅぎょうを しなおして\nまた ジムを さいかい するんだ!\pそのときには {PLAYER}さん\nぜったい ちょうせんしに きてよね!$"

MatchCall_Text_Flannery_PreparingPostGame::
	.string "{JPN}アスナ『{PLAYER}さん おめでとう!\pあなたの うわさは かざんの ねつのように\nわたしにも つたわって きてるよ!\pこちらも じゅんちょうに\nトレーニングが すすんでるんだ!\pジムの じゅんびが できたら\nエントリーコールの なまえの ところに\lしるしが つくからね!$"

MatchCall_Text_Flannery_RematchReady::
	.string "{JPN}アスナ『あっ {PLAYER}さん?\nジムの じゅんびは もうできてます!\pおんせんに はいる ついでに\nフエン タウンまで きてくださいね!$"

MatchCall_Text_Flannery_PostRematch::
	.string "{JPN}アスナ『{PLAYER}さん……\nポケモンの あつかいかたが\lどんどん うまくなってる きがするよ!$"

MatchCall_Text_Winona_Preparing::
	.string "{JPN}ナギ『こんにちは {PLAYER}さん!\pあなたと しょうぶを したおかげで\nじぶんの じゃくてんが よくわかったわ!\pいつか また ジムを さいかい できたら\nそのときは もう まけませんよ!$"

MatchCall_Text_Winona_PreparingPostGame::
	.string "{JPN}ナギ『やりましたね {PLAYER}さん!\pしんチャンピオン たんじょうの うわさは\nヒワマキにも とどいて いますよ!\pでも…… つぎに しょうぶ するときは\nこのまえの ようには いきませんからね!$"

MatchCall_Text_Winona_RematchReady::
	.string "{JPN}ナギ『ええと {PLAYER}さん?\nジムの じゅんびが できましたよ!\pヒワマキ シティで まってます!$"

MatchCall_Text_Winona_PostRematch::
	.string "{JPN}ナギ『{PLAYER}さん……\nしょうぶに まけても わたしの つばさは\lけっして おれることは ないのです!\pそう {PLAYER}さんが\nゆめを あきらめなかった ように!$"

MatchCall_Text_TateLiza_Preparing::
	.string "{JPN}フウ『あっ あなたは\nラン『{PLAYER}さん ですね!\pフウ『ぼくたち ジムを さいかい するため\nラン『しゅぎょう しなおして いるんです!\pフウ『ジムの じゅんびが できたら\nラン『ジムの じゅんびが できたら\pフウ『エントリーコールの なまえに\nラン『しるしが つくので わかるんです!$"

MatchCall_Text_TateLiza_PreparingPostGame::
	.string "{JPN}フウ『{PLAYER}さん おめでとう!\nラン『{PLAYER}さん おめでとう!\pフウ『ぼくたち ふたりは\nラン『まだ しゅぎょうちゅう!\pフウ『もうすこし じかんが かかるけど\nラン『もし ジムを さいかい できたら\pフウ『エントリーコールの なまえに\nラン『しるしが つくから わかりますよ!$"

MatchCall_Text_TateLiza_RematchReady::
	.string "{JPN}フウ『{PLAYER}さん!\nラン『{PLAYER}さん!\pフウ『ジムの じゅんびが できました!\nラン『ジムの じゅんびが できました!\pフウ『いつでも トクサネ シティまで\nラン『きてくださいね!$"

MatchCall_Text_TateLiza_PostRematch::
	.string "{JPN}フウ『{PLAYER}さんとの しょうぶは\nラン『わたしたちの だいじな けいけん\pフウ『いつか また 3にんで\nラン『しょうぶが できると いいですね$"

MatchCall_Text_Juan_Preparing::
	.string "{JPN}アダン『ほ……\n{PLAYER}{KUN}…… でしたね\pユーとの たたかいは\nはじめて ミクリと であったときを\lおもいださせて くれましたよ\pもしかすると ユーは\nミクリを こえるほどの ジーニアス!\lすなわち てんさい かもしれません$"

MatchCall_Text_Juan_PreparingPostGame::
	.string "{JPN}アダン『ふ…… {PLAYER}{KUN}\nついに やりとげた ようですね\pやはり わたくしの ひとを みるめは\nまちがって いなかった……\pつよさを きわめた ユーとは\nぜひ また しょうぶ したい ものです$"

MatchCall_Text_Juan_RematchReady::
	.string "{JPN}アダン『ほっほ…… {PLAYER}{KUN}\pわが ルネシティ ジムが\nふたたび オープン したのですよ\pわたくしの すがたを みたくなったら\nまあ いつでも おいでなさい$"

MatchCall_Text_Juan_PostRematch::
	.string "{JPN}アダン『{PLAYER}{KUN}……\pユーと かなでる ポケモン しょうぶは\nせんれんされた おんがくにも にて\lハートに ふかく ひびいて きます……\pめを とじれば メロディーに あわせて\nゆうがに まう ユーの すがたが……$"

MatchCall_Text_Sidney::
	.string "{JPN}カゲツ『よお {PLAYER}!\pおれと ポケモン しょうぶ したけりゃ\nいつでも ポケモン リーグに おいで!\pおれは いつでも ここに いるからな\nじゃあ まってるぜ!$"

MatchCall_Text_Phoebe::
	.string "{JPN}フヨウ『ハーイ {PLAYER}!\pあなたと ポケモンの きずなが\nどれぐらい ふかく なったか\lたまには ここまで みせに きてよね!$"

MatchCall_Text_Glacia::
	.string "{JPN}プリム『こんにちは {PLAYER}\pあなたは その つよさに\nおぼれたり していない でしょうね\pあつい きもちを すこしだけ\nひやしたいと おもったら\lポケモン リーグに いらっしゃい……$"

MatchCall_Text_Drake::
	.string "{JPN}ゲンジ『そのこえは {PLAYER}か\nげんきそう だな……\pさいきん ポケモン リーグとは べつに\nトレーナーの うでを きそわせる\lバトル フロンティア とかいう しせつが\lあるらしいが……\pほんとうの しょうぶを したいのなら\nやはり ポケモン リーグだ!\pなあ {PLAYER}も そうおもう だろう?$"

MatchCall_Text_Wallace::
	.string "{JPN}ミクリ『やあ {PLAYER}{KUN}\nきみは ダイゴには あったかな?\pかれって……\nほんとうは ものすごく つよいのに\pあまり ポケモン しょうぶを しないで\nめずらしい いしを さがして ばかりいる\lかわりもの なんだよ\pどこかの どうくつか いわやまに\nもぐってるんじゃ ないかな\pめずらしい いし なんて\nわたしには いんせき ぐらいしか\lおもい うかばないんだけど……$"

MatchCall_Text_MayRayquazaCall:
	.string "{JPN}…… …… ……\n…… …… …… ピッ!\pハルカ『あっ {PLAYER}{KUN}!?\pあたしね さっきまで キナギ タウンに\nいってたんだけど\lおおきな みどりいろの ポケモンが\lそらを とんで いくのを みたの!\pあたし……\nあんな ポケモン みたこと ない!\pなんだろう もしかしたら これって\nだいはっけん!?\p…… …… ……\n…… …… …… ツー$"

MatchCall_Text_BrendanRayquazaCall:
	.string "{JPN}…… …… ……\n…… …… …… ピッ!\pユウキ『おっ {PLAYER}!?\pオレ さっきまで キナギ タウンに\nいってたんだけどさ\lでっかい みどりいろの ポケモンが\lそらを とんで いくのを みたんだ!\pあんな すごいの みたこと ないよ\n{PLAYER}にも みせたかったなあ!\p…… …… ……\n…… …… …… ツー$"

MatchCall_Text_May1::
	.string "{JPN}ハルカ『あっ {PLAYER}{KUN}!\pハギろうじんは\nふなのりを いんたい したけど\pときどき ピーコちゃんと いっしょに\nうみに でてるのを みかけるよ\pきっと いまも うみが すきなんだね!$"

MatchCall_Text_May2::
	.string "{JPN}ハルカ『ねえねえ {PLAYER}{KUN}!\pトウカや ムロみたいな\nちいさい まちに ジムが あるのに\pおおきな みなとまちの カイナには\nなぜか ジムが ないのよね\pいつか ジムが できたら あたし\nジムリーダーに りっこうほ しよっかなー$"

MatchCall_Text_May3::
	.string "{JPN}ハルカ『あっ {PLAYER}{KUN}!\pそういえば カナズミシティに\nいあいぎりオヤジ っていう ひとの\lいえが あったでしょ?\pキンセツシティには\nその おとうとが すんでるんだって!\pどんな なまえだと おもう?\p…… …… ……\n…… …… ……\pいわくだきオヤジ っていうの!$"

MatchCall_Text_May4::
	.string "{JPN}ハルカ『{PLAYER}{KUN}?\pカナシダトンネル って\nカナズミと シダケを むすぶから\lカナシダトンネル って いうのよね!$"

MatchCall_Text_May5::
	.string "{JPN}ハルカ『{PLAYER}{KUN} げんきー?\pあたしは いま\n111ばんどうろに きているの!\pさばくの うえのほうに すんでる\nおばあさんの ところで\lひとやすみ していく つもりよ!$"

MatchCall_Text_May6::
	.string "{JPN}ハルカ『あっ {PLAYER}{KUN}!\pさばくに げんえいのとう っていうのが\nたってるの しってる?\pしんきろう みたいに\nみえたり みえなかったり するんだって!\pあたしも みてみたいなー$"

MatchCall_Text_May7::
	.string "{JPN}ハルカ『{PLAYER}{KUN} やっほー!\pあたしは いま\n119ばんどうろに きているの!\pこのあたりは おおきな かわが あるし\nあめも しょっちゅう ふってるから\lずぶぬれに なっちゃったよ!$"

MatchCall_Text_May8::
	.string "{JPN}ハルカ『{PLAYER}{KUN}!\pおくりびやまには じゅみょうを おえた\nポケモンが まつられてるの!\pそのせいか しゅつげんする ポケモンも\nゴーストタイプが おおいのよ!$"

MatchCall_Text_May9::
	.string "{JPN}ハルカ『ねえねえ {PLAYER}{KUN}!\pあたし また フエンタウンの\nおんせんに いこうと おもったんだけど\pデコボコさんどうに\nにんそうの わるいのが うろついていて\lなんか いやーな かんじ だったわ!$"

MatchCall_Text_May10::
	.string "{JPN}ハルカ『あっ {PLAYER}{KUN}!\pクスノキかんちょうが せんすいていで\nかいていどうくつを はっけんした って\lニュースで やってたけど みた?$"

MatchCall_Text_May11::
	.string "{JPN}ハルカ『ねえねえ {PLAYER}{KUN}!\pふねが なくても ポケモンの わざで\nうみのうえを わたって いけるって\lすごいよね!\pでも それだけじゃなくて\nポケモンと いっしょに うみのそこに\lもぐれちゃう わざも あるんだって!$"

MatchCall_Text_May12::
	.string "{JPN}ハルカ『{PLAYER}{KUN} おつかれ!\pうみのうえで みえてるのに むこうがわへ\nいけない ところ なんかは\pどこかから いったん もぐって\nかいていの みちを とおりぬけて\lむこうの すいめんに でれば いいの!$"

MatchCall_Text_May13::
	.string "{JPN}ハルカ『はーい {PLAYER}{KUN}\pどう? ずかんは じゅんちょうに\nうまっていってる?\pあのね うわさで きいたんだけど\nどこかに ちょうこだいポケモン というのが\l3しゅるいも いるらしいの!\pうーん 1しゅるい だけでも いいから\nみてみたいなあ……$"

MatchCall_Text_May14::
	.string "{JPN}ハルカ『{PLAYER}{KUN}!\nうわさは きいたよ!\pルネの ジムリーダーにも かったって?\nということは もうひといき だね!$"

MatchCall_Text_May15::
	.string "{JPN}ハルカ『もう ホウエンちほうで\n{PLAYER}{KUN}を しらない\lトレーナー なんて いないんだよ!\pあたしが {PLAYER}{KUN}と\nともだちだ っていうと\lみんな ビックリ するんだから!$"

MatchCall_Text_Brendan1::
	.string "{JPN}ユウキ『おっ {PLAYER}!\pハギろうじんは\nふなのりを いんたい したけど\pときどき ピーコちゃんと いっしょに\nうみに でてるのを みかけるんだ\pきっと いまも うみが すきなんだろうな!$"

MatchCall_Text_Brendan2::
	.string "{JPN}ユウキ『やあ {PLAYER}!\pトウカや ムロみたいな\nちいさい まちに ジムが あるのに\pおおきな みなとまちの カイナには\nなぜか ジムが ないんだよな\pいつか ジムが できたら オレ\nジムリーダーに りっこうほ しようかな$"

MatchCall_Text_Brendan3::
	.string "{JPN}ユウキ『おっ {PLAYER}!\pそういえば カナズミシティに\nいあいぎりオヤジ っていう ひとの\lいえが あっただろう?\pキンセツシティには\nその おとうとが すんでるんだって!\pどんな なまえだと おもう?\p…… …… ……\n…… …… ……\pいわくだきオヤジ だってさ!$"

MatchCall_Text_Brendan4::
	.string "{JPN}ユウキ『そのこえは {PLAYER}?\pカナシダトンネル って\nカナズミと シダケを むすぶから\lカナシダトンネル なんだよ\pおまえ…… しってたか?$"

MatchCall_Text_Brendan5::
	.string "{JPN}ユウキ『{PLAYER} げんきか?\pオレは いま\n111ばんどうろに きてるんだ!\pさばくの うえのほうに すんでる\nばあさんの ところで\lひとやすみ していく つもりさ!\pちかくまで きたら\nおまえも よっていくと いいよ!$"

MatchCall_Text_Brendan6::
	.string "{JPN}ユウキ『あっ {PLAYER}!\pさばくに げんえいのとう っていうのが\nたってるの しってるか?\pしんきろう みたいに\nみえたり みえなかったり するんだよ!\pオレも みてみたいなー$"

MatchCall_Text_Brendan7::
	.string "{JPN}ユウキ『だれ? {PLAYER}か?\pオレは いま\n119ばんどうろに きてるんだ!\pこのへんは でっかい かわが あるし\nいっつも あめが ふってるから\lずぶぬれに なっちまったよ!$"

MatchCall_Text_Brendan8::
	.string "{JPN}ユウキ『{PLAYER}!\pおくりびやまには じゅみょうを おえた\nポケモンが まつられてるんだ!\pそのせいか しゅつげんする ポケモンも\nゴーストタイプが おおいんだよな!$"

MatchCall_Text_Brendan9::
	.string "{JPN}ユウキ『なあなあ {PLAYER}!\pオレ また フエンタウンの\nおんせんに いこうと おもったんだけど\pデコボコさんどうの とちゅうに\nにんそうの わるいのが いたんだよ!\pあれって マグマだん…… だよな!?$"

MatchCall_Text_Brendan10::
	.string "{JPN}ユウキ『おっ {PLAYER}!\pクスノキかんちょうが せんすいていで\nかいていどうくつを はっけんした って\lニュースで やってたけど みたか?$"

MatchCall_Text_Brendan11::
	.string "{JPN}ユウキ『なあなあ {PLAYER}!\pふねが なくても ポケモンの わざで\nうみのうえを わたって いけるって\lなんだか すごくないか!?\pしかも ポケモンと いっしょに\nうみのそこに もぐれる わざも あるって!\pポケモンって なんでも できるんだなー!$"

MatchCall_Text_Brendan12::
	.string "{JPN}ユウキ『{PLAYER} おつかれ!\pうみのうえで みえてるのに むこうがわへ\nいけない ところ なんかは\pどこかから いったん もぐって\nかいていの みちを とおりぬけて\lむこうの すいめんに でれば いいんだ!$"

MatchCall_Text_Brendan13::
	.string "{JPN}ユウキ『おーす {PLAYER}!\pどうだ? ずかんは じゅんちょうに\nうまっていってるか?\pあのな うわさで きいたんだけど\nどこかに ちょうこだいポケモン ってのが\l3しゅるいも いるらしいんだよ!\pうーん 1しゅるい だけでも いいから\nつかまえて みたいよなあ……$"

MatchCall_Text_Brendan14::
	.string "{JPN}ユウキ『{PLAYER}!\nうわさは きいたよ!\pルネの ジムリーダーにも かったって?\nすげえなあ もうひといき だな!$"

MatchCall_Text_Brendan15::
	.string "{JPN}ユウキ『もう ホウエンちほうで\n{PLAYER}のこと しらない\lトレーナー なんて いないんだ!\pオレが {PLAYER}と\nともだちだ っていうと\lみんな うらやましそうに するよ!$"

MatchCall_Text_Wally1::
	.string "{JPN}ミツル『あっ {PLAYER}さん!\pさいきんは からだの ぐあいも\nずいぶん よくなって きたし\pぼくも はやく {PLAYER}さん みたいな\nトレーナーに なりたいな!$"

MatchCall_Text_Wally2::
	.string "{JPN}ミツル『{PLAYER}さん こんにちは!\pカナシダトンネルが かいつう したせいで\nミチルおねえちゃんも\lすっごく うれしそう ですよ!$"

MatchCall_Text_Wally3::
	.string "{JPN}ミツル『あっ {PLAYER}さん!\pぼく…… シダケの おじさんに\nなにも いわずに でてきちゃった けど\lおじさん おこってないかな……\p{PLAYER}さん なら\nぼくの きもち わかって くれますよね?$"

MatchCall_Text_Wally4::
	.string "{JPN}ミツル『{PLAYER}さん?\nぼくです ミツルです!\pトレーナーの せかいって すごいですね!\nポケモンを つれて あるいていると\lみんなが こえを かけて くれるんです!\pまるで ポケモンを つうじて\nみんなが つながっている みたいに!$"

MatchCall_Text_Wally5::
	.string "{JPN}ミツル『{PLAYER}さん? すごいですよ!\n{PLAYER}さんと いっしょに つかまえた\lラルトスが しんか したんです!\pぼくって さいのう あるのかなあ……\pなーんて ちょうしに のったら\nいけませんよね\pえらいのは ポケモン ですもん!$"

MatchCall_Text_Wally6::
	.string "{JPN}…… …… ……\n…… …… ……\pミツルは ポケナビの よびだしが\nとどかない ところに いるようだ……$"

MatchCall_Text_Wally7::
	.string "{JPN}ミツル『あっ {PLAYER}さん!\pいままで ほとんど いえから\nでたことの ない ぼくが\pこうして ポケモンと いっしょに\nぼうけんを している なんて……\p{PLAYER}さん…… ありがとう$"

MatchCall_Text_Scott1::
	.string "{JPN}エニシダ『どーも どーも {PLAYER}{KUN}\pやまでも うみでも くさむらでも\nどこにだって ポケモンが いるように\lトレーナーさん というのも\lいろんな ところに いるもんだねえ\pおかげで わたしも\nアッチいったり コッチいったり\lいそがしくて しょうがないよ!$"

MatchCall_Text_Scott2::
	.string "{JPN}エニシダ『わたしは いま\n119ばん どうろに きてるんだけど\lたくさんの トレーナーが いるねえ!\pでも このあたりは せのたかい くさが\nいっぱい はえてるから\pはんズボンで あるきまわると\nあしが くすぐったくて こまるよ!$"

MatchCall_Text_Scott3::
	.string "{JPN}エニシダ『やあやあ {PLAYER}{KUN}!\pきみは おくりびやま って\nのぼったこと ある?\pあそこは ポケモンの たましいが\nまつられている ばしょ だからねえ\pトレーナー ならば いちど ぐらいは\nてっぺんまで のぼって みないとね!$"

MatchCall_Text_Scott4::
	.string "{JPN}エニシダ『んー {PLAYER}{KUN}!\pどうも ちかごろは\nマグマだん とか アクアだん とか\lおかしな れんちゅうが あばれてるね\pかれらの なかには\nすぐれた トレーナーも いるんだろうけど\lでも わるもの じゃあなあ……$"

MatchCall_Text_Scott5::
	.string "{JPN}エニシダ『おおー {PLAYER}{KUN}\pあのね うみのそこにも すごうでの\nトレーナーが いたり するのかな?\pでも たしかめに いこうにも\nわたしは およげないし\lポケモンも もってないし……$"

MatchCall_Text_Scott6::
	.string "{JPN}エニシダ『やあやあ {PLAYER}{KUN}!\pぜんぶの ジムバッジを あつめたら\nポケモンリーグに ちょうせん できる\lというのは しってるよね?\pきみほどの じつりょくが あるなら\nチャンピオンも ゆめじゃない けど……\lじつは もっと いいところが あるんだよ\pまあ いまは それいじょう\nいわないで おくよ\pポケモンリーグを かちぬいて\nでんどういり してからの おたのしみだね!$"

MatchCall_Text_Scott7::
	.string "{JPN}…… …… ……\n…… …… ……\pエニシダは ポケナビの よびだしが\nとどかない ところに いるようだ……$"

MatchCall_Text_Norman1::
	.string "{JPN}パパ『カナズミの まちには\nいあいぎりおやじ という\lかわった なまえの ひとが すんでいる!\pちかくまで いったら\nおまえも たずねて みると いいぞ!$"

MatchCall_Text_Norman2::
	.string "{JPN}パパ『ふむ…… {PLAYER}は\nすこしずつ しかし かくじつに\lつよく なっているな\pおまえが つよくなれば なるほど\nわたしや ママの もとから\lとおくへ はなれて いってしまう……\pなんとも ふくざつな きぶんだよ$"

MatchCall_Text_Norman3::
	.string "{JPN}パパ『そうか……\nジムバッジを 4つ あつめたのか\pでは やくそく どおり\nポケモンしょうぶ だな……\pいつでも おいで まってるぞ!$"

MatchCall_Text_Norman4::
	.string "{JPN}パパ『{PLAYER}! たまには ママにも\nあいに いって あげるんだぞ!\pわたしは ここで\nじぶんを きたえなおす!\pポケモンしょうぶの みちは\nおくが ふかい からな!$"

MatchCall_Text_Norman5::
	.string "{JPN}パパ『おお {PLAYER}!\pなになに? マグマのしるし……?\nなんのことか わたしには わからないが\pマグマと いうぐらい だから\nなにか かざんと かんけい ありそうだな!$"

MatchCall_Text_Norman_Preparing::
	.string "{JPN}パパ『せや! うりゃ! どりゃー!\p……お {PLAYER}か!\pわたしは いま ポケモンと いっしょに\nトレーニングの まっさいちゅうだ!$"

MatchCall_Text_Norman_PreparingPostGame::
	.string "{JPN}パパ『{PLAYER}!\pまさか おまえが でんどういりを\nはたして しまうとは……\pよし!\nわたしも まけては いられないぞ!$"

MatchCall_Text_Norman_RematchReady::
	.string "{JPN}パパ『……ん? {PLAYER}か?\nこれは ちょうど よかった!\pこんどは パパから おまえに\nしょうぶを もうしこんで やろう\pトウカの ジムで まってるから\nいつでも ちょうせんしに おいで!$"

MatchCall_Text_Norman_PostRematch::
	.string "{JPN}パパ『……すごいなあ {PLAYER}\nどこまで つよく なっちゃうんだろう $"

MatchCall_Text_Steven1::
	.string "{JPN}ダイゴ『やあ {PLAYER}{KUN}!\pもう キンセツシティには いったかな?\pまちの サイクルショップで\nマッハじてんしゃを てにいれたら\pもういちど いしのどうくつの おくに\nいってみるのも いいね!\pなにか あたらしい はっけんが\nあるかも しれないよ!$"

MatchCall_Text_Steven2::
	.string "{JPN}ダイゴ『やあ {PLAYER}{KUN}!\pボクは これまでに ずいぶん いろいろな\nトレーナーを みてきた けれど\pキミは だれにも にていない\nはじめて みる タイプの ひとだよ!$"

MatchCall_Text_Steven3::
	.string "{JPN}ダイゴ『やあ {PLAYER}{KUN}!\pキミは ポケモンと ぼうけんを していて\nどんな きぶんに なる?\pつよいみかた だと おもうかい?\nたのしいなかま だと おもうかい?\pキミが どう かんじるかに よって\nその ぼうけんの いみは かわるんだ!$"

MatchCall_Text_Steven4::
	.string "{JPN}ダイゴ『ああ {PLAYER}{KUN} かい?\pちょっと いま うちゅうセンターで\nめんどうな ことが おきてるんだ\pわるいけど また あとでね!$"

MatchCall_Text_Steven5::
	.string "{JPN}ダイゴ『あっ {PLAYER}{KUN}!\pなにも いわなくて いいよ!\nとにかく いまは……\pキミが おもうように すすむんだ!$"

MatchCall_Text_Steven6::
	.string "{JPN}…… …… ……\pダイゴには よびだしが\nつうじていない ようだ……$"

MatchCall_Text_Steven7::
	.string "{JPN}ダイゴ『{PLAYER}{KUN}……\nでんどういり おめでとう\p…… …… ……\n…… …… ……\pまた いつか あえると いいね!$"

MatchCall_Text_BirchRegisterCall:
	.string "{JPN}オダマキ『おお {PLAYER}{KUN}!\nはなしは すでに きいて いるよ!\pきみの ポケナビに エントリーコールが\nセットされた らしいな!\pならば わたしも とうろく しておこう!\pこれで きみと はなれていても\nすぐに ポケモンずかんの ひょうかを\lしてあげられる からね!\p…… …… ……$"

MatchCall_Text_RegisteredBirch:
	.string "{JPN}オダマキはかせを\nポケナビに とうろく した!$"

MatchCall_Text_UnusedProfBirch:
	.string "{JPN}オダマキ『ずかんと ポケナビが あれば\nポケモンの ちょうさも\lより いっそう たのしくなるな!$"

MatchCall_Text_MrStone1::
	.string "{JPN}ツワブキ『おっ! {PLAYER}{KUN}か?\pこうして わしを よびだした ってことは\nポケナビの ちょうしは よさそうだな!\pわしの ほかにも いろんな ひとが\nとうろく されて いくから どんどん\lよびだして はなしを すると いいぞ!\pけっこう! けっこう!\nうれしそうに しとる ようだな!\p……ん? なんで わかるのかって?\pそれは…… しゃちょうしつの まどから\nきみを みおろして いるからだよ!\pわははは! じゃあ またな!$"

MatchCall_Text_MrStone2::
	.string "{JPN}ツワブキ『おっ! {PLAYER}{KUN}か?\pどうした! わしが たのんだ しごと\nわすれちゃったの かな?\pまずは ムロタウンで ダイゴに\nてがみを わたしてくれ!\pそのあと カイナシティの クスノキくんに\nわがしゃの にもつを とどけるんだ!\pな? おぼえたかな?\nわしは いそがしい しゃちょう だからね\lこれで しつれい するよ!$"

MatchCall_Text_MrStone3::
	.string "{JPN}ツワブキ『おっ! {PLAYER}{KUN}!\pそうか ダイゴに あえたのか!\nよーし おれいに プレゼントを やろう!\pカナズミに くることが あったら\nわしの へやに よっていって おくれ!\pじゃあな まっとるぞ!$"

MatchCall_Text_MrStone4::
	.string "{JPN}ツワブキ『おお! {PLAYER}{KUN}!\pそうそう カナシダトンネルは\nわがしゃが ほって いたんだけどね\pあの あたりに せいそく している\nポケモンを ほご するために\lこうじは ちゅうし したんだよ\pまあ にんげんの べんりさ よりは\nポケモンが しずかに くらせる\lそのほうが だいじな ことだからね!$"

MatchCall_Text_MrStone5::
	.string "{JPN}ツワブキ『やあやあ {PLAYER}{KUN}!\pトウカシティの ひとから きいたんだけど\nきみは センリさんの こども なんだね\pどうりで たのもしいと おもったよ!$"

MatchCall_Text_MrStone6::
	.string "{JPN}ツワブキ『ええっ!\nきみは じぶんの おとうさんと\lポケモンしょうぶを して かったのかい?\pこりゃ びっくりだ!\nわしは すごい ひとと ともだちに\lなっちゃったんだなあ! わはは!$"

MatchCall_Text_MrStone7::
	.string "{JPN}もしもし!\nデボンコーポレーションで ございま……\lああ {PLAYER}さん ですね!\pしゃちょうは さっきまで いたんですけど\nいまは るすに してるんですよ!\pうちの しゃちょうも いそがしいけど\n{PLAYER}さんも いそがしそう ですね!$"

MatchCall_Text_MrStone8::
	.string "{JPN}……え ……なにかね?\pグラ…… はい? ……ドン?\pなんだか…… きこえな……\pザザザザザ…… …… ……$"

MatchCall_Text_MrStone9::
	.string "{JPN}……え ……なにかね?\pかいて…… はい? ……どうくつ?\pなんだか…… きこえな……\pザザザザザ…… …… ……$"

MatchCall_Text_MrStone10::
	.string "{JPN}ツワブキ『{PLAYER}{KUN}! わしだ!\pなんだか いろいろ あった らしいが\nいそがしい わしには\lなんの ことだか サッパリ わからん!\pとにかく キミは じぶんの しんじた\nみちを あゆんで いきたまえ!\pわしも カゲながら おうえん しとるぞ!\nじゃあな!$"

MatchCall_Text_MrStone11::
	.string "{JPN}ツワブキ『…… …… ……\nもしかして {PLAYER}{KUN} か?\pこえに じしんが みなぎっていて\nいっしゅん ちがうひとかと おもったぞ!\pうむ! たまには わがしゃにも\nあそびに きておくれ!$"
