gText_ObtainedTheItem::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_TheBagIsFull::
	.string "{JPN}バッグが いっぱいだ!$"

gText_PutItemInPocket::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}{STR_VAR_3}ポケットに しまった!$"

gText_PlayerFoundOneItem::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}みつけた!$"

gText_TooBadBagIsFull::
	.string "{JPN}ざんねん!\n"
	.string "{JPN}バッグが いっぱいだ……$"

gText_PlayerPutItemInBag::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}バッグに しまった!$"

gText_ObtainedTheDecor::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_NoRoomLeftForAnother::
	.string "{JPN}ざんねん! {STR_VAR_2}を\n"
	.string "{JPN}いれる ばしょが いっぱいだ……$"

gText_TheDecorWasTransferredToThePC::
	.string "{JPN}{STR_VAR_2}は\n"
	.string "{JPN}パソコンに てんそうされた!$"

gText_ObtainedTheItems::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}を てにいれた!$"

gText_PlayerFoundItems::
	.string "{JPN}{PLAYER}は {STR_VAR_1}と {STR_VAR_2}を みつけた!$"

gText_PutCoinsAwayInCoinCase::
	.string "{JPN}{PLAYER}は \n"
	.string "{JPN}コインケースに しまった!$"

gText_FoundXCoins::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}{STR_VAR_1}まい みつけた!$"

gText_FoundXItems::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n"
	.string "{JPN}{STR_VAR_1}こ みつけた$"

gText_CoinCaseIsFull::
	.string "{JPN}ざんねん!\n"
	.string "{JPN}コインケースが いっぱいだ……$"

gText_NothingToPutThemIn::
	.string "{JPN}ざんねん!\n"
	.string "{JPN}いれるものが ない……$"
