Text_BootUpPC:
	.string "{JPN}{PLAYER}は\n"
	.string "{JPN}パソコンの スイッチを いれた$"

gText_WhichPCShouldBeAccessed::
	.string "{JPN}どこの パソコンに せつぞく して\n"
	.string "{JPN}つうしん しますか?$"

gText_AccessedSomeonesPC::
	.string "{JPN}だれかの パソコンに せつぞく した!$"

gText_StorageSystemOpened::
	.string "{JPN}ポケモンの あずかり システムを\n"
	.string "{JPN}よびだした!$"

gText_AccessedPlayersPC::
	.string "{JPN}{PLAYER}の パソコンに せつぞくした!$"

gText_AccessedLanettesPC::
	.string "{JPN}マユミの パソコンに せつぞく した!$"

gText_AccessedBillsPC::
	.string "{JPN}マサキの パソコンに せつぞく した!$"
