gBirchDexRatingText_AreYouCurious::
	.string "{JPN}オダマキ『おお {PLAYER}{KUN}!\pポケモンずかんの ようすを\nみせて くれるのかい?$"

gBirchDexRatingText_Cancel::
	.string "{JPN}うん? みせるほど\nポケモンを つかまえて いないのか$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "{JPN}ふむふむ……\pみつけた ポケモン {STR_VAR_1}\nつかまえた ポケモン {STR_VAR_2} か……$"

gBirchDexRatingText_LessThan10::
	.string "{JPN}もっと くさむらに はいって\nポケモンを さがしてみると いいな!$"

gBirchDexRatingText_LessThan20::
	.string "{JPN}ちょうしが でてきた みたいだね\nでも これからが たいへん なんだぞ!$"

gBirchDexRatingText_LessThan30::
	.string "{JPN}きまった ばしょでしか みつからない\nポケモンは しつこく さがすしか ないぞ!$"

gBirchDexRatingText_LessThan40::
	.string "{JPN}ボリュームは まだまだ だけど\nすこしは ポケモンずかん らしく なったぞ$"

gBirchDexRatingText_LessThan50::
	.string "{JPN}なかなか いい かんじ だな!\nこの ちょうしで がんばって くれよ$"

gBirchDexRatingText_LessThan60::
	.string "{JPN}つりざおは つかって いるかな?\nうみにも ポケモンは たくさん いるからな$"

gBirchDexRatingText_LessThan70::
	.string "{JPN}ポケモンを つかまえる だけでなく\nしんか させるのは どうだい?$"

gBirchDexRatingText_LessThan80::
	.string "{JPN}すばらしい ポケモンずかんに なりそうだ\nそんな よかんが して たまらないね!$"

gBirchDexRatingText_LessThan90::
	.string "{JPN}ここまで あつめるとは……\nきみの さいのうは たいした ものだよ!$"

gBirchDexRatingText_LessThan100::
	.string "{JPN}サファリゾーンには いったかい?\nあそこでしか つかまえられない\lポケモンも いるって はなし だぞ!$"

gBirchDexRatingText_LessThan110::
	.string "{JPN}とうとう 100しゅるい こえたのか!\nポケモンずかん として みごとな もんだね!$"

gBirchDexRatingText_LessThan120::
	.string "{JPN}……そういえば いわくだきを つかうことで\nみつかる ポケモンも いたっけ$"

gBirchDexRatingText_LessThan130::
	.string "{JPN}ポケモンこうかん すれば\nもっと あつまるかも しれないな$"

gBirchDexRatingText_LessThan140::
	.string "{JPN}なんでも なついていると\nしんか する ポケモンも いるそうだよ!$"

gBirchDexRatingText_LessThan150::
	.string "{JPN}ホウエンちほう には こんなにも\nおおくの ポケモンが いたのか……$"

gBirchDexRatingText_LessThan160::
	.string "{JPN}ときどき たいりょうはっせい する\nポケモンが いるらしい\lその チャンスを のがさないようにな!$"

gBirchDexRatingText_LessThan170::
	.string "{JPN}きみの ずかんを みれば\nホウエンちほうの ポケモンの\lすべてが わかるようだ!$"

gBirchDexRatingText_LessThan180::
	.string "{JPN}きみは ポケモンはかせ としても\nゆうしゅう なんだな$"

gBirchDexRatingText_LessThan190::
	.string "{JPN}ここまで ずかんが できたら\nもはや プロフェッショナル だぞ!$"

gBirchDexRatingText_LessThan200::
	.string "{JPN}いよいよ かんせいに ちかづいた!\nそんな よかんが してきたよ!$"

gBirchDexRatingText_DexCompleted::
	.string "{JPN}おめでとう!!\nポケモンずかんの かんせい だよ!!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "{JPN}ふむふむ ぜんこくてき には……\pみつけた ポケモン {STR_VAR_1}\nつかまえた ポケモン {STR_VAR_2} だね$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKeDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKeDEX is:\p"
	.string "{STR_VAR_1} POKEMON seen and\n"
	.string "{STR_VAR_2} POKEMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKEMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKeDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKEMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKeDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKeDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKEMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess... You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKEMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKEMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKeDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKeDEX is:\p"
	.string "{STR_VAR_1} POKEMON seen and\n"
	.string "{STR_VAR_2} POKEMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKeDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally...\p"
	.string "You've finally completed the\n"
	.string "POKeDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKeDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see...$"
