SecretBase_Text_Trainer0Intro:
	.string "{JPN}きみは もう ひみつきちを つくったかい?\pぼくは あっち こっち まわって\nやっと この ばしょに きめたんだ!\pせっかく きたんだから\nポケモン しょうぶ しない?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "{JPN}それじゃ いくよ!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "{JPN}えっ いまは むりなんだ…$"

SecretBase_Text_Trainer0Defeated::
	.string "{JPN}うわっ きみって つよいなー\nぼくが まけたこと ひみつに してね!$"

SecretBase_Text_Trainer0PostBattle:
	.string "{JPN}ぼくの ひみつきち どうかなー\nまた あしたも あそびに きてね!$"

SecretBase_Text_Trainer0PreChampion:
	.string "{JPN}きみは もう ひみつきちを つくったかい?\pぼくは あっち こっち まわって\nやっと この ばしょに きめたんだ!\pゆっくり して いってね!$"

SecretBase_Text_Trainer5Intro:
	.string "{JPN}ひみつきちを つくれる ばしょは\nほかにも たくさん あるけど\lここが いちばん きにいったの!\pねっ! すてきでしょ!\pあっ もし よかったら\nポケモン しょうぶ しない?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "{JPN}それじゃ いくわよ!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "{JPN}そう いまは むりなのね…$"

SecretBase_Text_Trainer5Defeated::
	.string "{JPN}うーん わたしの まけね…\nわたしが まけたのは ないしょの ひみつね!$"

SecretBase_Text_Trainer5PostBattle:
	.string "{JPN}このちかくに くることが あったら\nまた あそびに よってね!$"

SecretBase_Text_Trainer5PreChampion:
	.string "{JPN}ひみつきちを つくれる ばしょは\nほかにも たくさん あるけど\lここが いちばん きにいったの!\pねっ! すてきでしょ!$"

SecretBase_Text_Trainer1Intro:
	.string "{JPN}この ばしょは にんきが あるから\nいつも うまって いるんだー\pあっ もしかして\nきみも ここを つかいたい?\pうーん ぼくに かてたら\nこのばしょ あげても いいよ!$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "{JPN}よしっ! ぼくの きちを まもるぞー!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "{JPN}えっ この ばしょに きょうみが ないの?\nそっかー$"

SecretBase_Text_Trainer1Defeated::
	.string "{JPN}もう ダメだ!\nこうさーん!$"

SecretBase_Text_Trainer1PostBattle:
	.string "{JPN}よしっ ぼくが いつか ひっこしたら\nこの ばしょは きみの ものさ!$"

SecretBase_Text_Trainer1PreChampion:
	.string "{JPN}この ばしょは にんきが あるから\nいつも うまって いるんだよー\pぼくは ずっと まっていて\nやっと つかえる ように なったんだ!$"

SecretBase_Text_Trainer6Intro:
	.string "{JPN}わたしの ポケモン けんきゅうじょへ\nようこそ!\pここで ポケモン しょうぶに ついて\nこっそり べんきょう してるのよ\pどう わたしの じつりょく みてみる?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "{JPN}ほんきで いくわよ!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "{JPN}それじゃ また こんどね!$"

SecretBase_Text_Trainer6Defeated::
	.string "{JPN}うーん わたしも まだまだねー\nもっと  べんきょう しないと!$"

SecretBase_Text_Trainer6PostBattle:
	.string "{JPN}しょうぶ してくれて どうも ありがとう!\nまた あしたも きてねー$"

SecretBase_Text_Trainer6PreChampion:
	.string "{JPN}わたしの ポケモン けんきゅうじょへ\nようこそ!\pここで ポケモン しょうぶに ついて\nこっそり べんきょう してるのよ$"

SecretBase_Text_Trainer2Intro:
	.string "{JPN}おおきな いえも いいけど\nぼくは こういう ばしょが すきなんだ\pだって いろいろな ひとが\nあそびに きてくれる からねー!\pどう ポケモン しょうぶでも するかい?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "{JPN}そう こなくっちゃ!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "{JPN}よういが できたら\nいつでも こえを かけてね!$"

SecretBase_Text_Trainer2Defeated::
	.string "{JPN}やられたー!\nだけど ポケモン しょうぶは たのしいー!$"

SecretBase_Text_Trainer2PostBattle:
	.string "{JPN}さてと グッズでも かいに いこうかな\pぼくの ひみつきちを\nみんなに たのしんで ほしい からね!$"

SecretBase_Text_Trainer2PreChampion:
	.string "{JPN}おおきな いえも いいけど\nぼくは こういう ばしょが すきなんだ\pだって いろいろな ひとが\nあそびに きてくれる からねー!$"

SecretBase_Text_Trainer7Intro:
	.string "{JPN}わたし グッズの おかいものが\nだいすき です!\pそれと おなじくらい ポケモンを そだてるの\nだいすき です!\pもし よかったら わたしの ポケモンちゃんと\nしょうぶして くれますか?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "{JPN}それでは おねがいします$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "{JPN}そう それは ざんねん です…$"

SecretBase_Text_Trainer7Defeated::
	.string "{JPN}まいりました……$"

SecretBase_Text_Trainer7PostBattle:
	.string "{JPN}ああ たのしかった!\nつぎは おかいものを たのしもう かしら$"

SecretBase_Text_Trainer7PreChampion:
	.string "{JPN}わたし グッズの おかいものが\nだいすき です\pそれと おなじくらい ポケモンを そだてるの\nだいすき です$"

SecretBase_Text_Trainer3Intro:
	.string "{JPN}みつかり にくい ばしょに\nひみつきちを つくる ひとが いるけど\lこっそりと かくれて いたいのかなぁ……\pうん せっかく みつけて くれたんだから\nポケモン しょうぶ しようか?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "{JPN}かんたんには おわらせ ないよ!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "{JPN}もしかして さがすのに つかれちゃった?$"

SecretBase_Text_Trainer3Defeated::
	.string "{JPN}おわっちゃった……$"

SecretBase_Text_Trainer3PostBattle:
	.string "{JPN}きみの ひみつきちは どこなんだい!\nこんど あそびに いこうかなー$"

SecretBase_Text_Trainer3PreChampion:
	.string "{JPN}みつかり にくい ばしょに\nひみつきちを つくる ひとが いるけど\lこっそりと かくれて いたいのかなぁ$"

SecretBase_Text_Trainer8Intro:
	.string "{JPN}グッズを てにいれる ほうほうは\nいろいろ あるって はなしよ\pどっちが すてきな グッズを\nてにいれるか きょうそうね!\pついでに ポケモン しょうぶも しない?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "{JPN}じぶんの ひみつきちで まけられないわ!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "{JPN}いつでも しょうぶ まってるわ!$"

SecretBase_Text_Trainer8Defeated::
	.string "{JPN}えっ もしかして わたしの まけ?$"

SecretBase_Text_Trainer8PostBattle:
	.string "{JPN}グッズあつめ まけないわよ!\nまた あそびに きてね!$"

SecretBase_Text_Trainer8PreChampion:
	.string "{JPN}グッズを てにいれる ほうほうは\nいろいろ あるって はなしよ\pどっちが すてきな グッズを\nてにいれるか きょうそうね!$"

SecretBase_Text_Trainer4Intro:
	.string "{JPN}すきな ばしょを さがして\nすきな グッズを おく!\pすきな ポケモンを そだてて\nぼくも いっしょに つよくなる\pそんな ぼくと しょうぶ しよう!$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "{JPN}きみの じつりょくを みせてくれ!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "{JPN}まぁ そんな ときも あるよね!$"

SecretBase_Text_Trainer4Defeated::
	.string "{JPN}きみの じつりょくは じゅうぶん わかった!$"

SecretBase_Text_Trainer4PostBattle:
	.string "{JPN}きみも ぼくも もっと つよく なれる!\nおたがいに がんばろうね!$"

SecretBase_Text_Trainer4PreChampion:
	.string "{JPN}すきな ばしょを さがして\nすきな ものを おく!\pすきな ポケモンを そだてて\nぼくも いっしょに つよくなる\pまいにち たのしいねー$"

SecretBase_Text_Trainer9Intro:
	.string "{JPN}グッズの しゅるいや おきかたを みれば\nそのひとが どんな センスの もちぬしか\lよーく わかるわね!\pわたしの センスは どうかしら?\nうふふっ なにも いえないって かんじね!\pしょうぶの センスも ためして みる?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "{JPN}おもいっきり いくわよ!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "{JPN}いつでも わたしの センスを みせるわよ!$"

SecretBase_Text_Trainer9Defeated::
	.string "{JPN}すごい さいのうね!\nそこしれぬ つよさを かんじたわ……$"

SecretBase_Text_Trainer9PostBattle:
	.string "{JPN}わたしの センス どうだった?\nもっと センスを みがくわよー$"

SecretBase_Text_Trainer9PreChampion:
	.string "{JPN}グッズの しゅるいや おきかたを みれば\nそのひとが どんな センスの もちぬしか\lよーく わかるわね!\pわたしの センスは どうかしら?\nうふふっ なにも いえないって かんじね!$"
