gTVBravoTrainerText00::
	.string "{JPN}イヤー!\n『ブラボー トレーナー』の じかんだ!\pきょうは {STR_VAR_3}クラスの\n{STR_VAR_2}を ほこる\l{STR_VAR_1}さんの ポケモン!$"

gTVBravoTrainerText01::
	.string "{JPN}{STR_VAR_1} の 「{STR_VAR_2}」の\nしょうかいだー!\p「{STR_VAR_2}」か……\pもう ニックネーム からして\n{STR_VAR_3}が にじみ でているぜ!$"

gTVBravoTrainerText02::
	.string "{JPN}さーて この {STR_VAR_1}さんが\nポケモンコンテストに さんか したとき\pじぶんの ポケモンに ついて\nあつく はなして くれたぞ!$"

gTVBravoTrainerText03::
	.string "{JPN}コンテストを したあとの\nかんそうを きくと\lすごく うれしそうに\p「{STR_VAR_2}」って\nこたえて くれたぞ!\pまあ コンテストでは\n{STR_VAR_3}ばん でした からねー!\pいまの {STR_VAR_1}さんには\nぴったりの セリフだよ まったく!$"

gTVBravoTrainerText04::
	.string "{JPN}コンテストを したあとの\nかんそうを きくと\lびみょうに くやしがり ながら\p「{STR_VAR_2}」って\nこたえて くれたぞ!\pまあ コンテストでは\n{STR_VAR_3}ばん でした からねー!\pこの ことばに {STR_VAR_1}さんの\nくやしさが みえかくれ するねー$"

gTVBravoTrainerText05::
	.string "{JPN}ところで {STR_VAR_1}さんの めざしてる\n{STR_VAR_2}って いったい なんだろう?\lきいて みたいねー!\pもちろん きいて きました!\pそれは つぎの ひとことに\nすべてが つまって います!\pそれは 「{STR_VAR_3}!」\pそれこそ {STR_VAR_1}さんの\n{STR_VAR_2}の すべて なんです!$"

gTVBravoTrainerText06::
	.string "{JPN}さいごに {STR_VAR_1}が\nつかった {STR_VAR_2}も\lすべて 「{STR_VAR_3}」 なんです!$"

gTVBravoTrainerText07::
	.string "{JPN}ブラボー! {STR_VAR_1}\nブラボー!! {STR_VAR_2}\pこんごの {STR_VAR_1}さんの かつやくに\nきたい したいねー!\pそれじゃあ また じかいの\nほうそうで あいましょー!$"

gTVBravoTrainerText08::
	.string "{JPN}{STR_VAR_1} の しょうかいだー!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "{JPN}あ! いま たたかっていた\nトレーナーの かたですね!\pわたし いま いろんな トレーナーの\nはなしを きいて まわってるんだけど\pたたかいおわった かんそうを\nすこしだけ きかせて もらえませんか?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "{JPN}ほんと!?\nありがとう!\lえっと それじゃあねぇ……\pこんかいの バトルタワーの\nたいせんは どうでしたか\pまんぞく でしたか!\nそれとも ふまん ですか!?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "{JPN}あぁ!\nごめんなさい\pじゃあ またこんど バトルタワーに きたら\nきかせて くださいね$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "{JPN}さっすが!\pその まんぞくした かおを みれば\nどんなに いいしあいだったか\lわかりますよ!$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "{JPN}うーん そうですか……\pおもいどおりに しょうぶを するのって\nなかなか むずかしい ですからね……$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "{JPN}あぁっ あと\nもう ひとつだけ いいですか?\pこの たたかいの かんそうを\nひとことで ビシッと きかせてください!$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "{JPN}かっこいー!!\pいい きめゼリフ ですね\nつぎの たたかいも きたい してますよ\pそれでは また!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "{JPN}そうですか……\pでも なにも いわないのも\nまた かっこいいですね!\pそれじゃあ またの きかいに\nかんそうを きかせて ください!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "{JPN}つぎの たたかいも\nきたい してますよ$"

BravoTrainerBattleTower_Text_Intro::
	.string "{JPN}イヤー!\n『ブラボー トレーナー』の じかんだ!\pきょうは バトルタワーに ちょうせんした\n{STR_VAR_1}さんの しょうかいだー!\p{STR_VAR_1}さんは {STR_VAR_2}を\nつかった たたかいをして$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "{JPN}なんと {STR_VAR_1}の へやで\n{STR_VAR_2}れんしょう という\lきろくを うちたてたぞ!$"

BravoTrainerBattleTower_Text_Lost::
	.string "{JPN}おしくも {STR_VAR_2}にんめで たたかった\n{STR_VAR_1}さんに まけて しまいました\lうーん! ざんねんだねぇ\pでも こんなはじめに {STR_VAR_1}さんに\nあたるとは うんがないとしか いえないよ\pさて その {STR_VAR_1}さんとの\nしょうぶの かんそうを きいたところ$"

BravoTrainerBattleTower_Text_Won::
	.string "{JPN}さいごには {STR_VAR_1}さんの\n{STR_VAR_2}を みごとに たおして\lしょうり したんですねぇ\pいや {STR_VAR_1}さんに かつなんて\nすごいとしか いいようがないよ まったく\pさて そのしょうりを つかんだ\nしゅんかんの かんそうを きいたところ$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "{JPN}しかし さいごに とうじょうした\n{STR_VAR_1}さんの {STR_VAR_2}に\lついに まけて しまったんですねぇ\pまあ 「{STR_VAR_1}の {STR_VAR_2}」\nといえば ゆうめいな コンビ ですからね\p……さて その ゆうめいじんとの\nしょうぶの かんそうを きいたところ$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "{JPN}まんぞく した!!\pと すがすがしく こたえてくれたよ\nさすがだぜ!\pまんぞくいく たたかいが できるなんて\nほんと すごいよねぇ まったく!\pその まんぞくかんは つぎの ひとことを\nきいたとき すべて わかったよ$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "{JPN}ふまんだった……\pと びみょうに おちこみながら\nこたえて くれたよ\p……まあ まんぞくいく たたかいって\nなかなかできる もんじゃないからねー\pそのときの くやしさは\nつぎの ひとことが よくあらわしてるよ$"

BravoTrainerBattleTower_Text_None1::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_None2::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_None3::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_None4::
	.string "{JPN}なし$"

BravoTrainerBattleTower_Text_Response::
	.string "{JPN}その ことばは\n「{STR_VAR_1}!」$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "{JPN}「{STR_VAR_1}!」\nうーん  いい ことばだねぇ!!\p{STR_VAR_2}さんの うれしさを\nこのことばが よく あらわしているよ!\pたしかに {STR_VAR_3}さんとの たたかいは\nまさに 「{STR_VAR_1}」 という\lかんじ だったからねぇ!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "{JPN}「{STR_VAR_1}!」\nなるほどねぇ\pたしかに {STR_VAR_3}さんとの たたかいは\n「{STR_VAR_1}」 としか いいようがない\lたたかい でしたからねぇ\p{STR_VAR_2}さんの くやしさが\nよく つたわってくるよ! くー!$"

BravoTrainerBattleTower_Text_Outro::
	.string "{JPN}ブラボー! {STR_VAR_1}\nブラボー!! {STR_VAR_2}\pこんごの {STR_VAR_1}さんの かつやくに\nきたい したいねぇ!\pそれじゃあ また じかいの\nほうそうで あいましょー!$"

gTVFanClubOpinionsText00::
	.string "{JPN}『ぼくたち!\nポケモン だいすきクラブ!』\pはい はじまりました!\pこのばんぐみは みなさんの\nいけんを このわたしが\lかわりに さけんで しまおう!\lという すごい ばんぐみ!!\pさて きょうは ポケモンだいすきクラブ に\nいって いろんな はなしを きいてきた\lリポーターからの じょうほうだ!\pさて きょうの\nポケモンだいすき にんげんは?\pんー……\p{STR_VAR_1}さんだー!!\pそれでは ごじぶんの ポケモン\p{STR_VAR_2}の 「{STR_VAR_3}」に\nついての あつい きもちを\pかわりに この わたくしが テレビに\nむかって さけんで あげましょう!\pうー!!\pレッツ シャウト!!!$"

gTVFanClubOpinionsText01::
	.string "{JPN}さて {STR_VAR_1}さんが はじめて\n{STR_VAR_2}と あったとき ちょっかんてきに\lおもった ことは……\l……\p「{STR_VAR_3}!!」\pんー いい さけびだ!\pまるで そのときの おもいでが\nよみがえる ようだー!!$"

gTVFanClubOpinionsText02::
	.string "{JPN}さて {STR_VAR_1}さんの だいすきな\n{STR_VAR_2}を なにかに たとえると したら\l……\p「{STR_VAR_3}!!」\pんー すごい はっそうだ!!\pはげしい {STR_VAR_2}への おもいこみが\nかんじられるねー!$"

gTVFanClubOpinionsText03::
	.string "{JPN}さて {STR_VAR_1}さんが {STR_VAR_2}に\nひかれた りゆうは……\l……\p「{STR_VAR_3}!!」\pおー!! すんばらしい いけんだー!\p{STR_VAR_2}を どんなに すきか\nビンビン つたわって くるねー!$"

gTVFanClubOpinionsText04::
	.string "{JPN}んー? まだ つづきが ありますねー\nよんで みましょう!\pえーと……\p{STR_VAR_1}さんに とって ポケモンを\nひとことで たとえると すれば それは!\l……\p「{STR_VAR_3}!!」\pブラボー!!\pいままでの なかで いちばん\nいい さけび だったー!\p「{STR_VAR_3}!!」\pなんども さけびたくなる ことばだねー!\pそれでは いいさけびと であった ところで\nまた じかい おあいしましょう!\pさいごに もういちど\nみんなで さけびましょう!\p「{STR_VAR_3}!!」$"

gTVFanClubText00::
	.string "{JPN}『ぼくたち!\nポケモン だいすきクラブ!』\pはい はじまりました!\pじゃあ きょうは ポケモンアンケートの\nコーナーから!\pかずある ポケモンと トレーナーの\nはなしの なかから\pきょうは どんな はなしが\nとびだして くるのでしょうか!?\lさて きょうの はなしは?\pんー……\pこれだ!\pでは てがみの しょうかい から!!\p{STR_VAR_2}の ことに ついて\n{STR_VAR_1}さん からの おてがみだー\pでは どれだけ {STR_VAR_2}への\nあつい いけんが かいてあるか\lよませて もらいましょう!\lえーと……$"

gTVFanClubText01::
	.string "{JPN}おー!!\nなんて すばらしい てがみなんだ!!$"

gTVFanClubText02::
	.string "{JPN}きにいったから もういちど!$"

gTVFanClubText03::
	.string "{JPN}いい てがみは\nなんど きいても いいねー!!$"

gTVFanClubText04::
	.string "{JPN}「{STR_VAR_3}」 っていう ことばの\nおかげで グッと こころに つたわってくる\lいい てがみに なっているねー!!$"

gTVFanClubText05::
	.string "{JPN}とくに「{STR_VAR_3}」って ところ!\p「{STR_VAR_3}」っていう ところが\nきにいったぞー!$"

gTVFanClubText06::
	.string "{JPN}ところで あんまり かんけい ないけど\n「{STR_VAR_3}」って いいことば だよね\pじつは おれも 「{STR_VAR_3}」って\nことば さいきん よく つかうんだよね$"

gTVFanClubText07::
	.string "{JPN}このてがみ じぶんてきには\n{STR_VAR_3}てん ていう かんじかなー!\pつぎは もっと いい てがみを\nきたい してるよ! {STR_VAR_1}さん!!\pおっと もう こんなじかんだ!\nそれでは また じかい\lみなさま おあい しましょう!!$"

gTVRecentHappeningsText00::
	.string "{JPN}『さいきんの できごと』\pポケモントレーナーに とって\nまいにちが ものがたりです\lその ものがたりを すこしでも\lしょうかい できたら うれしいですね\pさて きょうは トレーナーの\n{STR_VAR_1}さんの おはなしです\p{STR_VAR_1}さん さいきん\nどんなことが あったんで しょうか?\lさっそく みてみることに しましょう\pえーと……$"

gTVRecentHappeningsText01::
	.string "{JPN}なるほど {STR_VAR_1}さんの\nまわりで さいきん おきている ことが\lてに とるように わかりますね$"

gTVRecentHappeningsText02::
	.string "{JPN}「{STR_VAR_3}」という ことばが\nおはなしに ストーリーを かんじさせますね$"

gTVRecentHappeningsText03::
	.string "{JPN}「{STR_VAR_3}」という ことばの\nおかげで まるで じょうけいが\lうかんで くるようですね$"

gTVRecentHappeningsText04::
	.string "{JPN}このおはなしは 「{STR_VAR_3}」という\nぶぶんが とても いんしょうてき ですね$"

gTVRecentHappeningsText05::
	.string "{JPN}{STR_VAR_1}さんは とても いい\nおはなしを きかせて くれましたね\pこれで あなたの こころにも\n{STR_VAR_1}さん という ストーリーが\lきざみ こまれましたよ\pそれでは また じかいの\nほうそうで おあいしましょう$"

gTVMassOutbreakText00::
	.string "{JPN}こんにちは\n『ポケモン ニュース』の じかんです\pたいへん めずらしい ニュースが\nはいって きました\p{STR_VAR_1}で\n{STR_VAR_2}が たいりょうはっせい した\lという ほうこくが ありました!\p{STR_VAR_2}と いえば\nなかなか みつけることが むずかしい\lポケモンとしても ゆうめい ですね\pあなたも このしんぴてきな\n{STR_VAR_2}の たいりょうはっせいを\lみにいっては いかが でしょうか?\pいじょう\n『ポケモン ニュース』でした$"

gTV3CheersForPokeblocksText00::
	.string "{JPN}しかい『ごきげん いかがですか?\n『ポロック バンザイ!』の おじかんです\pきょうの ポロックは\n{STR_VAR_1}さんと その おなかまが\lブレンドした ポロックです\pさっそく わたしの グルメな ポケモン\nゴクリンちゃんに たべさせて みましょう!\p…… …… …… ……\n…… …… …… ……$"

gTV3CheersForPokeblocksText01::
	.string "{JPN}ゴクリン『グビィ! グビィ!\pしかい『おお! とっても {STR_VAR_1}くて\n「{STR_VAR_2}!」と いってますね\pきっと これは {STR_VAR_3}さんが\nがんばって まわした おかげですね!\p{STR_VAR_3}さん!\nごちそうさま でした!$"

gTV3CheersForPokeblocksText02::
	.string "{JPN}こんかい いまいち だった\n{STR_VAR_1}さんが\lもっと じょうずに まわすことが できれば\lさらに おいしく なるかも しれませんよ!$"

gTV3CheersForPokeblocksText03::
	.string "{JPN}ゴクリン『グビィ! グビィ!\pしかい『うーん…… ちょっと {STR_VAR_1}すぎて\n「{STR_VAR_2}!」と いってますね……\pやっぱり {STR_VAR_3}さんの しっぱいが\nいたかった ですね……$"

gTV3CheersForPokeblocksText04::
	.string "{JPN}こんかい いちばん がんばっていた\n{STR_VAR_1}さんが かわいそうです……\p……{STR_VAR_2}さん!\nつぎは がんばって ください!$"

gTV3CheersForPokeblocksText05::
	.string "{JPN}では また おあいしましょう!\nあいことばは 『ポロック バンザイ!』$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "{JPN}やあ!\pボク {STR_VAR_1}の ファン なんだけど\n{STR_VAR_1} って どう おもう?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "{JPN}なるほどねー\nそんな ふうに おもっているんだね!$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "{JPN}{STR_VAR_1}の こと\nわすれちゃったの……?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "{JPN}ボク {STR_VAR_1}の ファン なんだけど\n{STR_VAR_1} って どうおもう?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "{JPN}じゃあ こんどは\n{STR_VAR_1}の つよさを\lてんすうで おしえてくれる?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "{JPN}{STR_VAR_1}の こと\nわすれちゃったの……?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "{JPN}そっか!\nこんど {STR_VAR_1}に あってみてよ!\lきみも きっと ファンに なっちゃうよ!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "{JPN}そうなんだー!\pありがとう!\nとっても さんこうに なったよ!\pさっそく {STR_VAR_1}の ファン みんなで\nこの ことに ついて はなしあって みるよ!$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "{JPN}もうすぐ {STR_VAR_1}に ついての\nテレビ ばんぐみが ほうそう されるんだ!\pきみも ぜひ みてね!$"

gTVTrainerFanClubSpecialText00::
	.string "{JPN}『トレーナー ファンクラブ\n {STR_VAR_1} スペシャル!』\pホウエン かくちに いらっしゃる\n{STR_VAR_1}ファンの みなさま\lおまたせしました!\pきょうは {STR_VAR_1}さんが\n「どのように おもわれているか?」を\lいっしょに かんがえて いきましょう!\pほかの トレーナーさんを だいひょうして\n{STR_VAR_2}さん から ごいけんを\lいただきました!\pまず {STR_VAR_1}さんを\nひとことで いい あらわすと……\p「{STR_VAR_3}」\pさすが {STR_VAR_2}さん!\nよく みて いらっしゃいますね!\p「{STR_VAR_3} {STR_VAR_1}!」\nいいですねー\pつづいて {STR_VAR_1}さんの つよさに\nてんすうを つけると……$"

gTVTrainerFanClubSpecialText01::
	.string "{JPN}「{STR_VAR_3}てん!」\pすごい こうとくてん ですね\n{STR_VAR_2}さんは {STR_VAR_1}さんを\lとっても そんけい していますね$"

gTVTrainerFanClubSpecialText02::
	.string "{JPN}「{STR_VAR_3}てん!」\pいい てんすう ですね\n{STR_VAR_2}さんは {STR_VAR_1}さんを\lライバル として みていますね$"

gTVTrainerFanClubSpecialText03::
	.string "{JPN}「{STR_VAR_3}てん!」\pちょっと いまいち ですね\n{STR_VAR_2}さんは {STR_VAR_1}さんを\lじぶんの こぶん として みていますね$"

gTVTrainerFanClubSpecialText04::
	.string "{JPN}「{STR_VAR_3}てん!」\pひどい てんすう ですね\n{STR_VAR_2}さんは {STR_VAR_1}さんを\lしたっぱ として みていますね$"

gTVTrainerFanClubSpecialText05::
	.string "{JPN}いやー なるほど!\p{STR_VAR_1}さんに ついて\nあたらしい はっけんが ありましたね!\pでは さいごに {STR_VAR_2}さんの\nことばで おわかれ しましょう!\p{STR_VAR_1} {STR_VAR_3}!$"

gTVNameRaterText00::
	.string "{JPN}『せいめい はんだん』の\nじかんが やって まいりました\pあなたの つけた ニックネームから\nポケモンの ことを\lうらなって さしあげます\pすこしでも アドバイスに\nなれば よいと おもいますな\pきょうは {STR_VAR_1}さんの ポケモン\n{STR_VAR_2}の 「{STR_VAR_3}」の\lニックネームを うらなって みますかな\pふむふむ……\pうーむ\nこの ニックネームは……$"

gTVNameRaterText01::
	.string "{JPN}いろいろな ところで さいのうを\nはっき できる ニックネーム ですなぁ!\pこんご いろいろな ことに\nチャレンジ すると よいと おもいますよ$"

gTVNameRaterText02::
	.string "{JPN}{STR_VAR_1}さん との あいしょうが\nとても よい ニックネーム ですなぁ!\pいきの ぴったり あった\nよい コンビに なると おもいますよ$"

gTVNameRaterText03::
	.string "{JPN}とても こせいてきな ポケモンに\nなる ニックネーム ですなぁ!\pきちんと そだてて やれば その こせいが\nおおきく はな ひらくと おもいますよ$"

gTVNameRaterText04::
	.string "{JPN}とても おもいやりの ある\nポケモンに なる ニックネーム ですなぁ!\pきちんと そだてて やれば\nそれに こたえて くれると おもいますよ$"

gTVNameRaterText05::
	.string "{JPN}しょうらい おおものに なる\nとても よい ニックネーム ですなぁ!\pしょうらいが とても\nたのしみな ポケモン ですな$"

gTVNameRaterText06::
	.string "{JPN}とても けんこうてきな ポケモンに\nなる よい ニックネーム ですなぁ!\pいつまでも げんきで\nいて くれる でしょう$"

gTVNameRaterText07::
	.string "{JPN}とても かつどうてきな ポケモンに\nなる よい ニックネーム ですなぁ!\pポケモンしょうぶ では\nおおいに かつやく すると おもいますよ$"

gTVNameRaterText08::
	.string "{JPN}とても あいきょうの ある\nポケモンになる ニックネーム ですなぁ!\pポケモンコンテスト では\nとても かつやく できると おもいますよ$"

gTVNameRaterText09::
	.string "{JPN}この 「{STR_VAR_1}」という ニックネームは\n「{STR_VAR_3}」の もじを ちゅうしん として\lこれに 「{STR_VAR_2}」が つくことで\pどっしり とした\nよい ニックネームに なっていますな$"

gTVNameRaterText10::
	.string "{JPN}この 「{STR_VAR_1}」という ニックネームは\nとても かたちの よい\lニックネーム ですなぁ\pニックネームに 「{STR_VAR_2}」と 「{STR_VAR_3}」が\nはいって いるのが とても よい!$"

gTVNameRaterText11::
	.string "{JPN}この 「{STR_VAR_1}」という ニックネームは\nとても ながれの よい\lニックネーム ですなぁ\p「{STR_VAR_2}」の もじの あとに\n「{STR_VAR_3}」がくる ながれが とても よい!$"

gTVNameRaterText12::
	.string "{JPN}……さて そのほかに\nよい ニックネームの れい として$"

gTVNameRaterText13::
	.string "{JPN}トレーナーの {STR_VAR_1}さんの\nなまえを もってきて\p「{STR_VAR_2}{STR_VAR_3}」と いうのも\nとても よい ニックネーム ですなぁ$"

gTVNameRaterText14::
	.string "{JPN}もしくは 「{STR_VAR_2}{STR_VAR_3}」と\nいうのも よい ニックネーム ですな$"

gTVNameRaterText15::
	.string "{JPN}もとの ポケモンの なまえ\n{STR_VAR_2}から すこし もらって\p「{STR_VAR_1}{STR_VAR_3}」や$"

gTVNameRaterText16::
	.string "{JPN}「{STR_VAR_1}{STR_VAR_3}」と いうのも\nよい ニックネーム ですなぁ$"

gTVNameRaterText17::
	.string "{JPN}まちがっても ほかの ポケモンの なまえ\nたとえば {STR_VAR_2}の なまえを つけて\p「{STR_VAR_1}{STR_VAR_3}」の ような\nニックネームに しては いけませんな$"

gTVNameRaterText18::
	.string "{JPN}うむ それにしても 「{STR_VAR_1}」は\nなかなか よい ニックネーム ですな\pこれからも 「{STR_VAR_1}」の ことを\nたいせつに して ほしい ものですなぁ\pそれでは また\nごえんが あれば$"

gTVPokemonAnglerText00::
	.string "{JPN}『{STR_VAR_2}を つる』\pアナウンサー「こんにちは! きょうは\n{STR_VAR_2}つりを おそわりに きました\pさて せんせい {STR_VAR_2}を つるには\nどんな コツが いるのですか?\pせんせい「ん?\n{STR_VAR_2}を つる コツかい\lそれはね じーっと まつことだね\pほら あそこにいる {STR_VAR_1}さん\nなんて いい みほん じゃないか?\pもう かれこれ……\n{STR_VAR_3}かいは にげられて いるけど\pあきらめず じーっと まちつづけて いるよ\nあれが {STR_VAR_2}つりの ごくいだね\pアナウンサー「なるほど……\pあ! {STR_VAR_1}さん\nやっと {STR_VAR_2}を つりました!\lなきそうな かおして よろこんで ますよ!\p…わたしも あんな うれしそうな\nかおを みたら つりをしたく なりました!\pみなさんも これを きに {STR_VAR_2}つりを\nしてみては いかがですか?\pそれでは また じかいの\nほうそうで あいましょう$"

gTVPokemonAnglerText01::
	.string "{JPN}『{STR_VAR_2}を つる』\pインタビュアー『こんにちは! きょうは\n{STR_VAR_2}つりを おそわりに きました\pさて せんせい {STR_VAR_2}を つるには\nどんな コツが いるのですか?\pせんせい『ん?\n{STR_VAR_2}を つる コツかい\lそれはね つりざおを あらしの ごとく\nあつかう ことだね!\pほら あそこにいる {STR_VAR_1}さんの\nつりざお さばきを みてみなさい!\pもう {STR_VAR_3}ひきは れんぞくで\nつって いるぞ!\pインタビュアー『すっ すごい!\nまさに あらしの ようね……\p……あんなに すごい わざを みたら\nわたしも つりを したくなって きました!\pみなさんも これを きに {STR_VAR_2}つりを\nしてみては いかがですか?\pそれでは また じかいの\nほうそうで あいましょう$"

gTVPokemonTodayFailedText00::
	.string "{JPN}こんにちはー!\p『きょうの ポケモン』の\nじかんだよー!!\pおねえさん『こんにちは みんな げんき!\nきょうは {STR_VAR_1}さんの ポケモン\l{STR_VAR_2}の しょうかいを するよ!\pおにいさん『するぞー!$"

gTVPokemonTodayFailedText01::
	.string "{JPN}あ!\n{STR_VAR_1}さん といえば……\pおねえさん このまえ\nぼく みちゃった!!\pおねえさん『みちゃった って\nなにを みちゃったの?\pおにいさん『このまえ\n{STR_VAR_2}に でかけたとき\l{STR_VAR_1}さんを みかけたんだ\pちょうど {STR_VAR_3}を つかまえてる\nところ だったん だけど……$"

gTVPokemonTodayFailedText02::
	.string "{JPN}とちゅうで ポケモンに\nにげられ ちゃったんだよ!!\pボールを {STR_VAR_2}こも なげたのに\nぜんぶ むだ……\pポケモンに にげられた ときの\n{STR_VAR_1}さんの くやしがった かお\lすごかったなぁ……$"

gTVPokemonTodayFailedText03::
	.string "{JPN}とちゅうで まちがって ポケモンを\nたおし ちゃったんだよ!!\pボールを {STR_VAR_2}こも なげたのに\nぜんぶ むだ……\pポケモンを たおしちゃった ときの\n{STR_VAR_1}さんの あぜんと した かお\lなんとも いえなかったなぁ……$"

gTVPokemonTodayFailedText04::
	.string "{JPN}おねえさん『こらこらっ!\nたにんの ふこうを わらっちゃ だめだよ\pあぁ {STR_VAR_1}さん\nとっても かわいそう……\pおにいさん『はーい!\nわらって すいませーん$"

gTVPokemonTodayFailedText05::
	.string "{JPN}おねえさん『プッ!\pおにいさん『あ! いま\nわらったでしょ!?\pおねえさん『え!?\pわらってない\nわらってないよ!\pあぁ {STR_VAR_1}さん\nとっても かわいそう……\pおにいさん『……$"

gTVPokemonTodayFailedText06::
	.string "{JPN}おねえさん『じゃあ きを とりなおして\nポケモンの しょうかいを……\pえ?\nもう じかんが ない?\pもう! ポケモンの しょうかいが\nできなかった じゃない!\pおにいさん『また じかい あおうぜ!\pおねえさん『かってに しめるなー!!$"

gTVPokemonTodaySuccessfulText00::
	.string "{JPN}こんにちはー!\p『きょうの ポケモン』の\nじかんだよー!!\pおねえさん『こんにちは みんな げんき!\nきょうは {STR_VAR_1}さんの ポケモン\l{STR_VAR_2}の しょうかいを するよ!\pおにいさん『するぞー!$"

gTVPokemonTodaySuccessfulText01::
	.string "{JPN}おねえさん『{STR_VAR_1}さんは\n{STR_VAR_2}に 「{STR_VAR_3}」って\pニックネームを つけて たいせつに\nそだてて るんだって!$"

gTVPokemonTodaySuccessfulText02::
	.string "{JPN}おにいさん『ちなみに\nボールを ぜんぶで {STR_VAR_3}こ なげて\pさいごは {STR_VAR_2}で\nつかまえたって うわさだよ!$"

gTVPokemonTodaySuccessfulText03::
	.string "{JPN}おねえさん『そんなに かんたんに\nつかまえる なんて\p{STR_VAR_1}さんと {STR_VAR_2}の\nであいは きっと うんめい だったのよ!$"

gTVPokemonTodaySuccessfulText04::
	.string "{JPN}おねえさん『くろうして やっと\nつかまえた ポケモンは\lだいじに されるって いうしね!$"

gTVPokemonTodaySuccessfulText05::
	.string "{JPN}おねえさん『{STR_VAR_1}さんの\n{STR_VAR_2}は だいじな マスターボールを\pつかって やっと つかまえた\nおもいでの ポケモン なんだって!\pおにいさん『えー! すごいねー!\pおねえさん『{STR_VAR_1}さん ほんとうに\n{STR_VAR_2}を つかまえ たかったんだね!$"

gTVPokemonTodaySuccessfulText06::
	.string "{JPN}おにいさん『でも その\n{STR_VAR_2}に 「{STR_VAR_3}」って\pニックネームを つけるあたり\n{STR_VAR_1}さんの センスが わかるね!\pおねえさん『そうだねー$"

gTVPokemonTodaySuccessfulText07::
	.string "{JPN}わたしなら {STR_VAR_3} とかに\nそのニックネームを つけちゃう けどね!\pおにいさん『おー!\nそれ なかなか あたらしいかも!$"

gTVPokemonTodaySuccessfulText08::
	.string "{JPN}「{STR_VAR_2}」かー\nまさに {STR_VAR_1}って かんじよね!\pほら! もじの ふんいきとか なんとなく\n{STR_VAR_1}って かんじが するもの!\pおにいさん『……そうだね$"

gTVPokemonTodaySuccessfulText09::
	.string "{JPN}わたしの しってるかぎり {STR_VAR_1}に\n「{STR_VAR_2}」って ニックネームを\lつけている トレーナーなんて いないよ!\pおにいさん『それだけ ニックネームをつける\nセンスが いいって ことだよ!$"

gTVPokemonTodaySuccessfulText10::
	.string "{JPN}わたしも こんど ポケモンを つかまえたら\n「{STR_VAR_2}」って つけて みようかな?\pおにいさん『え? じゃあ ぼくも\n「{STR_VAR_2}」って つけよー!$"

gTVPokemonTodaySuccessfulText11::
	.string "{JPN}おねえさん『あ! もう こんなじかん!\pそれでは また じかいの\nほうそうで おあいしましょう\pおにいさん『つぎは あなたの ポケモンを\nしょうかい するかもよ!$"

SmartShopper_Text_Intro::
	.string "{JPN}こんにちは\p『きょうの かいもの じょうず』の\nじかん です\pインタビュアー『みなさん おげんきですか?\pきょうは {STR_VAR_2}の\nおみせに きています\pさいきん なにが うれているのか\nチェック してみましょう!$"

SmartShopper_Text_ClerkNormal::
	.string "{JPN}それでは てんいんさんに\nインタビュー してみましょう\lどうですか うれて いますか?\pてんいん『はい おかげさまで\pとくに {STR_VAR_2}が\nいま うれて いるんですよ\pこのまえも {STR_VAR_1}さん という\nかたが {STR_VAR_3}こも かって いかれました$"

SmartShopper_Text_RandomComment1::
	.string "{JPN}インタビュアー『{STR_VAR_2}を\n{STR_VAR_3}こも かうなんて すごいですね!\pもしかしたら {STR_VAR_1}さんは\nこれから とおくまで いくための\lたびじたくを していたのかも しれませんね\pやっぱり たびには {STR_VAR_2}ですね!$"

SmartShopper_Text_RandomComment2::
	.string "{JPN}インタビュアー『{STR_VAR_2} といえば\nわたし なんか このまえ\l{STR_VAR_3}こも かいましたよ!\p{STR_VAR_2}って いいですからねー!$"

SmartShopper_Text_RandomComment3::
	.string "{JPN}インタビュアー『{STR_VAR_2}を!!\n{STR_VAR_3}こも!?\p……そんなに かうひとが\nいるなんて しらなかったわ\pわたし なんか せいぜい 1こか 2こしか\nかわないから……$"

SmartShopper_Text_RandomComment4::
	.string "{JPN}インタビュアー『わたしも むかし\n{STR_VAR_2}を たくさん かったことが\lあったん ですけど\pあまって しまって\nこうかい したわ……\pそれからと いうもの ひつような\nぶんだけ かうように してるの……\pおっと!\pわたしの ことを はなしても\nしょうがない ですね!$"

SmartShopper_Text_SecondItem::
	.string "{JPN}てんいん『{STR_VAR_1}さんは そのほかにも\n{STR_VAR_2}を {STR_VAR_3}こ\lまとめて かわれましたよ\pインタビュアー『おー {STR_VAR_2}も\nなかなか よい ですもんね!$"

SmartShopper_Text_ThirdItem::
	.string "{JPN}てんいん『ついでに {STR_VAR_2}も\n{STR_VAR_3}こ かわれて いきました$"

SmartShopper_Text_DuringSale::
	.string "{JPN}てんいん『しかも おおやすうりの とき\nですから さすが ですよね!$"

SmartShopper_Text_OutroNormal::
	.string "{JPN}インタビュアー『うーん……\n{STR_VAR_1}さんって かなりの\lかいものじょうず なのかも しれませんね!\pこれで ごうけいは……\p{STR_VAR_2}えん!?\nさすが ですね!\pおっと それでは またじかいの\nほうそうで おあい しましょう!$"

SmartShopper_Text_IsVIP::
	.string "{JPN}てんいん『{STR_VAR_1}さんは ほんとうに\nだいじな おきゃくさま ですよ$"

SmartShopper_Text_ClerkMax::
	.string "{JPN}それでは てんいんさんに\nインタビュー して みましょう\lどうですか うれて ますか?\pてんいん『はい おかげさまで\nうれてうれて こまって ますよ!\pこのまえ {STR_VAR_1}さん というかたが\n{STR_VAR_2}を たくさん かわれまして\pみせのなかに {STR_VAR_2}が\nなくなって しまいそう だったんですよ!\pわたくしも {STR_VAR_2}を そんなに\nかう おきゃくさまが いるなんて\lゆめにも おもいません でした からね!\pインタビュアー『と いうことは……\n100こ とか 200こ とか ですか?\pてんいん『いや もっと でしたよ!\pインタビュアー『うひゃー!\n{STR_VAR_1}さんって すごい ですね!\pてんいん『{STR_VAR_1}さんは ほんとうに\nだいじな おきゃくさま ですよ$"

SmartShopper_Text_OutroMax::
	.string "{JPN}インタビュアー『うーん すごい ですね\pでも なんで そんなに\nいっぱい かったので しょう?\p……\pなぞは ふかまる ばかりですが\nじかんの ようなので\lまたじかい おあい しましょう!\pそれに しても\n{STR_VAR_1}さんって なぞだわ……$"

gTVWorldOfMastersText00::
	.string "{JPN}『めいじんの せかい』\pみなさん こんにちは\pみなさんは {STR_VAR_1}さん という\nトレーナーを しってますか?\p{STR_VAR_1}さんは ポケモンを つかまえる\nめいじん として ゆうめい なんです\p{STR_VAR_1}さんの ポケモンさがしは\nあるきまわる ところから はじまります\pこのまえは ポケモンを さがすために\n1にちで {STR_VAR_2}ほ いじょうも あるき\pつかまえた ポケモンの かずは\nなんと {STR_VAR_3} ひきにも なったとか!$"

gTVWorldOfMastersText01::
	.string "{JPN}きっと あいぼうの {STR_VAR_1}と\nしんらい しあっている からこそ\lこんな すごいことが できるんですね$"

gTVWorldOfMastersText02::
	.string "{JPN}めいじんは さいごに\n{STR_VAR_2}で\l{STR_VAR_3}を つかまえ\pきねんの ポケモンとして だいじに\nしている らしいですよ\pじしんのある トレーナーは このきろくに\nちょうせんして みては いかがですか?\pそれでは また\nじかい おあいしましょう$"

gTVTodaysRivalTrainerText00::
	.string "{JPN}『きょうの ライバル トレーナー』\pポケモン トレーナーの みなさん!\nごきげん いかがですか?\pきょうも みなさんの ライバルたちの\nようすに ついて おつたえします!$"

gTVTodaysRivalTrainerText07::
	.string "{JPN}こんかいの トレーナーは\nげんざい {STR_VAR_3}に\lいらっしゃる {STR_VAR_1}さん です!\p{STR_VAR_1}さんは\nポケモン ずかんを {STR_VAR_2}ひき\lとうろく されていますねー!$"

gTVTodaysRivalTrainerText08::
	.string "{JPN}こんかいの トレーナーは\nげんざい ひみつきちに\lいらっしゃる {STR_VAR_1}さん です!\p{STR_VAR_1}さんは\nポケモン ずかんを {STR_VAR_2}ひき\lとうろく されていますねー!$"

gTVTodaysRivalTrainerText09::
	.string "{JPN}こんかいの トレーナーは\n{STR_VAR_1}さん です!\pげんざい {STR_VAR_1}さんは\nポケモン ずかんを {STR_VAR_2}ひき\lとうろく されていますねー!$"

gTVTodaysRivalTrainerText10::
	.string "{JPN}こんかいの トレーナーは\nげんざい れんらくせんに のっている\l{STR_VAR_1}さん です!\p{STR_VAR_1}さんは\nポケモン ずかんを {STR_VAR_2}ひき\lとうろく されていますねー!$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "{JPN}バッジは {STR_VAR_1}こ\nかくとく されていますよー!$"

gTVTodaysRivalTrainerText02::
	.string "{JPN}バッジは まだ 1こも\nかくとく されていませんねー!$"

gTVTodaysRivalTrainerText03::
	.string "{JPN}バトルフロンティアの シンボルは\n1こも かくとく されていませんねー!$"

gTVTodaysRivalTrainerText04::
	.string "{JPN}バトルフロンティアの シンボルは\nゴールドシンボルを {STR_VAR_1}こ\lシルバーシンボルを {STR_VAR_2}こ\lかくとく されていますねー!$"

gTVTodaysRivalTrainerText05::
	.string "{JPN}バトルフロンティアでの\nバトルポイントは げんざい\l{STR_VAR_1} BP あつめていますねー!$"

gTVTodaysRivalTrainerText06::
	.string "{JPN}{STR_VAR_1}さんの ようすは\nみなさんと くらべて いかが でしたか?\pまだまだ ぼうけんは つづきます\pトレーナーの みなさん!\pライバルたちに まけずに\nがんばって くださいねー!$"

TrendWatcher_Text_Intro::
	.string "{JPN}『ムロタウン\n りゅうこう じょうほうきょく』\pしかい『さあ きょうも ムロタウンの\nりゅうこうを いちはやく おとどけします\pゲストは ムロタウン いち\nものしり という この おじいさんです!\pろうじん『……ふむ よろしくじゃ\pしかい『さっそく ですが ムロタウンで\nいま はやっている ことと いえば……\pろうじん『{STR_VAR_1} {STR_VAR_2}\pしかい『{STR_VAR_1} {STR_VAR_2}\n……ですか?\pろうじん『……いいや!\n{STR_VAR_1} {STR_VAR_2} は\lまったく はやらんかった のじゃ……\lこの はなし ききたいか のう……?\pしかい『いや いまの りゅうこうを……$"

@ Identical to below, may have been different in other languages

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "{JPN}ろうじん『{STR_VAR_1} {STR_VAR_2} は\nミシロから きた {STR_VAR_3}くんが\lおしえて くれたの じゃがのう……$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "{JPN}ろうじん『{STR_VAR_1} {STR_VAR_2} は\nミシロから きた {STR_VAR_3}ちゃんが\lおしえて くれたの じゃがのう……$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "{JPN}まったく ダメ じゃった……\p{STR_VAR_1} {STR_VAR_2} まつり!\p{STR_VAR_1} {STR_VAR_2} たいかい!\pわしも みんなに いっしょうけんめい\nおしえたの じゃがのう……\p「{STR_VAR_1}」が わるかったのか のう……\pしかい『……すいませんが\nいまの りゅうこうを……$"

@ Identical to below, may have been different in other languages

TrendWatcher_Text_MaleTellMeBigger::
	.string "{JPN}ろうじん『{STR_VAR_3}くん!\n{STR_VAR_1} {STR_VAR_2} より\lすごい こと また おしえて おくれー$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "{JPN}ろうじん『{STR_VAR_3}ちゃん!\n{STR_VAR_1} {STR_VAR_2} より\lすごい こと また おしえて おくれー$"

TrendWatcher_Text_Outro::
	.string "{JPN}しかい『……えーと ……はい! ということで\n{STR_VAR_1} {STR_VAR_2} は……\lムロタウンで はやらなかった!\p……いじょうを おつたえしました\pろうじん『{STR_VAR_1} {STR_VAR_2}$"

gTVHoennTreasureInvestigatorsText00::
	.string "{JPN}『ホウエン おたから たんていだん!』\pみんなー!\nかくしアイテム みつけてるー!?\pきょうも かくちで もくげき された\nひみつの じょうほうを しょうかい するよ!\pきょうの おてがみは\n「{STR_VAR_1} はっけん!」に\lついてだよー!!$"

gTVHoennTreasureInvestigatorsText01::
	.string "{JPN}さっそく よんでみるねー!\p……たんていだんの みなさん こんにちは\pこの あいだ {STR_VAR_2}さんが\n「{STR_VAR_3}」で なんと!\l「{STR_VAR_1}」を みつけて いました\lもう とっても うらやましかったです\p……やったね! {STR_VAR_2}さん!\pテレビの まえの みんなも まけずに\nダウジングマシンを つかって さがしてね!\pきみの とっておきの じょうほう\nまってるよー!$"

gTVHoennTreasureInvestigatorsText02::
	.string "{JPN}さっそく よんでみるねー!\p……たんていだんの みなさん こんにちは\pこの あいだ {STR_VAR_2}さんが\n「れんらくせん」で なんと!\l「{STR_VAR_1}」を みつけて いました\lもう とっても うらやましかったです\p……やったね! {STR_VAR_2}さん!\pテレビの まえの みんなも まけずに\nダウジングマシンを つかって さがしてね!\pきみの とっておきの じょうほう\nまってるよー!$"

gTVFindThatGamerText00::
	.string "{JPN}『ギャンブラーを さがせー!』\pみなさーん!\n{STR_VAR_2} ガンガン まわしてますかー?\pさあ きょうも ゲームコーナーで\nすごかった トレーナーさんを\lはっぴょう させて いただきますよ!\pきょうの ナンバー1 ギャンブラーは……\l{STR_VAR_1}さん です!$"

gTVFindThatGamerText01::
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}で\nなんと {STR_VAR_3}まいも\lコインを だした そうです!\p「{STR_VAR_1}さんが きたら\n あかじ かくご!」\p……という ことばが てんいんたちの\nあいだで ささやかれた そうです!\pテレビの まえの みなさんも\n{STR_VAR_1}さんの ように {STR_VAR_2}で\lあそんで みては いかがでしょうか?\pいじょう\nホウエン いち ドキドキの スポット!\lゲームコーナー より おおくりしました$"

gTVFindThatGamerText02::
	.string "{JPN}{STR_VAR_1}さんは {STR_VAR_2}で\nなんと {STR_VAR_3}まいも\lまけてしまった そうです!\p「{STR_VAR_1}さんが きたら\n うりあげ 2ばい!」\p……という ことばが てんいんたちの\nあいだで ささやかれた そうです$"

gTVFindThatGamerText03::
	.string "{JPN}テレビの まえの みなさんは\n{STR_VAR_1}さん みたいに ならないように\l{STR_VAR_2}で あそんでみては\lいかがで しょうか?\pいじょう\nホウエン いち ドキドキの スポット!\lゲームコーナー より おおくりしました$"

gTVBreakingNewsText00::
	.string "{JPN}……きんきゅう スペシャル テレビ!!$"

gTVBreakingNewsText01::
	.string "{JPN}『{STR_VAR_1}さん レア {STR_VAR_2}を\n つかまえるーーー!!』\p……はい!\nこちら {STR_VAR_3} です!\pさきほど {STR_VAR_1}さんが\nレア {STR_VAR_2}を つかまえる ことに\lせいこう しました!$"

gTVBreakingNewsText02::
	.string "{JPN}レア {STR_VAR_2}に であった\n{STR_VAR_1}さんは\l{STR_VAR_3}で たたかいを いどみました!\pそして……$"

gTVBreakingNewsText03::
	.string "{JPN}ボールを {STR_VAR_1}かい なげて\nみごと {STR_VAR_2}の なかに\lつかまえた のです!$"

gTVBreakingNewsText04::
	.string "{JPN}その しゅんかん {STR_VAR_2}には\n{STR_VAR_1}さんの よろこびの おたけびが\lひびき わたった そうです!\pいやー {STR_VAR_1}さん!\nうらやましいです!\lわたしも いっしょに さけびたいです!\p……いじょう\nよろこび いっぱいの げんばより\lおつたえ しました!$"

gTVBreakingNewsText05::
	.string "{JPN}『{STR_VAR_1}さん レア {STR_VAR_2}を\n とりにがすーーー!!』\p……はい!\nこちら {STR_VAR_3}です!\pさきほど {STR_VAR_1}さんが\nレア {STR_VAR_2}を つかまえることに\lしっぱい しました!$"

gTVBreakingNewsText06::
	.string "{JPN}レア {STR_VAR_2}に であった\n{STR_VAR_1}さんは\l{STR_VAR_3}で たたかいを いどみました$"

gTVBreakingNewsText07::
	.string "{JPN}そして……\p{STR_VAR_2}に {STR_VAR_1} などを\nめいれい している うちに\lきが つくと たおしていた のです……$"

gTVBreakingNewsText12::
	.string "{JPN}しかし……\pレア {STR_VAR_2}に おどろいて\nこんらんした {STR_VAR_1}さんは\lわけも わからないまま\l{STR_VAR_3}に めいれいを してしまい\lきが つくと たおしていた のです……$"

gTVBreakingNewsText08::
	.string "{JPN}その しゅんかん {STR_VAR_2}には\n{STR_VAR_1}さんの かなしみの さけびが\lひびき わたった そうです……$"

gTVBreakingNewsText09::
	.string "{JPN}しかし……\pボールが なかったのか このあと\n{STR_VAR_2}から にげてしまった のです\pその しゅんかん {STR_VAR_3}には\n{STR_VAR_1}さんの かなしみの さけびが\lひびき わたった そうです……$"

gTVBreakingNewsText10::
	.string "{JPN}しかし……\p{STR_VAR_2}は あっというまに\nにげてしまった のです\pその しゅんかん {STR_VAR_3}には\n{STR_VAR_1}さんの かなしみの さけびが\lひびき わたった そうです……$"

gTVBreakingNewsText11::
	.string "{JPN}いやー {STR_VAR_1}さん!\nざんねん でした……\lわたしも いっしょに さけびたいです\p……いじょう\nかなしみ いっぱいの げんばより\lおつたえ しました……!$"

gTVSecretBaseVisitText00::
	.string "{JPN}みなさん こんにちは!\n『ひみつきち ほうもん!』の じかんです\pきょうは {STR_VAR_1}さんの ひみつきちに\nおじゃま させて いただきます\p{STR_VAR_1}さんの きちは どんな\nおへやに なっている のでしょうか?\pさっそく はいって みましょう!\n……… ……… ……… ………$"

gTVSecretBaseVisitText01::
	.string "{JPN}おおー!\pこんな ところに 「{STR_VAR_2}」が!\nすばらしい ですねー$"

gTVSecretBaseVisitText02::
	.string "{JPN}おおー!\pなんと!\nグッズが なにも ありません!\pふつうの ひとには まね できない\nこの だいたんさ!\pシンプルで ありながら\nあふれでる この ワイルドさ!\pいやー\nさすが {STR_VAR_1}さん ですねー$"

gTVSecretBaseVisitText03::
	.string "{JPN}ああー! なるほど!\pここに 「{STR_VAR_2}」 ですか!\nこれは こうかてき ですねー$"

gTVSecretBaseVisitText04::
	.string "{JPN}ああー! なるほど!\pここには わざと グッズを おかずに\nあけて いるのですねー\pこれは こうかてき ですねー$"

gTVSecretBaseVisitText05::
	.string "{JPN}ふぇー!\p「{STR_VAR_2}」と\n「{STR_VAR_3}」の くみあわせ!\pゆめの がったいに なっていますねー$"

gTVSecretBaseVisitText06::
	.string "{JPN}ふぇー!\pここに 「{STR_VAR_2}」ですか!\nひみつきち ぜんたいに きいていますねー$"

gTVSecretBaseVisitText07::
	.string "{JPN}ふぇー!\pここには なにも おいていません\pいやー この なにもない スペースが\nひみつきち ぜんたいに きいてますねー$"

gTVSecretBaseVisitText08::
	.string "{JPN}あっ!\n{STR_VAR_1}さんが いらっしゃいます!\lさっそく たいせん してみましょう!\p…… …… …… ……\n…… …… …… ……$"

gTVSecretBaseVisitText09::
	.string "{JPN}はぁー!\nさすが {STR_VAR_1}さん です\pチャンピオンと よぶに ふさわしい\nつよさの ポケモン でした\p{STR_VAR_1}さんの ちからづよさが\nとっても でていましたよ\pとくに {STR_VAR_2}に\n「{STR_VAR_3}」 なんて\l{STR_VAR_1}さん らしいですねー\pいやー べんきょう させて いただきました$"

gTVSecretBaseVisitText10::
	.string "{JPN}ひぃー!\nさすが {STR_VAR_1}さん です\pものすごく つよい ポケモン でしたよ\p{STR_VAR_1}さんの がんばりやさんな\nところが でていましたよ\pとくに {STR_VAR_2}に\n「{STR_VAR_3}」 なんて\l{STR_VAR_1}さん らしいですねー\pいやー べんきょう させて いただきました$"

gTVSecretBaseVisitText11::
	.string "{JPN}ふぇー!\nさすが {STR_VAR_1}さん です\pバランスよく\nそだてられた ポケモン でしたよ\p{STR_VAR_1}さんの きくばり じょうずな\nところが でていましたよ\pとくに {STR_VAR_2}に\n「{STR_VAR_3}」 なんて\l{STR_VAR_1}さん らしいですねー\pいやー べんきょう させて いただきました$"

gTVSecretBaseVisitText12::
	.string "{JPN}ほぉー!\nさすが {STR_VAR_1}さん です\pしょうらいの せいちょうが\nたのしみな ポケモン でしたよ\p{STR_VAR_1}さんの ゆめと きぼうが\nでていましたよ\pとくに {STR_VAR_2}に\n「{STR_VAR_3}」 なんて\l{STR_VAR_1}さん らしいですねー\pいやー\nべんきょう させて いただきました$"

gTVSecretBaseVisitText13::
	.string "{JPN}いやー\nすばらしい おへや でしたねー\pみなさんも いちど {STR_VAR_1}さんの\nひみつきちを ごほうもん されてみては\lいかが でしょうか?\pでは また じかい おあいしましょう!\nさようなら!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "{JPN}『ドキドキ! ワクワク!\n ポケモンくじ とうせんしゃ そくほう!』\pこんにちは!\nこちらは ミナモデパート 1かい\lポケモンくじ うりば です!\pきょうも ひとりの ラッキートレーナーが\nあらわれました!\pその かたの おなまえは……\l{STR_VAR_1}さん です!\p{STR_VAR_1}さんは\nみごと {STR_VAR_2}とうを あてて\l{STR_VAR_3}を かくとく しました!\p{STR_VAR_1}さん!\nおめでとう ございました!\pテレビの まえの みなさんも ぜひ\nミナモデパートへ ごらいてん ください!\lてんいん いちどう おまち しております!\pいじょう\nホウエン いちの しなぞろえ\lミナモデパート より おおくり しました!$"

gTVThePokemonBattleSeminarText00::
	.string "{JPN}『ポケモン バトル こうざ!』\pきょうも みなさんと ごいっしょに\nバトルに ついて べんきょう しましょう\pきょうの もんだいは\n{STR_VAR_1}さんの バトルに ついてです\p{STR_VAR_1}さんは {STR_VAR_2}で\n{STR_VAR_3}と たたかったの ですが……$"

gTVThePokemonBattleSeminarText01::
	.string "{JPN}{STR_VAR_2}に たいして\n「{STR_VAR_3}」を やってしまいました……\pうーん…… {STR_VAR_1}さん!\nこれは いけませんね……$"

gTVThePokemonBattleSeminarText02::
	.string "{JPN}{STR_VAR_1}は そのほかに……$"

gTVThePokemonBattleSeminarText03::
	.string "{JPN}「{STR_VAR_1}」 「{STR_VAR_2}」\n「{STR_VAR_3}」 ……を おぼえていました$"

gTVThePokemonBattleSeminarText04::
	.string "{JPN}「{STR_VAR_1}」 「{STR_VAR_2}」\n……を おぼえていました$"

gTVThePokemonBattleSeminarText05::
	.string "{JPN}「{STR_VAR_2}」\n……を おぼえていました$"

gTVThePokemonBattleSeminarText06::
	.string "{JPN}この なかで いちばん よいのは\n…………………………………………\p「{STR_VAR_1}」 ですね!\p「{STR_VAR_2}」より\nぜったい 「{STR_VAR_1}」です\pテレビの まえの みなさんも\nよーく かんがえて バトルを しましょう!\pそれでは さようなら!$"

gTVTrainerFanClubText00::
	.string "{JPN}せーの!\n『トレーナー だいすき クラブ!!』\pしかい『みんなー げんきかーい!?\nきょうは いま だいにんきの トレーナー\l{STR_VAR_1}さんの ファンに\lあつまって もらったよ!\pファン『ワアアアアアアアアアーーー!\pファン『{STR_VAR_1}さまーーーー!\pしかい『みんなー!\n{STR_VAR_1}さんの ことは すきかいー?\pファン『だいすきー!!\pしかい『どんな ところがー?$"

gTVTrainerFanClubText01::
	.string "{JPN}ファン『モンスターボールを なげる しぐさが\nかっこいい ところ!!$"

gTVTrainerFanClubText02::
	.string "{JPN}ファン『はしる すがたが\nかわいい ところ!!$"

gTVTrainerFanClubText03::
	.string "{JPN}ファン『ポケモンバトルで\nここ いちばんに つよい ところ!!$"

gTVTrainerFanClubText04::
	.string "{JPN}ファン『ポケモンの ことに ついて\nくわしい ところ!!$"

gTVTrainerFanClubText05::
	.string "{JPN}ファン『ポケモンに たいして\nいつも やさしい ところ!!$"

gTVTrainerFanClubText06::
	.string "{JPN}ファン『じてんしゃを あやつる\nテクニックが すごい ところ!!$"

gTVTrainerFanClubText07::
	.string "{JPN}ファン『アイテムの かいかたが\nごうかいな ところ!!$"

gTVTrainerFanClubText08::
	.string "{JPN}ファン『ポケモンに つける ニックネームが\nおちゃめな ところ!!$"

gTVTrainerFanClubText09::
	.string "{JPN}ファン『ひみつきちの センスが\nいい ところ!!$"

gTVTrainerFanClubText10::
	.string "{JPN}ファン『わざマシンの つかい かたが\nだいたんな ところ!!$"

gTVTrainerFanClubText11::
	.string "{JPN}しかい『そんな ホットな\n{STR_VAR_1}さん ファンの あいだには\lとくべつな あいことばが あるんだよー!\pしかい『{STR_VAR_1} といえば……\pしかい『{STR_VAR_2}!\pファン『{STR_VAR_3}!\pしかい『{STR_VAR_2}!\pファン『{STR_VAR_3}!\pしかい『{STR_VAR_1} といえば……\n{STR_VAR_2} {STR_VAR_3}\lうーん! いい ひびきだねー!\p{STR_VAR_1}さんの ファンに\nなっちゃうのも わかる きが するよー!\pよーし! テレビの まえの みんなも\nいっしょに いってみよー!!\pしかい『{STR_VAR_1} といえば……\pしかい『{STR_VAR_2}!\pファン『{STR_VAR_3}!\pしかい『{STR_VAR_2}!\pファン『{STR_VAR_3}!\pしかい『{STR_VAR_1}さん ファンの\nみんなー ありがとーーー!!\lそれじゃー またねー!!\pしかい『{STR_VAR_1} といえば……\pしかい『{STR_VAR_2}!\pファン『{STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "{JPN}『ステキに はっけん!\n リボンを つけた ポケモンちゃん!!』\p……はぁー\pポケモンちゃんに リボンって\nほんと ステキ ざますねー\pきょうも まちで みかけた\nステキな ポケモンちゃんを\lみなさまに ごしょうかい するざます\pきょうの ポケモンちゃんは\n{STR_VAR_1}さんの {STR_VAR_2} ざます$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "{JPN}{STR_VAR_2}は なんと!\nリボンを {STR_VAR_3}こ つけている ざますよ\p{STR_VAR_1}さんの あいを\nかんじる ざますねー$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{JPN}{STR_VAR_2}は ビックリ ざます!\nリボンを {STR_VAR_3}こも つけている ざますよ\p{STR_VAR_1}さんの しゅうねんを\nかんじる ざますねー$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{JPN}{STR_VAR_2}は すごい ざます!\nリボンを {STR_VAR_3}こも つけている ざますよ\p{STR_VAR_1}さんの コレクターだましいを\nかんじる ざますねー$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "{JPN}さて {STR_VAR_2}に ついている\nたくさんの リボン ざますが……$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "{JPN}とくに でんどういりの きねんで もらった\nチャンプリボンが おにあい ざますね\p{STR_VAR_2}の ゆうかんさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に チャンプリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "{JPN}とくに かっこよさ コンテストで もらった\nクールリボンが おにあい ざますね\p{STR_VAR_2}の かっこよさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に クールリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "{JPN}とくに うつくしさ コンテストで もらった\nビューティリボンが おにあい ざますね\p{STR_VAR_2}の うつくしさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に ビューティリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "{JPN}とくに かわいさ コンテストで もらった\nキュートリボンが おにあい ざますね\p{STR_VAR_2}の かわいさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に キュートリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "{JPN}とくに かしこさ コンテストで もらった\nジーニアスリボンが おにあい ざますね\p{STR_VAR_2}の かしこさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に ジーニアスリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "{JPN}とくに たくましさ コンテストで もらった\nパワフルリボンが おにあい ざますね\p{STR_VAR_2}の たくましさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に パワフルリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "{JPN}とくに バトルタワーで もらった\nウイニングリボンが おにあい ざますね\p{STR_VAR_2}の つよさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に ウイニングリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "{JPN}とくに バトルタワーで もらった\nビクトリーリボンが おにあい ざますね\p{STR_VAR_2}の ものすごい つよさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に ビクトリーリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "{JPN}とくに えかきさん から もらった\nプロマイドリボンが おにあい ざますね\p{STR_VAR_2}の アイドルらしさを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に プロマイドリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "{JPN}とくに がんばりやで もらった\nがんばリボンが おにあい ざますね\p{STR_VAR_2}の がんばりぶりを\nとっても ひきたたせている ざますよー\p{STR_VAR_2}に がんばリボン!\nこうかは ばつぐん ざます!$"

TVSpotTheCuties_Text_Outro::
	.string "{JPN}……はぁー\pポケモンに リボンって……\nホントに いい ざますね!\pウットリ したところで\nさよなら ざますー!$"

gTVPokemonNewsBattleFrontierText00::
	.string "{JPN}こんにちは!\n『ポケモン ニュース』の じかんです\pバトルフロンティアから\nうれしい ニュースが はいって きました!$"

gTVPokemonNewsBattleFrontierText01::
	.string "{JPN}バトルタワー シングル バトルルームに\nちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText02::
	.string "{JPN}バトルタワー ダブル バトルルームに\nちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText03::
	.string "{JPN}バトルタワー マルチ バトルルームに\nちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText04::
	.string "{JPN}バトルタワー\nつうしん マルチ バトルルームに\lちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText05::
	.string "{JPN}バトルドーム\nシングル バトルトーナメントに\lちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんぱで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText06::
	.string "{JPN}バトルドーム\nダブル バトルトーナメントに\lちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんぱで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText07::
	.string "{JPN}バトルファクトリー\nバトルトレード シングルに\lちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText08::
	.string "{JPN}バトルファクトリー\nバトルトレード ダブルに\lちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText09::
	.string "{JPN}バトルチューブで\nバトルゲームに ちょうせんした\l{STR_VAR_1}さんが\l{STR_VAR_2} へや とっぱで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText10::
	.string "{JPN}バトルアリーナで\nかちぬきチームバトルに ちょうせんした\l{STR_VAR_1}さんが\l{STR_VAR_2} にんぬきで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText11::
	.string "{JPN}バトルパレス\nシングル バトルホールに\lちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText12::
	.string "{JPN}バトルパレス\nダブル バトルホールに\lちょうせんした {STR_VAR_1}さんが\l{STR_VAR_2} れんしょうで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText13::
	.string "{JPN}バトルピラミッドで\nバトルアドベンチャーに ちょうせんした\l{STR_VAR_1}さんが\l{STR_VAR_2} だん せいはで\lきろくを こうしん しました!\p……{STR_VAR_1}さん!$"

gTVPokemonNewsBattleFrontierText14::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}と\n{STR_VAR_3}の 3ひきの ポケモンたち!\pきろく こうしん\nおめでとう ございました!!$"

gTVPokemonNewsBattleFrontierText15::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}の\n2ひきの ポケモンたち!\pきろく こうしん\nおめでとう ございました!!$"

gTVPokemonNewsBattleFrontierText16::
	.string "{JPN}{STR_VAR_1}!\p{STR_VAR_2}!\p{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "{JPN}そして {STR_VAR_1}の\n4ひきの ポケモンたち!\pきろく こうしん\nおめでとう ございました!!$"

gTVPokemonNewsBattleFrontierText18::
	.string "{JPN}{STR_VAR_1}さんと ポケモンたちの\nつぎの チャレンジに きたい しましょう!\pいじょう\n『ポケモン ニュース』 でした!$"

gTVWhatsNo1InHoennTodayText00::
	.string "{JPN}『ホウエン きょうの\n なんでも ナンバー1!!』\pテレビの まえの みなさん\nがんばってますかー?\pきょうも いちにちで いちばん がんばった\nトレーナーを しょうかい しますよ!\p……さあ\nきょうの ナンバー1 トレーナーは……\l{STR_VAR_1}さんです!!$"

gTVWhatsNo1InHoennTodayText01::
	.string "{JPN}{STR_VAR_1}さんは ゲームコーナーの\nスロットを いちにちで\l{STR_VAR_2} かい まわしました!\p{STR_VAR_1}さんは あそんで いるときに\n「スロットが とまって みえる……!」と\lブツブツ ぶきみに\lつぶやいていた そうですよ!$"

gTVWhatsNo1InHoennTodayText02::
	.string "{JPN}{STR_VAR_1}さんは ゲームコーナーの\nルーレットを いちにちで\l{STR_VAR_2} かい まわしました!\p{STR_VAR_1}さんは あそんで いるとき\n「ボールの うごきが よめた……!」と\lめを まっかにして\lそれは すごい かおで\lさけんでいた そうですよ!$"

gTVWhatsNo1InHoennTodayText03::
	.string "{JPN}{STR_VAR_1}さんは やせい ポケモンと\nいちにちで {STR_VAR_2} かい たたかいました!\p{STR_VAR_1}さんの ポケモンたちは\nいぜんと くらべものに ならないほど\lつよくなった らしく……\pだれかと ポケモンしょうぶが したくて\nたまらない そうですよ!$"

gTVWhatsNo1InHoennTodayText04::
	.string "{JPN}{STR_VAR_1}さんは きのみブレンダーを\nいちにちで {STR_VAR_2} かい まわしました!\pさすがに さいごの ほうでは\n{STR_VAR_1}さんの めも\lくるくる まわってしまい\lまるで パッチールの ように\lなってしまった そうですよ!$"

gTVWhatsNo1InHoennTodayText05::
	.string "{JPN}{STR_VAR_1}さんは きのみを\nいちにちで {STR_VAR_2} こ うえました!\p{STR_VAR_1}さんの\nふくは まっくろに なりましたが……\pきのみを うえた ところには\nきれいな はなが たくさん さきほこり\lみる ひとの こころを\lなごませている そうですよ!$"

gTVWhatsNo1InHoennTodayText06::
	.string "{JPN}{STR_VAR_1}さんは きのみを いちにちで\n{STR_VAR_2} こ とりました\p{STR_VAR_1}さんの バックは\nきのみで いっぱいに なり\lあるくのも たいへんだった そうですよ!$"

gTVWhatsNo1InHoennTodayText07::
	.string "{JPN}{STR_VAR_1}さんは いちにちで\nバトルポイントを\l{STR_VAR_2} BP ためました!\p{STR_VAR_1}さんは \nたまった バトルポイントで\lすごい グッズを もらうべきか……\lすごい アイテムを もらうべきか……と\lニタニタ しながら\lずっと なやんでいた そうですよ!$"

gTVWhatsNo1InHoennTodayText08::
	.string "{JPN}いやー すごい ですね!\p{STR_VAR_1}さん!\nあなたが きょうの ナンバー1です!!\pテレビの まえの みなさんも\n{STR_VAR_1}さんに まけずに\lいちにち がんばりましょうね!$"

TVSecretBaseSecrets_Text_Intro::
	.string "{JPN}『ひみつきちの ヒミツー!』\pひみつきちで トレーナーは いったい\nどんな こうどうを とる のでしょうか?\pきょうは\n{STR_VAR_1}さんの ひみつきちです\p……さあ {STR_VAR_2}さんが\nあそびに いらした ようですね!\pさっそく のぞいてみましょう!\pまず {STR_VAR_2}さんは……$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "{JPN}{STR_VAR_2}さんは つぎに……$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "{JPN}この あと\n{STR_VAR_2}さんは……$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "{JPN}……と いうような かんじで\n{STR_VAR_2}さんは\l{STR_VAR_1}さんの きちを\l{STR_VAR_3}ほ あるいて かえりました$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "{JPN}……うーん\pどうやら {STR_VAR_2}さんは\n{STR_VAR_1}さんの ひみつきちに\lきょうみが わかなかった ようですね……$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{JPN}{STR_VAR_2}さんは\n{STR_VAR_1}さんの ひみつきちを\lとっても たのしんだ ようですね$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{JPN}{STR_VAR_2}さんは\n{STR_VAR_1}さんの ひみつきちマニアに\lなった ようですね$"

TVSecretBaseSecrets_Text_Outro::
	.string "{JPN}テレビの まえの みなさんも\n{STR_VAR_1}さんの ひみつきちを\lたずねて みては いかがでしょうか?\pそれでは また だれかの ひみつきちで\nおあいしましょう! さようなら!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "{JPN}……たちどまって しまいました!\pぜんぜん うごきません!\p{STR_VAR_1}さんの ひみつきちが\nきに いらなかった のでしょうか?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "{JPN}……たちどまって しまいました!\pぜんぜん うごきません!\p……つかれちゃった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "{JPN}いすに すわりましたー!\pとっても うれしそうです\pすわりごこちが\nよかった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "{JPN}ふうせんに とつげきだー!\pわっちゃいました!\pちょっと おとに\nビックリ しています$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "{JPN}テントに はいったー!\pはしりまわって います!\pあばれまわって います!\pテントの おおきさに\nびっくり しています!!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "{JPN}はちうえを かんさつ しています!\pいがいに アダルトな しゅみを\nもっていますね……$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "{JPN}きんのたてを みています!\pキラキラと めを\nかがやかせて いますね$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "{JPN}ぎんのたてを みています!\pめを まるーく していますね$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "{JPN}ガラスのオブジェを みています……\pあっ!\pさわっちゃいました……\pしもんを ペタペタ つけています$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "{JPN}テレビを みています!\pかなりの テレビっこ みたいですねー$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "{JPN}どろだんごを ふみつけましたー!\pとっても うれしそうです$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "{JPN}……おや?\pとつぜん バッグの なかみを\nガサガサと いじりだしましたよ!\pそして {STR_VAR_2}を\nとりだしたー!\p{STR_VAR_2}を もって\nスマイル! スマイル!!\pテレビの コマーシャル みたいだー!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "{JPN}クッションを つかんで……$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "{JPN}たたいてます!\pだいぶ ストレスが\nたまっている のでしょうか?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "{JPN}だきついたー!\pなにか いいことでも あった のでしょうか?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\pどうやら ポケモンバトルを やるようです\pそして……\pかったー!!\pうれしがっています$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\pどうやら ポケモンバトルを やるようです\pそして……\pまけたー!!\pがっかり しています$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\pどうやら ポケモンバトルを やるようです\pそして……\pいや ことわった!\pたいせんを ことわりました!\p{STR_VAR_1}さんの ことが\nきに いらなかった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "{JPN}ポスターを じーっと みつめています!\pきに いった のでしょうか?\p……でも\nちょっと めつきが やばいですねー$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "{JPN}おんぷマットに のったー!\p……うーん\nふしぎな きょくを つくっちゃいました……$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "{JPN}{STR_VAR_1}さんと はなしています!\pどうやら ポケモンバトルを やるようです\pそして……\pひきわけたー!\pふたりとも とっても くやしそうです$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "{JPN}くるっとマットに のったー!\pめが まわった ようです!\pクラクラ しています$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "{JPN}すなのおきものに てを ふれて……\pあっ!\pこわしちゃいましたー!\pかおが すこし ひきつっています$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "{JPN}つくえの うえを\nゆびで さわっています!\pどうやら ほこりが\nきに なっている みたいです!\pいやー\nいがいに こまかい ですねー$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "{JPN}レンガを じーっと みつめています!\pこの レンガにあう グッズの ことでも\nかんがえている のでしょうか?$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "{JPN}じょうぶないたの うえを あるいています!\pちょっと したを きにしています\pいがいに きが ちっちゃいですねー$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "{JPN}さくを じーっと ながめています!\pあたらしい トラップでも\nひらめいた のでしょうか?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "{JPN}きらきらマットに のったー!\pいろんな ポーズを きめています!\pきぶんは アイドル でしょうか?$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "{JPN}タイヤを じーっと みつめています!\pこの タイヤで はしる くるまの ことでも\nかんがえている のでしょうか?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "{JPN}おおきなだいに のぼりました!\p{STR_VAR_1}さんの きちを\nうえから みわたしています!\p……そして\pさけんだー!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "{JPN}やぶれるドアに むかって とつげきー!\pわらっています……$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "{JPN}ぬいぐるみに はなし かけています!\pちょっと こわい ですね……$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "{JPN}すべりだいの はしごを のぼりました!\p……そして\pすべったー!\pとっても たのしそうだ!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "{JPN}すべりだいの はしごを のぼりました!\p……そして\pもどったー!\pハシゴを おりて ひきかえしました!\pこわくなった のでしょうか?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "{JPN}ジャンプマットに のったー!\pジャンプを 1かい!\pジャンプを 2かい!\pちゃくち せいこう!\p……ひとりで じぶんに\nはくしゅを おくっています$"

gTVSafariFanClubText00::
	.string "{JPN}『サファリ だいすき クラブ!』\pレポーター『サファリボール なげてますか?\nわたしは いま めずらしい ポケモンが\lいっぱいの サファリゾーンに きています\pさっそく かかりいんさんに\nおはなしを うかがって みましょう!\p……サファリに きている トレーナーたちの\nようすは いかがですか?$"

gTVSafariFanClubText01::
	.string "{JPN}かかりいん『みんな がんばってますよ\pとくに {STR_VAR_1}さん なんて\nすごいです\pこの あいだ なんて {STR_VAR_2}ひきも\nつかまえたんですよ!$"

gTVSafariFanClubText02::
	.string "{JPN}{STR_VAR_2}この ポロックを\nじょうずに つかっていました!$"

gTVSafariFanClubText03::
	.string "{JPN}しかも ポロックを 1こも\nつかって いないんです!\pいやー すごい うで でしたよ$"

gTVSafariFanClubText04::
	.string "{JPN}レポーター『そうですかー\p{STR_VAR_1}さんは\nサファリの めいじん ですね\pかかりいん『また おとずれて\nあの すごい わざを みせて ほしいです$"

gTVSafariFanClubText05::
	.string "{JPN}かかりいん『みんな いまいち ですね……\pとくに {STR_VAR_1}さんは\nひどかった ですね\pこの あいだ なんて {STR_VAR_2}ひき しか\nつかまえられません でしたから$"

gTVSafariFanClubText06::
	.string "{JPN}かかりいん『みんな いまいち ですね……\pとくに {STR_VAR_1}さんは\nひどかった ですね\pこの あいだ なんて 1ひきも\nつかまえられません でしたから……$"

gTVSafariFanClubText07::
	.string "{JPN}いちおう ポロックは {STR_VAR_2}こ\nつかって いましたけどね\pもう ちょっと\nうでを あげて ほしいですねー$"

gTVSafariFanClubText08::
	.string "{JPN}1こも つかってなかった\nポロックを つかうように なれば\lよくなると おもうんですがね……$"

gTVSafariFanClubText09::
	.string "{JPN}レポーター『そうですかー\p{STR_VAR_1}さん には\nサファリを とっくんして ほしいですね\pかかりいん『なんども おとずれて\nコツを つかんで ほしいです$"

gTVSafariFanClubText10::
	.string "{JPN}レポーター『そうです!\nチャレンジは たいせつです\pテレビの まえの みなさんも なんどでも\nサファリに チャレンジ しましょう!\pでは また!$"

ContestLiveUpdates_Text_Intro::
	.string "{JPN}『ポケモン コンテスト\n けっか そくほう!』\pしかい『……はい!\nこちら さきほど おわりました\l{STR_VAR_1} コンテストの かいじょうです\pかいじょうには まだ たくさんの\nおきゃくさんが のこっています\pかんきゃく『{STR_VAR_2}ーーー!\pかんきゃく『{STR_VAR_3}ーーー!\pしかい『……と みなさんが おっしゃる\nとおりに ゆうしょう ポケモンは\l{STR_VAR_3}さんの {STR_VAR_2} でした!\pかんきゃく『{STR_VAR_2}! さいこー!\pかんきゃく『{STR_VAR_3}! えらいー!\pしかい『それでは…… おきゃくさんに\nちょっと かんそうを きいて みましょう!$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "{JPN}かんきゃく『1じ しんさも 2じ しんさも\nだんとつで 1ばん でしたー!\l{STR_VAR_2} つぎも ゆうしょうだー!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "{JPN}かんきゃく『1じ しんさが だめ だったのに\n2じ しんさで だいぎゃくてん!\lミラクル {STR_VAR_2} ばんざいーー!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "{JPN}かんきゃく『1じ しんさも 2じ しんさも\nあんてい しておったのう……\p{STR_VAR_2}に {STR_VAR_3}さん!\nあんたら ただものでは ないのう……$"

ContestLiveUpdates_Text_BetterRound1::
	.string "{JPN}かんきゃく『{STR_VAR_2}の\nあの {STR_VAR_1}は ケタちがい でしたね!\lつぎは もっと アピールを がんばってー!$"

ContestLiveUpdates_Text_GotNervous::
	.string "{JPN}かんきゃく『{STR_VAR_2}が\nきんちょう したとき おもわず\lがんばれー って さけんじゃいました\p{STR_VAR_2} よかったね おめでとう!$"

ContestLiveUpdates_Text_StartledFoes::
	.string "{JPN}かんきゃく『{STR_VAR_2}の アピールで\nおもわず ボクも おどろいちゃった!\p{STR_VAR_2}! きみは スゴイ!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "{JPN}かんきゃく『{STR_VAR_2}の\nあの コンボでの アピール!\lああ もう ウットリ……$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "{JPN}かんきゃく『{STR_VAR_2}の アピールに\nもう もえあがっちゃいました!$"

ContestLiveUpdates_Text_WasCool::
	.string "{JPN}{STR_VAR_2}!\nかっこよかった よー!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{JPN}{STR_VAR_2}\nうつくしかった よー!$"

ContestLiveUpdates_Text_WasCute::
	.string "{JPN}{STR_VAR_2}\nかわいかった よー!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{JPN}{STR_VAR_2}!\nかしこかった よー!$"

ContestLiveUpdates_Text_WasTough::
	.string "{JPN}{STR_VAR_2}!\nたくましかった よー!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "{JPN}かんきゃく『{STR_VAR_2}の アピールに\nもう もえつきちゃい ました!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{JPN}{STR_VAR_2}!\nさいこうに かっこいいー!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{JPN}{STR_VAR_2}!\nさいこうに うつくしいー!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{JPN}{STR_VAR_2}!\nさいこうに かわいいー!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{JPN}{STR_VAR_2}!\nさいこうに かしこいー!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{JPN}{STR_VAR_2}!\nさいこうに たくましいー!$"

ContestLiveUpdates_Text_TookBreak::
	.string "{JPN}かんきゃく『{STR_VAR_2}が とちゅうで\nアピールを やすんだ ときも……\lずーっと {STR_VAR_2}だけ みてました!\pもう {STR_VAR_2}の とりこ です……$"

ContestLiveUpdates_Text_GotStartled::
	.string "{JPN}かんきゃく『{STR_VAR_2}が ほかの\nポケモンの アピールに おどろいた ときは\lもう なきそうに なっちゃいました!\p{STR_VAR_2}\nがんばったねー! えらい!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "{JPN}かんきゃく『ああ……\n{STR_VAR_2}の {STR_VAR_3}!\l{STR_VAR_2}の {STR_VAR_3}!\l{STR_VAR_2}の {STR_VAR_3}!\lなんで あんなに ステキなんだー!$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "{JPN}しかい『……いやー すごいですね\n{STR_VAR_1}ファン いっしょくです\pその ほかの トレーナーさんと ポケモンで\nわたしの いんしょうに のこったのは……\l{STR_VAR_2}さんと {STR_VAR_3}ですね\p{STR_VAR_2}さんの {STR_VAR_3}は……$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "{JPN}きんちょうして 2じしんさで 1かいも\nアピールが できませんでした\pつぎは 1かい だけでも {STR_VAR_1}の\nアピールを みたいものです$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "{JPN}1じしんさも 2じしんさも\nダントツで ビリでした\p{STR_VAR_1}さんには {STR_VAR_2}を\nきたえ なおして\lビリから ぬけだして ほしいです$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "{JPN}かいじょうが もりあがっている ときに\nふさわしい アピールが できません でした\p{STR_VAR_1}さんには ながれを よんで\nつぎこそ かいじょうを エキサイト させて\lさいこうに もりあげて ほしいです$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "{JPN}1じしんさで いちばん だったのに\n2じしんさの アピールが うまくいかず\lぎゃくてん まけを してしまいました\pきっと いまごろ {STR_VAR_1}さんは\nアピールに ついて\lべんきょう していると おもいます$"

ContestLiveUpdates_Text_NeverExciting::
	.string "{JPN}2じ しんさの アピールで 1ども\nかんきゃくが もりあがり ませんでした\pほかの ポケモンの ことは きにせず\nもっと かんきゃくに むかって\lアピールをして ほしいです$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "{JPN}{STR_VAR_1}さんの {STR_VAR_2}と\nちょっとの さで まけて しまいました\pあと すこしで ゆうしょう だったのに\nとっても ざんねんです\pいまごろ {STR_VAR_3}さんは\nないていると おもいます$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "{JPN}おなじ アピールを つづけて しんさいんに\nがっかりされて しまいました\pコンテストで やっては いけない\nミスを したのが いたかったですね\pいまごろ {STR_VAR_1}さんは\nじぶんを せめていると おもいます$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{JPN}{STR_VAR_1}さん なりに がんばって\nいたのですが……\pけっかてきに ビリに なってしまいました\p{STR_VAR_1}さんには まけた りゆうを\nかんがえて つぎに つなげて ほしいです$"

ContestLiveUpdates_Text_Outro::
	.string "{JPN}それでは さいごに みなさんと ごいっしょに\n{STR_VAR_1}さんと {STR_VAR_2}に\lひとこと おくりたいと おもいます\pしかい『みなさん いいですかー? せーの\pみんな『{STR_VAR_1}さん! {STR_VAR_2}!\nコンテスト ゆうしょう おめでとうー!$"

gTVPokemonBattleUpdateText00::
	.string "{JPN}『ポケモン たいせん そくほう!』\pさきほど おこなわれた ポケモンバトルの\nけっかを おつたえします$"

gTVPokemonBattleUpdateText01::
	.string "{JPN}{STR_VAR_1}さん たい\n{STR_VAR_2}さんの {STR_VAR_3}バトルは……\p{STR_VAR_1}さんが\nしょうり しました!$"

gTVPokemonBattleUpdateText02::
	.string "{JPN}バトルは {STR_VAR_1}さんの\n{STR_VAR_2}が {STR_VAR_3}を つかって\lだいかつやく しました!$"

gTVPokemonBattleUpdateText03::
	.string "{JPN}{STR_VAR_1}さんに とっては\n{STR_VAR_2}が ブレーキ だったのが\lいたかった ようです$"

gTVPokemonBattleUpdateText04::
	.string "{JPN}しょうりを おさめた\n{STR_VAR_1}さん!\lおめでとう ございました!\pやぶれて しまった\n{STR_VAR_2}さん!\lつぎは がんばって ください!\pいじょう\n『ポケモン たいせん そくほう!』 でした$"

gTVPokemonBattleUpdateText05::
	.string "{JPN}{STR_VAR_1}さん チーム たい\n{STR_VAR_2}さん チームの\lマルチバトルの けっかは……\p{STR_VAR_1}さん チームが\nしょうり しました$"

gTVPokemonBattleUpdateText06::
	.string "{JPN}バトルは {STR_VAR_1}さん チームの\n{STR_VAR_2}が {STR_VAR_3}を つかって\lだいかつやく しました!$"

gTVPokemonBattleUpdateText07::
	.string "{JPN}{STR_VAR_2}さん チームに とっては\n{STR_VAR_3}が ブレーキ だったのが\lいたかった ようです\pしょうりを おさめた\n{STR_VAR_1}さん チーム!\lおめでとう ございました!\pやぶれて しまった\n{STR_VAR_2}さん チーム!\lつぎこそ がんばって ください!\pいじょう\n『ポケモン たいせん そくほう!』 でした$"

gTVInSearchOfTrainersText00::
	.string "{JPN}『トレーナーを もとめて』\pマリ『はーい わたしは いま\n{STR_VAR_1}に きています!\pきょうは ここで あたらしい さいのうを\nはっくつ しようと おもいます!\pきょう わたしが ちゅうもく した\nトレーナーは {PLAYER}さん!\pわたしは この トレーナーに\nなにかを かんじます!$"

gTVInSearchOfTrainersText01::
	.string "{JPN}{PLAYER}さんとは まえに\nたたかった ことが あるのですが\pかくじつに まえより\nつよく なっている かんじが します!\pさっすが わたしの\nちゅうもく した トレーナー!$"

gTVInSearchOfTrainersText02::
	.string "{JPN}さて トレーナーの じつりょくを\nみるには…\pたたかって みるのが いちばん はやい!\nさっそく ちょうさを かいし します!\p……\pと いうわけで\nたたかって みたの ですが\pみごとに ボコボコに されました!\n{PLAYER}さん やたら つよいですね……\pで たたかった かんそうを\nいわせて もらいますと$"

gTVInSearchOfTrainersText03::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_3}の\nコンビが さいこう でしたね!\p{STR_VAR_1}と {STR_VAR_3}が おたがい\nたすけあって たたかう すがた……\pあぁ なんて\nすばらしいんでしょう!\pわたしたちとの しょうぶで\nさいごに つかった 「{STR_VAR_2}」も\p{STR_VAR_1}と {STR_VAR_3}の ゆうじょうの\n「{STR_VAR_2}」なんですね!$"

gTVInSearchOfTrainersText04::
	.string "{JPN}……わたくし じしんを\nなくして しまいました\pいっかいも こうげきする ひまもなく\nすぐに まけて しまいました\lああ グスン……\pでも {PLAYER}さんの たたかいは\nいっけんのかち あり です!\pじしんの ある トレーナーは いちど\nたたかって みることを おすすめ しますよ!$"

gTVInSearchOfTrainersText05::
	.string "{JPN}トレーナーと たたかって いるときは\nモンスターボールを なげるな!\lという ことです\p{PLAYER}さん しょうぶは つよいのに\nきほんが なって ませんよ!\pもう テレビを みてる みんな!\p{PLAYER}さんに あったら\nちゅういして やってね!$"

gTVInSearchOfTrainersText06::
	.string "{JPN}{PLAYER}さん あいての こうどうを\nよむのが とても うまいです!\pどうぐを つかう タイミング なんか\nなかなかの ものでしたよ!$"

gTVInSearchOfTrainersText07::
	.string "{JPN}しょうじき わたしも なかなか\nつよいかも と おもっちゃい ましたー!\pさいごは けっきょく まけちゃった けど\nいい しあい だったなー\pでも わたしに くせん してるようじゃ\nまだまだ ですよ {PLAYER}さん!$"

gTVInSearchOfTrainersText08::
	.string "{JPN}たいせんの あと {PLAYER}さんに\nいまの たいせんの かんそうを きくと\p「{STR_VAR_1}」って\nこたえて くれました\p{PLAYER}さんの ポケモンの\n{STR_VAR_2}と {STR_VAR_3}\lそして 「{STR_VAR_1}」……\pんー!!\nなんか いみのふかい ことば よね!\pやはり いい トレーナーは\nいいことを いって くれますね\pさて それじゃあ また\nじかいの ほうそうで おあい しましょう!$"

ContestLadyShow_Text_Intro::
	.string "{JPN}『ポケモン コンテスト けっか そくほう』\pしかい『みなさん きょうしゅく です!\pほんじつは {STR_VAR_1}さ コンテストが\nしゅうりょうした ばかりの こちらの\lかいじょう から おおくり します!\pかんきゃく『?ーーー!!\pしかい『おおっと どうやら\nコンテスト さんかしゃ たちが\lこちらに むかって くるようですっ!\pわたくし さっそく とつげき しゅざいを\nおこないたいと おもいます!\pかんきゃく『?ーーー!! ?ーーー!!$"

ContestLadyShow_Text_Won::
	.string "{JPN}しかい『きょうしゅく です!\pゆうしょう おめでとう ございます!\nこんかいの きめてに なったのは\lどんな ところ なので しょうか?\pおねえさん『あたしも {STR_VAR_2}も\nとっても がんばりました!\pだけど きっと コンテストに でるまでに\nきょうりょくして くれた ひとたちの\lおかげだと おもいますっ!\pしかい『では この よろこびを\nいちばん つたえたい かたに むけて\lひとこと メッセージを おねがい します!\pおねえさん『おーいっ!\p{STR_VAR_3}さーん! みてるーっ!?\nあたしたち やったよーっ!\lどうも ありがとーっ!$"

ContestLadyShow_Text_Lost::
	.string "{JPN}しかい『きょうしゅく です!\pしかし こんかいは ざんねん でしたね!\nなにか コメントを おねがい します!\pおねえさん『ざんねんでした……\nあたしも {STR_VAR_2}も がんばったけど\lおうえん してくれた ひとたちに\lもうしわけ ないです……\pしかい『うーん たしかに けづやが\nちょっと いまいちな かんじ ですねー\pおねえさん『……{STR_VAR_3}さん ごめんね\nこんどは がんばるから……\l…… …… うっ …… うわーん!\pかんきゃく『ガヤガヤ ガヤガヤ\pしかい『あわぁぁ…… しまった……\pそっ それでは このあたりで\nおわかれです! みなさん さようならー!$"

ContestLadyShow_Text_LostBadly::
	.string "{JPN}しかい『きょうしゅく です!\pこんかいの コンテスト いかが でした?\pおねえさん『ぜんぜん だめでした……\nあたしの {STR_VAR_2}は なんだか\lにんきが なかった みたいで……\pしかい『うーん たしかに けづやが\nちょっと いまいちな かんじ ですねー\pおねえさん『…… …… …… ……\n…… うっ …… うっ うわーん!\pかんきゃく『ガヤガヤ ガヤガヤ\pしかい『あわぁぁ…… しまった……\pそっ それでは このあたりで\nおわかれです! みなさん さようならー!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest::
	.string "{JPN}おや?\nあなたも ポケモンのことが おすきで?\pわたくし テレビきょくの もので\nさいきん おきた\pトレーナーと ポケモンの できごとを\nきいて まわって いるのです\pもし よければ なにか\nはなしを きかせて くれませんかね?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort::
	.string "{JPN}いま さいきん おきた\nトレーナーと ポケモンの できごとを\lきいて まわって いるのですが\pもし よければ なにか\nはなしを きかせて くれませんかね?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon::
	.string "{JPN}おお きかせて くれますか!\nありがとう ございます\pでは さいきん おきたこと なら\nなんでも よいので\lはなしを きかせて ください!$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory::
	.string "{JPN}そうですか……\pでは また なにか おもしろい はなしが\nあったら きかせて くださいね$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview::
	.string "{JPN}……おお\nなんて いいはなしだ!\pこのはなし テレビで\nつかわせて いただきます!\pいつか ほうそう するかも しれないので\nたのしみに まっていて くださいね$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory::
	.string "{JPN}うーん\nいい テレビばんぐみが できそうだ!\pいそいで まとめないと!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName::
	.string "{JPN}わあ!\pきみ その {STR_VAR_1}を とても\nだいじに している みたいね!\p{STR_VAR_2} って いうんだ……\pそうだ!\pいま わたし テレビの しゅざいで\nポケモンの アンケートを してるんだけど\pすこしだけ しつもんに\nこたえて くれないかな?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers::
	.string "{JPN}ありがとう!\pじゃあ きくね\nずばり ひとことで こたえて!$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon::
	.string "{JPN}きみが {STR_VAR_1}と\nであったときって\pなにか かんじた?\nどう おもったか おしえて!$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike::
	.string "{JPN}きみの かわいがってる {STR_VAR_1}!\pもし なにか すきなものに たとえると\nすれば なんだと おもう?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon::
	.string "{JPN}きみの かわいがってる {STR_VAR_1}!\pきみは {STR_VAR_1}の どこに\nひかれたの?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou::
	.string "{JPN}うーん なるほどね\pじゃあ つぎは ちょっと\nむずかしい しつもんを するね!\pじゃあ……\pきみに とって ポケモンって\nひとことで いうと なんだと おもう?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview::
	.string "{JPN}なるほどー!\pふむふむ……\pあ!\nきょうりょく ありがとうね!\pいろいろ はなしが きけて\nおもしろ かったよ\pこのはなし もしかしたら テレビで\nながすかも しれないから きたい しててね\pじゃあね\nバイバイ!$"

SlateportCity_PokemonFanClub_Text_InterviewRequest::
	.string "{JPN}きみの その {STR_VAR_1}と\nとても なかが よさそうね\pそうだ! いま わたし\nテレビの しゅざいで\pいろんな ポケモンの はなしを\nきいて まわってるんだけど\pよかったら きみの {STR_VAR_1}の\nはなしを きかせて くれないかな?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon::
	.string "{JPN}わあ!\nありがとう!\pじゃあ {STR_VAR_1}の はなし\nなんでも いいので きかせてよ!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe::
	.string "{JPN}そっか……\pじゃあ また ポケモンの ことを\nはなしたく なったら いつでも きてね$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2::
	.string "{JPN}へー……\nおもしろい はなし だね!\pきみは ほんとうに {STR_VAR_1}と\nなかが いいんだね\pうーん なんか このはなしで\nいい ばんぐみが できそうな よかん!\pきっと おもしろい ばんぐみに\nするから たのしみに まっててね\pじゃあ ありがとうね\nバイバイ!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews::
	.string "{JPN}ここに いると いろんな ポケモンの\nはなしが きけるから おもしろいわ$"

LilycoveCity_ContestLobby_Text_InterviewRequest::
	.string "{JPN}おや? あなた ポケモンコンテストに\nさんかして いましたね!\lその ポケモンを みれば わかりますよ!\pわたくし ポケモンコンテストに ついて\nきじを かいて いるのですが\pできれば すこし かんそうを\nきかせて くれませんかね?$"

LilycoveCity_ContestLobby_Text_DescribeContest::
	.string "{JPN}ほんとう ですか!\nありがとう ございます\pそれでは いまの コンテストの かんそうを\nひとことで おねがいします!$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX::
	.string "{JPN}うーん なるほど!\pどんな コンテストだったか\nよくわかる ひとこと ですね!\p……さいごに\nちょっと おききしたいの ですが\pあなたが イメージする {STR_VAR_2}って\nいったい どんなもの ですかね?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview::
	.string "{JPN}なるほど!\pそれが あなたの イメージする\n{STR_VAR_2} なんですね!\pいろいろ さんこうに なりました!\pコンテストに ついて\nいい きじが かけそう ですよ\pもしかしたら テレビで このことが\nながれるかも しれないので\lたのしみに してくださいね!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe::
	.string "{JPN}そうですか……\pこんど おもしろいことが あれば\nきかせて くださいね$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest::
	.string "{JPN}こんどの ポケモンコンテストも\nたのしみに してますよ!$"

GabbyAndTy_Text_GabbyPreFirstBattle::
	.string "{JPN}マリ『おっ こんなところに\nつよそうな トレーナー はっけん!\pよーし カメラを まわして\nインタビュー かいしよ!$"

GabbyAndTy_Text_GabbyDefeatFirstTime::
	.string "{JPN}マリ『わたしの めに くるいはないわ\nすごい トレーナーの はっけんよ!$"

GabbyAndTy_Text_GabbyNotEnoughMons::
	.string "{JPN}マリ『ポケモンを いっぱい つれてる\nつよい トレーナーって いない かしら?$"

GabbyAndTy_Text_TyPreFirstBattle::
	.string "{JPN}ダイ『おっ こんなところに\nつよそうな トレーナー はっけん!\lさっそく ろくが かいしだ!$"

GabbyAndTy_Text_TyDefeatFirstTime::
	.string "{JPN}ダイ『すごい トレーナーの はっけんだ\nこれは だいスクープだぞ!$"

GabbyAndTy_Text_TyNotEnoughMons::
	.string "{JPN}ダイ『きみは 1ぴきしか ポケモンを\nもって ないのかい?\pポケモンが いっぱい いたほうが\nいい えいぞうに なるんだが……$"

GabbyAndTy_Text_TyPostBattle::
	.string "{JPN}ダイ『さすがだな!\nいい えいぞうを とることが できたよ!$"

GabbyAndTy_Text_GabbyIntro::
	.string "{JPN}マリ『あ! あなたは\nこのあいだの {PLAYER}さん!\pよーし どのくらい つよく なったか\nさっそく インタビュー かいしよ!$"

GabbyAndTy_Text_GabbyDefeat::
	.string "{JPN}マリ『すごい たたかいだったわ!\nほら ちゃんと カメラにとった!?$"

GabbyAndTy_Text_KeepingAnEyeOutForYou::
	.string "{JPN}マリ『あなたの こと\nちゅうもく してるわ!$"

GabbyAndTy_Text_TyIntro::
	.string "{JPN}ダイ『きみは このあいだの!\pよーし この たたかいを\nすべて カメラに おさめてやる$"

GabbyAndTy_Text_TyDefeat::
	.string "{JPN}ダイ『いまの たたかいの すべてが\nこの カメラのなかに!$"

GabbyAndTy_Text_WhoAreYouInterview::
	.string "{JPN}マリ『すごい! すごい!\nあなた いったい なにもの!?\pさすが わたしたちが\nめを つけただけ あるわ!\p……あっ じつは わたしたち\nいろんな ばしょの いろんな トレーナーを\lインタビューして まわっているのよ\pだから すこしだけ\nインタビュー させて もらえないかな?$"

GabbyAndTy_Text_QuoteFromLastInterview::
	.string "{JPN}マリ『「{STR_VAR_1}!」\pおぼえてる? まえに たたかった とき\nあなたが いった きめゼリフよ\pわたしたち ちゃーんと\nおぼえてるん だからね!$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime::
	.string "{JPN}マリ『うーん さすがね!\pまえに たたかった ときより\nずっと つよく なってる!\pやっぱり わたしたちが みつけた\nトレーナー よね!\pところで どう?\nこんどこそ インタビューを\lうけて もらえないかな?$"

GabbyAndTy_Text_InterviewAgain::
	.string "{JPN}ところで どう?\nまた インタビュー うけてみる?$"

GabbyAndTy_Text_YouStompedUsInterviewAgain::
	.string "{JPN}そうそう まえに たたかった ときは\nても あしも でなかった のよねぇ……\pところで どう?\nまた インタビュー うけてみる?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain::
	.string "{JPN}そうそう まえに たたかった ときは\nボールを なげられ たんだっけ……\pもう びっくりして みんなに\nいいふらし ちゃったわよ!\pところで どう?\nまた インタビュー うけてみる?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain::
	.string "{JPN}そうそう まえに たたかった ときは\nどうぐを うまく つかわれて\lまけちゃった のよね\pところで どう?\nまた インタビュー うけてみる?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain::
	.string "{JPN}そうそう まえに たたかった ときは\nけっこう いいしょうぶ だったんだよね……\pところで どう?\nまた インタビュー うけてみる?$"

GabbyAndTy_Text_DescribeYourFeelings::
	.string "{JPN}ほんと!?\nありがとう!\pじゃあ たたかいの あとの\nかんそうを ビシッと ひとことで\lどうぞ!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou::
	.string "{JPN}マリ『んー!\nさいこうの きめゼリフね\pなんか いいテレビばんぐみが\nできそうな よかん!\pもしかしたら このことを\nテレビで ほうそうするかも しれないから\lテレビの チェックを わすれないでね!\pそれじゃあ\nまた どこかで!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut::
	.string "{JPN}マリ『そう……\pでも これからも がんばってね!\nあなたのこと ちゅうもく してるわ!$"
