VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "{JPN}とおく はなれた\nサイユウの おくちに ある という\lポケモン リーグ\pそこに あつまるのは\nすごうでの トレーナー ばかり ですって!$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "{JPN}ポケモン リーグは\nしてんのう 4にん つづけて\lしょうぶする という ルールらしいの!\pとちゅうで まけたら ひとりめ から\nやりなおし だなんて きびしいのね!$"
