PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "{JPN}この まちの あたらしい\nジムリーダーに なった センリさん\pとおくに すんでいた ごかぞくを\nこっちに よびよせた らしいのよね$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "{JPN}まえに いちど しょうぶ してみたけど\nさすがに センリさんは つよいね!\pなんというか こう……\p「ポケモン ひとすじに いきる!」\nっていうのを ヒシヒシと かんじたよ!$"

