SlateportCity_House_MapScripts::
	.byte 0

SlateportCity_House_EventScript_PokefanM::
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
	end

SlateportCity_House_EventScript_Girl::
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
	end

SlateportCity_House_Text_NatureToDoWithStatGains:
	.string "{JPN}わたしの ポケモン せっかちでね\nほかの ポケモンと くらべると\lすばやさが たかいんだわ\pせいかくで そだちやすい のうりょくに\nちがいが あるのかもな?$"

SlateportCity_House_Text_MustBeGoingToBattleTent:
	.string "{JPN}あなた ポケモントレーナーね\nカイナシティに きた っていうことは\lとうぜん バトルテントに いくのね!$"

