PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "{JPN}たびは いいぞ!\pわしも わかいときは あちこちの\nうみや やまを わたりあるいた ものだ!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "{JPN}あぁ……\pわたしも ポケモンと いっしょに\nぼうけんの たびに でかけて みたい……\pしめった くさむらに もぐったり\nごつごつの いわやまを のぼったり\lうみの あらなみを わたったり\lまっくらな どうくつを さまよったり……\pそれでいて ときには じぶんの おうちが\nこいしく なったりして……\pたびって いいよね!$"

